'use strict';
let PRODUCTS=[],CART_PHOTOS={};
const $=id=>document.getElementById(id);
const money=(value,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(value);
const CART_KEY='midnightCartV2';
function cartNotice(text){const target=$('cartStatus')||$('productNotice');if(target)target.textContent=text;}
function cart(){try{const raw=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(!Array.isArray(raw))return [];const lines=new Map();for(const x of raw){if(!x||!['string','number'].includes(typeof x.productId)||!['string','number'].includes(typeof x.variantId)||!Number.isInteger(x.qty)||x.qty<1||x.qty>99)continue;const productId=String(x.productId),variantId=String(x.variantId);if(!productId||!variantId)continue;const id=productId+':'+variantId;const previous=lines.get(id);lines.set(id,{id,productId,variantId,qty:Math.min(99,(previous?.qty||0)+x.qty)})}return [...lines.values()]}catch{cartNotice('Your saved bag could not be read. Browser storage may be unavailable or the saved data may be damaged.');return []}}
function saveCart(c){try{localStorage.setItem(CART_KEY,JSON.stringify(c))}catch{cartNotice('Your browser could not save this change. Enable browser storage and try again.');return false}updateCartCount();return true}
function updateCartCount(){if($('cartCount'))$('cartCount').textContent=cart().reduce((n,x)=>n+x.qty,0)}
function activeVariant(v){return !!v&&(!v.availability||v.availability==='active');}
function lineMoney(v,qty=1){const decimals=new Intl.NumberFormat('en-US',{style:'currency',currency:v.currency}).resolvedOptions().maximumFractionDigits;const scale=10**decimals;return {minor:Math.round(v.price*scale)*qty,scale,currency:v.currency};}
function cartTotals(){const totals=new Map();let unavailable=false;for(const x of cart()){const p=PRODUCTS.find(p=>p.id===x.productId),v=p?.variants.find(v=>String(v.id)===x.variantId);if(!activeVariant(v)){unavailable=true;continue}const value=lineMoney(v,x.qty),previous=totals.get(value.currency);totals.set(value.currency,{...value,minor:value.minor+(previous?.minor||0)})}if($('total'))$('total').textContent=[...totals.values()].map(t=>money(t.minor/t.scale,t.currency)).join(' + ')||money(0);if($('cartReview'))$('cartReview').textContent=unavailable?'Remove unavailable options before ordering. Their prices are excluded from the subtotal.':totals.size>1?'Your bag contains different currencies. Amounts are shown separately; currency conversion is not available.':'Prices reflect the current catalog. Shipping and taxes are separate.';}
function element(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function image(url,alt){const img=element('img');try{const u=new URL(url,location.href);if(u.protocol!=='https:'&&!(u.origin===location.origin&&u.pathname.includes('/assets/product-photos/')))return element('span','notice','Image unavailable');img.src=u.href}catch{return element('span','notice','Image unavailable')}img.alt=alt;img.loading='lazy';img.addEventListener('error',()=>img.replaceWith(element('span','notice','Image unavailable')));return img}
function empty(target,title,copy){target.replaceChildren();const box=element('div','empty');box.append(element('h3','',title),element('p','',copy));target.append(box)}
function productType(p){const name=p.name.toLowerCase();if(/hoodie/.test(name))return 'Hoodies';if(/sweatshirt/.test(name))return 'Sweatshirts';if(/t-shirt|tee|tank/.test(name))return 'Tees';if(/legging|pants|shorts/.test(name))return 'Bottoms';if(/backpack|fanny|bag/.test(name))return 'Bags';if(/bandana|gaiter/.test(name))return 'Accessories';return p.category==='Other pieces'?'Accessories':p.category;}
function catalogVariants(p){let variants=p.variants;if($('sizeFilter')?.value)variants=variants.filter(v=>v.size===$('sizeFilter').value);if($('availabilityFilter')?.value==='available')variants=variants.filter(activeVariant);if($('availabilityFilter')?.value==='unavailable')variants=variants.filter(v=>!activeVariant(v));return variants;}
function productPrice(p,filtered=false){const variants=filtered?catalogVariants(p):p.variants,available=variants.filter(activeVariant);return available.length?Math.min(...available.map(v=>v.price)):null;}
function renderProducts(target,list=PRODUCTS){target.replaceChildren();target.classList.toggle('single',list.length===1&&!target.dataset.catalog);if(!list.length){empty(target,PRODUCTS.length?'No matching pieces.':'The next chapter is coming.',target.dataset.catalog?'Try a different size, category or search, or clear the filters.':'Check back for the latest Midnight Designs collection.');return}for(const p of list){const filtered=!!target.dataset.catalog,variants=filtered?catalogVariants(p):p.variants,available=variants.filter(activeVariant),card=element('article','product-card'),link=element('a','product-image');card.dataset.productId=p.id;link.href='product.html?id='+encodeURIComponent(p.id);const photo=image(p.image,p.name);if(target.dataset.featured)photo.loading='eager';link.append(photo);const body=element('div','product-body'),meta=element('div','product-meta');body.append(element('div','eyebrow',filtered?productType(p):p.category));const name=element('a');name.href=link.href;name.append(element('h3','',p.name));meta.append(name);if(available.length){const prices=available.map(v=>v.price);meta.append(element('div','price',(Math.min(...prices)!==Math.max(...prices)?'From ':'')+money(Math.min(...prices),available[0].currency)))}else meta.append(element('span','availability-badge unavailable',filtered&&p.variants.some(activeVariant)?'Unavailable options':'Unavailable'));body.append(meta);if(filtered){if(available.length)body.append(element('span','availability-badge',available.length<variants.length?'Some options unavailable':'Available options'));const sizes=[...new Set(available.map(v=>v.size).filter(Boolean))];body.append(element('p','catalog-sizes',sizes.length?'Available sizes: '+sizes.join(' · '):'No available options'+($('sizeFilter').value?' in '+$('sizeFilter').value:'.')));if(available.length<variants.length&&available.length)body.append(element('p','notice','Check available size and color combinations.'));}card.append(link,body);target.append(card)}}
function homeProducts(){const ids=($('grid')?.dataset.featured||'').split(',').filter(Boolean);const selected=ids.map(id=>PRODUCTS.find(p=>p.id===id&&p.variants.some(activeVariant))).filter(Boolean);for(const p of PRODUCTS)if(selected.length<4&&!selected.includes(p)&&p.variants.some(activeVariant))selected.push(p);return selected.slice(0,4)}
function shop(){const sizes=['2XS','XS','S','M','L','XL','2XL','3XL','4XL','5XL','6XL','S/M','M/L','One size'];const categories=[...new Set(PRODUCTS.map(productType))];for(const c of categories.sort()){const o=element('option','',c);o.value=c;$('category').append(o)}const actual=[...new Set(PRODUCTS.flatMap(p=>p.variants.map(v=>v.size)).filter(Boolean))];actual.sort((a,b)=>{const i=sizes.indexOf(a),j=sizes.indexOf(b);return (i<0?99:i)-(j<0?99:j)||a.localeCompare(b)});for(const s of actual){const o=element('option','',s);o.value=s;$('sizeFilter').append(o)}
const fields={q:'search',type:'category',size:'sizeFilter',availability:'availabilityFilter',sort:'sort'};
function restore(){const params=new URLSearchParams(location.search);for(const [key,id] of Object.entries(fields)){const n=$(id),value=params.get(key)||'';n.value=id==='search'?value:[...n.options].some(o=>o.value===value)?value:n.options[0].value;}}
function apply(write=true){const tokens=$('search').value.toLowerCase().trim().split(/\s+/).filter(Boolean);let list=PRODUCTS.filter(p=>{const text=[p.name,p.description,productType(p),...p.variants.flatMap(v=>[v.name,v.size,v.color])].join(' ').toLowerCase();if(tokens.some(t=>!text.includes(t))||($('category').value&&productType(p)!==$('category').value))return false;if($('sizeFilter').value&&!p.variants.some(v=>v.size===$('sizeFilter').value))return false;return $('availabilityFilter').value==='unavailable'?!catalogVariants(p).length?(!p.variants.length&&!$('sizeFilter').value):catalogVariants(p).some(v=>!activeVariant(v)):$('availabilityFilter').value==='available'?catalogVariants(p).some(activeVariant):true});
const sort=$('sort').value;if(sort!=='default')list.sort((a,b)=>{if(sort==='name')return a.name.localeCompare(b.name);const x=productPrice(a,true),y=productPrice(b,true);if(x===null)return y===null?0:1;if(y===null)return -1;return (sort==='low'?1:-1)*(x-y)});renderProducts($('grid'),list);$('catalogStatus').textContent=list.length+' of '+PRODUCTS.length+' pieces'+($('sizeFilter').value?' · Size '+$('sizeFilter').value:'');$('clearFilters').disabled=!Object.values(fields).some(id=>$(id).value&&$(id).value!=='default');if(write){const url=new URL(location.href);for(const [key,id] of Object.entries(fields)){const value=$(id).value;if(value&&value!=='default')url.searchParams.set(key,value);else url.searchParams.delete(key)}history.replaceState(null,'',url)}}
for(const id of Object.values(fields))$(id).addEventListener(id==='search'?'input':'change',()=>apply());$('clearFilters').onclick=()=>{for(const id of Object.values(fields))$(id).value=id==='sort'?'default':'';apply()};window.addEventListener('popstate',()=>{restore();apply(false)});restore();apply(false);}
function product(){const p=PRODUCTS.find(p=>p.id===new URLSearchParams(location.search).get('id'));if(!p||!p.variants.length){$('name').textContent='This piece is unavailable.';$('description').textContent='Explore the collection for available pieces.';$('variant').replaceChildren(element('option','','Unavailable'));return}document.title=p.name+' | Midnight Designs';$('name').textContent=p.name;$('cat').textContent=p.category;$('description').textContent=p.description||'A Midnight Designs piece for your after-hours rotation.';$('visual').append(image(p.image,p.name));for(const url of [...new Set([p.image,...(p.images||[])])]){const button=element('button');button.type='button';button.setAttribute('aria-label','View another image of '+p.name);button.append(image(url,''));button.onclick=()=>$('visual').replaceChildren(image(url,p.name));$('gallery').append(button)}$('variant').replaceChildren();for(const v of p.variants){const option=element('option','',v.name+' — '+(activeVariant(v)?money(v.price,v.currency):'Unavailable'));option.value=v.id;$('variant').append(option)}$('variant').disabled=false;$('add').disabled=false;function update(){const v=p.variants.find(v=>String(v.id)===$('variant').value);$('price').textContent=v?money(v.price,v.currency):'Unavailable';$('add').disabled=!activeVariant(v)}$('variant').onchange=update;update();$('add').onclick=()=>{const v=p.variants.find(v=>String(v.id)===$('variant').value);if(!activeVariant(v)){cartNotice('This option is unavailable. Choose another size or color.');return}const c=cart(),key=p.id+':'+v.id,existing=c.find(x=>x.id===key);if(existing?.qty>=99){cartNotice('You already have the maximum of 99 for this option.');return}if(existing)existing.qty++;else c.push({id:key,productId:p.id,variantId:String(v.id),qty:1});if(saveCart(c)){$('productNotice').textContent='Added to your bag: '+(v.size||'One size')+' · '+(v.color||'Printed design as pictured')+'.';$('add').textContent='Added ✓';setTimeout(()=>$('add').textContent='Add to bag',1500)}}}

function renderCart(){const c=cart(),box=$('items');box.replaceChildren();if(!c.length)box.append(element('p','notice','Your bag is empty. Find your next piece in the collection.'));for(const x of c){const p=PRODUCTS.find(p=>p.id===x.productId),v=p?.variants.find(v=>String(v.id)===x.variantId),available=activeVariant(v);const row=element('div','item'),details=element('div');row.dataset.key=x.id;if(p){const gallery=CART_PHOTOS[p.id];const candidates=gallery?.originalImage===p.image?gallery.photos.filter(photo=>photo.storeVariantIds.includes(x.variantId)):[];const photo=candidates.find(photo=>photo.category==='product'&&/front/i.test(photo.view))||candidates.find(photo=>photo.category==='product')||candidates[0];row.append(image(photo?.image||p.image,p.name+' · '+(v?.size||'')+' · '+(v?.color||'Printed design as pictured')))}else row.append(element('span','','—'));const name=element('a');if(p)name.href='product.html?id='+encodeURIComponent(p.id);name.append(element('b','',p?.name||'Unavailable piece'));details.append(name,element('small','',v?.name||'This option is no longer listed.'),element('small','cart-option','Size: '+(v?.size||'Not supplied')+' · Color / base: '+(v?.color||'Printed design as pictured')));if(!available)details.append(element('small','error','Unavailable — remove this option.'));const remove=element('button','','Remove');remove.type='button';remove.setAttribute('aria-label','Remove '+(p?.name||'unavailable item')+' '+(v?.size||'')+' '+(v?.color||''));remove.onclick=()=>{if(saveCart(cart().filter(line=>line.id!==x.id))){cartNotice('Item removed.');renderCart()}};details.append(remove);const price=element('div');if(available){details.append(element('small','cart-unit-price','Unit price: '+money(v.price,v.currency)));const line=element('div','price');const updateLine=qty=>{const value=lineMoney(v,qty);line.textContent=money(value.minor/value.scale,value.currency)};updateLine(x.qty);price.append(line);const qty=element('input');qty.type='number';qty.min=1;qty.max=99;qty.step=1;qty.value=x.qty;qty.setAttribute('aria-label','Quantity for '+p.name+' '+(v.size||'')+' '+(v.color||''));function change(){const n=Number(qty.value);if(!Number.isInteger(n)||n<1||n>99)return;const current=cart(),item=current.find(item=>item.id===x.id);if(!item){renderCart();return}if(item.qty===n)return;const previous=item.qty;item.qty=n;if(saveCart(current)){cartNotice('Bag updated.');updateLine(n);cartTotals()}else qty.value=previous}qty.oninput=change;qty.onchange=()=>{change();const saved=cart().find(item=>item.id===x.id);if(saved)qty.value=saved.qty};price.append(qty)}row.append(details,price);box.append(row)}cartTotals();updateCartCount()}
window.addEventListener('storage',event=>{if(event.key===CART_KEY||event.key===null){updateCartCount();if($('items')&&PRODUCTS.length){renderCart();cartNotice('Bag updated from another tab.')}}});

async function init(){updateCartCount();try{const response=await fetch('products.json',{cache:'no-cache'});if(!response.ok)throw Error('catalog');const data=await response.json();if(!Array.isArray(data.products))throw Error('catalog');PRODUCTS=data.products.filter(p=>typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.variants)&&p.variants.every(v=>Number.isFinite(v.price)&&v.price>0&&typeof v.currency==='string'));if(PRODUCTS.length&&document.querySelector('.hero-art')){const p=document.body.classList.contains('home')?homeProducts()[0]||PRODUCTS[0]:PRODUCTS[0],link=element('a','hero-product');link.href='product.html?id='+encodeURIComponent(p.id);const heroImage=image(p.image,p.name);heroImage.loading='eager';heroImage.fetchPriority='high';link.append(heroImage);link.setAttribute('aria-label','View '+p.name);document.querySelector('.hero-art').append(link);const label=document.querySelector('.art-bottom');if(label)label.textContent=p.name+' / FROM '+money(Math.min(...p.variants.map(v=>v.price)),p.variants[0].currency)}if($('grid'))$('search')?shop():renderProducts($('grid'),document.body.classList.contains('home')?homeProducts():PRODUCTS.slice(0,6));if($('variant'))product();if($('items')){try{const photos=await fetch('product-photos.json',{signal:AbortSignal.timeout(4000)});if(photos.ok)CART_PHOTOS=(await photos.json()).products||{}}catch{}renderCart()}}catch{if($('grid'))empty($('grid'),'The collection could not load.','Please refresh the page or try again shortly.');if($('name'))$('name').textContent='The product could not load.';if($('items'))$('items').textContent='Your bag could not load. Please try again shortly.'}}
init();
