'use strict';
(()=>{
 const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
 const bag=()=>{try{return JSON.parse(localStorage.getItem('midnightCartV2')||'[]').map(({productId,variantId,qty})=>({productId:String(productId),variantId:String(variantId),qty}));}catch{return [];}};
 let endpoint,quote=null,busy=false;
 const status=text=>{const target=$('checkoutStatus')||$('paymentStatus');if(target)target.textContent=text;};
 async function api(path,data){const r=await fetch(endpoint+path,{...(data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(30000)});let result;try{result=await r.json();}catch{throw Error('The payment connection returned an unexpected response.');}if(!r.ok)throw Error(result.error||'Checkout could not be completed.');return result;}
 async function configure(){const r=await fetch('request-service-config.json',{cache:'no-store'});if(!r.ok)throw Error('The payment connection could not be checked.');const config=await r.json();if(!config.url)throw Error('Checkout is not open yet. Payment setup is in progress.');const u=new URL(config.url);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('The payment connection is unavailable.');endpoint=u.origin;return api('/api/checkout/config');}
 function invalidate(){quote=null;if($('shippingOptions'))$('shippingOptions').replaceChildren();if($('payNow'))$('payNow').disabled=true;if($('quoteSummary'))$('quoteSummary').textContent='';}
 if($('shippingForm')){
  $('shippingForm').addEventListener('input',invalidate);window.addEventListener('storage',e=>{if(e.key==='midnightCartV2'||e.key===null)invalidate();});
  $('shippingForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;invalidate();$('calculateShipping').disabled=true;status('Calculating shipping…');try{const items=bag();if(!items.length)throw Error('Add a piece to your bag first.');const recipient=Object.fromEntries(new FormData(e.currentTarget));quote=await api('/api/checkout/quote',{items,recipient});quote.bag=JSON.stringify(items);quote.recipient=JSON.stringify(recipient);for(const rate of quote.shipping){const option=document.createElement('option');option.value=rate.id;option.textContent=rate.name+' — '+money(rate.amount);$('shippingOptions').append(option);}$('quoteSummary').textContent='Items: '+money(quote.subtotal)+'. Shipping shown above; taxes calculated at checkout.';$('payNow').disabled=false;status(quote.testMode?'Test checkout: no real charge will be made.':'Review your shipping option, then continue to secure payment.');}catch(err){status(err.message);}finally{busy=false;$('calculateShipping').disabled=false;}};
  $('payNow').onclick=async()=>{if(busy||!quote)return;if(quote.bag!==JSON.stringify(bag())||quote.recipient!==JSON.stringify(Object.fromEntries(new FormData($('shippingForm'))))){invalidate();status('Your bag or address changed. Calculate shipping again.');return;}busy=true;$('payNow').disabled=true;status('Opening secure checkout…');try{const result=await api('/api/checkout/session',{quoteId:quote.quoteId,receiptToken:quote.receiptToken,shippingId:$('shippingOptions').value});const u=new URL(result.url);if(u.origin!=='https://checkout.stripe.com')throw Error('The payment page could not be verified.');try{sessionStorage.setItem('midnightCheckoutBag:'+result.orderId,quote.bag);}catch{}location.assign(u.href);}catch(err){status(err.message);$('payNow').disabled=false;}finally{busy=false;}};
  configure().then(config=>{if(!config.enabled){status('Checkout is not open yet. Payment setup is in progress.');return;}$('shippingForm').hidden=false;$('calculateShipping').disabled=false;const select=$('country_code');for(const country of config.countries){const option=document.createElement('option');option.value=country;try{option.textContent=new Intl.DisplayNames(['en'],{type:'region'}).of(country);}catch{option.textContent=country;}select.append(option);}status(config.testMode?'Stripe test mode — no real payments.':'Enter your delivery address to calculate shipping.');if(new URLSearchParams(location.search).get('checkout')==='cancelled')status('Payment cancelled. Your bag is still saved.');}).catch(err=>status(err.message));
 }
 if($('paymentStatus')){
  const access=new URLSearchParams(location.hash.slice(1));let order=access.get('order'),token=access.get('access');
  if(order&&token){try{sessionStorage.setItem('midnightReceipt',JSON.stringify({order,token}));}catch{}history.replaceState(null,'',location.pathname);}else{try{({order,token}=JSON.parse(sessionStorage.getItem('midnightReceipt')||'{}'));}catch{}}
  if(!order||!token){status('This page does not confirm a payment. Reopen the checkout receipt link.');return;}
  let attempts=0;async function check(){try{const result=await api('/api/checkout/status',{orderId:order,receiptToken:token});$('orderNumber').textContent='Order '+result.id;const paid=result.status==='paid';status(paid?(result.testMode?'Test payment confirmed. No real charge was made.':'Payment confirmed. Your order is awaiting fulfillment.'):(['expired','failed'].includes(result.status)?'Payment was not completed. Your bag is still saved.':'Waiting for payment confirmation. Do not pay again.'));if(paid){$('paidTotal').textContent='Total paid: '+money(result.total);try{const before=sessionStorage.getItem('midnightCheckoutBag:'+order);if(before&&before===JSON.stringify(bag())){localStorage.removeItem('midnightCartV2');const count=$('cartCount');if(count)count.textContent='0';}sessionStorage.removeItem('midnightCheckoutBag:'+order);}catch{}return;}if(!['expired','failed'].includes(result.status)&&++attempts<12)setTimeout(check,5000);}catch(err){status(err.message+' Your payment has not been confirmed on this page.');}}
  configure().then(check).catch(err=>status(err.message));
 }
})();
