'use strict';
(()=>{
if(!/\/(?:index\.html|shop\.html|cart\.html|product\.html|designs\.html|products\/\d+\.html)?$/.test(location.pathname))return;
const consentKey='midnightDesignAnalyticsConsentV1',idKey='midnightDesignAnalyticsVisitorV1';let url=null,enabled=false,visitor=null;const seen=new Set();
const blocked=()=>navigator.globalPrivacyControl===true||navigator.doNotTrack==='1';const read=()=>{try{return JSON.parse(localStorage.getItem(consentKey)||'null')}catch{return null;}};
const id=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map((n,i)=>([4,6,8,10].includes(i)?'-':'')+n.toString(16).padStart(2,'0')).join('');
function event(type,{designId,productId}={}){if(!enabled||!url||blocked()||!visitor)return;if(type==='view'){const key=designId||productId;if(!key||seen.has(key))return;seen.add(key);}const payload={eventId:id(),visitorId:visitor,type,device:innerWidth<768?'phone':innerWidth<1025?'tablet':'desktop',...(designId?{designId}:{}),...(productId?{productId}:{})};fetch(url+'/api/design-events',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true}).then(r=>{if(!r.ok&&type==='view')seen.delete(designId||productId);}).catch(()=>{if(type==='view')seen.delete(designId||productId);});}
function snapshot(){const data=window.midnightAnalyticsSnapshot?.(),product=document.body.dataset.productId||new URLSearchParams(location.search).get('id');if(document.getElementById('variant')&&/^\d+$/.test(product||''))event('view',{productId:product});else if(data?.product?.[0]?.item_id)event('view',{productId:String(data.product[0].item_id)});const dialog=document.getElementById('designDialog');if(dialog?.open&&dialog.dataset.designId)event('view',{designId:dialog.dataset.designId});}
function stop(){enabled=false;visitor=null;seen.clear();try{localStorage.removeItem(idKey);}catch{}}
function start(){if(!url||blocked()||read()?.value!=='allow')return;try{visitor=localStorage.getItem(idKey);if(!/^[a-f0-9-]{36}$/.test(visitor||'')){visitor=id();localStorage.setItem(idKey,visitor);}enabled=true;snapshot();}catch{stop();status.textContent='Your preference could not be saved. Design analytics stays off.';}}
const dialog=document.createElement('dialog');dialog.className='analytics-panel';dialog.setAttribute('aria-label','Optional design analytics');const heading=document.createElement('h2');heading.textContent='Optional design analytics';const copy=document.createElement('p');copy.textContent='Allow anonymous browsing signals to help Midnight Designs compare artwork views, likes and cart interest. Uploads, messages, addresses and payment details are excluded. Shopping and design voting work with this off.';const status=document.createElement('p');status.className='notice';status.setAttribute('role','status');const actions=document.createElement('div');actions.className='hero-actions';const allow=document.createElement('button');allow.type='button';allow.className='btn dark';allow.textContent='Allow design analytics';const deny=document.createElement('button');deny.type='button';deny.className='btn outline';deny.textContent='Keep design analytics off';actions.append(allow,deny);dialog.append(heading,copy,status,actions);document.body.append(dialog);
function show(){allow.hidden=!url||blocked();status.textContent=blocked()?'Your browser privacy preference keeps design analytics off.':!url?'Shared design analytics is not connected. No browsing events are sent.':enabled?'Optional design analytics is on. You can turn it off here.':'Design analytics is off unless you allow it.';if(!dialog.open)dialog.show();}
allow.onclick=()=>{if(!url||blocked())return;try{localStorage.setItem(consentKey,JSON.stringify({value:'allow',at:Date.now()}));start();dialog.close();}catch{status.textContent='Your preference could not be saved. Analytics stays off.';}};deny.onclick=()=>{try{localStorage.setItem(consentKey,JSON.stringify({value:'deny',at:Date.now()}));}catch{}stop();dialog.close();};const footer=document.querySelector('.footer');if(footer){const b=document.createElement('button');b.type='button';b.className='analytics-preferences text-link';b.textContent='Design analytics preferences';b.onclick=show;footer.append(b);}
document.addEventListener('midnight:design-view',e=>event('view',{designId:e.detail?.designId}));document.addEventListener('midnight:design-like',e=>event('like',{designId:e.detail?.designId}));document.addEventListener('midnight:commerce',e=>{const detail=e.detail||{};if(detail.event==='view_item')for(const item of detail.items||[])event('view',{productId:String(item.item_id)});if(detail.event==='add_to_cart')for(const item of detail.items||[])event('cart',{productId:String(item.item_id)});});window.addEventListener('storage',e=>{if(e.key===consentKey){if(read()?.value==='allow')start();else stop();}});
fetch('request-service-config.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{if(c.url){const u=new URL(c.url);if(u.protocol==='https:'&&!u.username&&!u.password&&u.pathname==='/'&&!u.search&&!u.hash)url=u.origin;}if(blocked())stop();else if(read()?.value==='allow')start();else if(url&&!read())show();}).catch(()=>{});
})();
