'use strict';
(()=>{
const newVoterId=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map((n,i)=>([4,6,8,10].includes(i)?'-':'')+n.toString(16).padStart(2,'0')).join('');
const key='midnightDesignVotes',pendingKey='midnightDesignVotePending';let preferences={},pending={},client=null,storage=true,connected=false;const listeners=new Set(),queues=new Map(),versions={};let dialogRefresh=()=>{};
try{preferences=JSON.parse(localStorage.getItem(key)||'{}');pending=JSON.parse(localStorage.getItem(pendingKey)||'{}');if(!preferences||Array.isArray(preferences)||typeof preferences!=='object')preferences={};if(!pending||typeof pending!=='object'||Array.isArray(pending))pending={};client=localStorage.getItem('midnightDesignVoterId');if(!/^[a-f0-9-]{36}$/.test(client||'')){client=newVoterId();localStorage.setItem('midnightDesignVoterId',client);}}catch{storage=false;client=newVoterId();}
const service=fetch('request-service-config.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{if(!c.url)return null;const u=new URL(c.url);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)return null;connected=true;update();return u.origin;}).catch(()=>null);
function save(){try{localStorage.setItem(key,JSON.stringify(preferences));localStorage.setItem(pendingKey,JSON.stringify(pending));}catch{storage=false;}}
function report(message){const n=document.getElementById('designVoteStatus');if(n)n.textContent=message;}
function update(){listeners.forEach(fn=>fn());dialogRefresh();const button=document.getElementById('retryDesignVotes');if(button)button.hidden=!connected||!Object.keys(pending).length;}
function send(id,value,generation=versions[id]||0){const previous=queues.get(id)||Promise.resolve();const work=previous.catch(()=>{}).then(async()=>{const url=await service;if(!url){report(storage?'Saved on this device. Shared feedback collection is not connected yet.':'Selected for this visit. Browser storage and shared collection are unavailable.');return;}try{const r=await fetch(url+'/api/design-votes',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({designId:id,choice:value,voterId:client})});if(!r.ok)throw Error();if(preferences[id]===value&&(versions[id]||0)===generation){delete pending[id];save();report('Feedback received by Midnight Designs. Thank you.');}}catch{report('Saved on this device. Feedback could not reach Midnight Designs; you can retry.');}update();});queues.set(id,work);return work;}
function choose(id,vote){versions[id]=(versions[id]||0)+1;preferences[id]=preferences[id]===vote?null:vote;pending[id]=true;save();update();send(id,preferences[id]);}
function controls(design){if(design.kind==='reference')return null;const wrap=document.createElement('div');wrap.className='design-vote-actions';for(const [value,label]of [['like','❤️ Like'],['dislike','Not for me']]){const b=document.createElement('button');b.type='button';b.className='btn outline';b.textContent=label;b.dataset.designVote=design.id;b.dataset.vote=value;b.setAttribute('aria-label',label+' — '+design.name);const refresh=()=>b.setAttribute('aria-pressed',String(preferences[design.id]===value));refresh();listeners.add(refresh);b.onclick=()=>choose(design.id,value);wrap.append(b);}return wrap;}
function resetCardListeners(){listeners.clear();}
function dialog(design){for(const value of ['like','dislike']){const b=document.getElementById(value+'Design');b.disabled=design.kind==='reference';b.setAttribute('aria-pressed',String(preferences[design.id]===value));b.onclick=()=>choose(design.id,value);}const refresh=()=>{for(const value of ['like','dislike'])document.getElementById(value+'Design').setAttribute('aria-pressed',String(preferences[design.id]===value));};dialogRefresh=refresh;refresh();}
document.getElementById('retryDesignVotes')?.addEventListener('click',()=>{for(const id of Object.keys(pending))send(id,['like','dislike'].includes(preferences[id])?preferences[id]:null);});
window.midnightDesignVotes={controls,dialog,resetCardListeners};update();
})();