'use strict';
(()=>{
const newVoterId=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map((n,i)=>([4,6,8,10].includes(i)?'-':'')+n.toString(16).padStart(2,'0')).join('');
const form=document.getElementById('designRatingForm');if(!form)return;
const $=id=>document.getElementById(id),key='midnightDesignRatings',pendingKey=key+'Pending',fields=['overall','artwork','colors','style','wear','buy','complexity'];
let ratings={},pending={},active=null,storage=true,voter;const queues=new Map(),versions={};
try{ratings=JSON.parse(localStorage.getItem(key)||'{}');pending=JSON.parse(localStorage.getItem(pendingKey)||'{}');if(!ratings||Array.isArray(ratings)||typeof ratings!=='object')ratings={};if(!pending||Array.isArray(pending)||typeof pending!=='object')pending={};voter=localStorage.getItem('midnightDesignVoterId');if(!/^[a-f0-9-]{36}$/.test(voter||'')){voter=newVoterId();localStorage.setItem('midnightDesignVoterId',voter);}}catch{storage=false;voter=newVoterId();}
const service=fetch('request-service-config.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{if(!c.url)return null;const u=new URL(c.url);if(u.protocol!=='https:'||u.username||u.password||u.pathname!=='/'||u.search||u.hash)return null;return u.origin;}).catch(()=>null);
function save(){try{localStorage.setItem(key,JSON.stringify(ratings));localStorage.setItem(pendingKey,JSON.stringify(pending));}catch{storage=false;}}
function report(id,text,retry=false){if(active?.id!==id)return;$('designRatingStatus').textContent=text;$('retryDesignRating').hidden=!retry;}
function send(id,rating){const version=versions[id]||0;const task=(queues.get(id)||Promise.resolve()).then(async()=>{const url=await service;if(!url){report(id,storage?(rating?'Rating saved on this device. Shared ratings are not connected yet.':'Rating removed from this device. Shared ratings are not connected yet.'):'Browser storage is unavailable. This rating will be lost when you leave.');return;}try{const r=await fetch(url+'/api/design-ratings',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({designId:id,voterId:voter,rating,device:innerWidth<768?'phone':innerWidth<1025?'tablet':'desktop'})});if(!r.ok)throw Error();if(version===(versions[id]||0)){delete pending[id];save();report(id,rating?'Rating received by Midnight Designs.':'Rating removed from shared feedback.');}}catch{if(version===(versions[id]||0))report(id,'Could not share your rating. '+(storage?'Saved on this device.':'Keep this page open.'),true);}});queues.set(id,task);}
function commit(rating){const id=active.id;versions[id]=(versions[id]||0)+1;if(rating)ratings[id]=rating;else delete ratings[id];pending[id]=true;save();$('removeDesignRating').hidden=!rating;send(id,rating);}
form.onsubmit=e=>{e.preventDefault();if(!active||active.kind==='reference'||!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));for(const f of fields.slice(0,4))data[f]=Number(data[f]);commit(data);};
$('removeDesignRating').onclick=()=>{if(!active)return;commit(null);form.reset();};$('retryDesignRating').onclick=()=>{if(active)send(active.id,ratings[active.id]||null);};
window.midnightDesignRatings={open(d){active=d;$('ratingSection').hidden=!d||d.kind==='reference';form.reset();if(!d||d.kind==='reference')return;const rating=ratings[d.id];if(rating)for(const f of fields)form.elements.namedItem(f).value=rating[f];$('removeDesignRating').hidden=!rating;report(d.id,rating?'Your saved rating. Change any answer and save to update it.':'Choose all seven answers, then save your rating.',!!pending[d.id]);if(pending[d.id])send(d.id,rating||null);}};
})();
