'use strict';
(()=>{
const $=id=>document.getElementById(id),form=$('feedbackForm'),key='midnight-feedback-draft-v1',types=['Design idea','Product request','Clothing request','Site problem','Feature suggestion','Complaint','General comment'];let service=null,busy=false,record=null,signature='',storage=true;
const uid=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map((n,i)=>([4,6,8,10].includes(i)?'-':'')+n.toString(16).padStart(2,'0')).join('');
function fields(){return Object.fromEntries(new FormData(form));}function save(){try{localStorage.setItem(key,JSON.stringify({fields:fields(),record,signature,at:Date.now()}));storage=true;return true;}catch{storage=false;return false;}}
try{const draft=JSON.parse(localStorage.getItem(key)||'null');if(draft&&Date.now()-draft.at<7*86400000){for(const [name,value]of Object.entries(draft.fields||{})){const field=form.elements.namedItem(name);if(field&&typeof value==='string')field.value=value.slice(0,field.maxLength>0?field.maxLength:10000);}if(draft.record&&typeof draft.signature==='string'&&/^[a-f0-9-]{36}$/.test(draft.record.id||'')){record=draft.record;signature=draft.signature;}$('feedbackStatus').textContent='Your draft was restored from this browser. Nothing has been submitted automatically.';}}catch{storage=false;}
function prepare(){if(!form.reportValidity())return null;const data=fields();for(const k of Object.keys(data))data[k]=data[k].trim();if(!types.includes(data.type))return null;const sig=JSON.stringify(data),brief=['Feedback type: '+data.type,...(data.product?['Related product / clothing: '+data.product]:[]),...(data.page?['Related page: '+data.page]:[]),'',data.details].join('\n');if(!record||signature!==sig){const t=new Date().toISOString();record={id:uid(),type:data.type,status:'New',title:data.title,name:data.name,email:data.email,product:data.product,budget:'',deadline:'',related:'',details:brief,files:'',notes:'',createdAt:t,updatedAt:t};signature=sig;}save();return record;}
function email(r){$('emailFeedback').href='mailto:midnightdesign107@gmail.com?subject='+encodeURIComponent(r.type+' — '+r.title)+'&body='+encodeURIComponent('From: '+r.name+'\nReply email: '+r.email+'\nRequest file ID: '+r.id+'\n\n'+r.details);}
form.oninput=()=>{if(!busy){save();$('feedbackStatus').textContent=storage?'Draft saved on this device. Nothing has been submitted.':'Browser storage is unavailable. Keep this page open to retain your draft.';}};
$('downloadFeedback').onclick=()=>{const r=prepare();if(!r)return;const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,kind:'midnight-design-request',request:r},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='midnight-feedback-request.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('feedbackStatus').textContent='Request file downloaded for Midnight Designs to import. Attach it to your email. Nothing has been submitted automatically.';};
$('emailFeedback').onclick=e=>{const r=prepare();if(!r){e.preventDefault();return;}email(r);$('feedbackStatus').textContent='Your email app will open. Review the message, attach the downloaded request file if available, and press Send there. Delivery is not confirmed here.';};
form.onsubmit=async e=>{e.preventDefault();if(busy)return;const r=prepare();if(!r)return;email(r);if(!service){$('feedbackStatus').textContent=(storage?'Feedback saved on this device. ':'Browser storage is unavailable. ')+'Shared submission is not connected yet. Use Prepare email and/or download the request file for Midnight Designs.';return;}busy=true;$('submitFeedback').disabled=true;$('feedbackStatus').textContent='Submitting feedback…';try{const response=await fetch(service+'/api/requests',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:r.type,title:r.title,name:r.name,email:r.email,brief:r.details,submissionId:r.id})}),data=await response.json();if(!response.ok)throw Error(data.error||'Submission failed.');const link=new URL(data.link);if(link.origin!==service||link.pathname!=='/'||!/^#access=[a-f0-9]{64}$/.test(link.hash)||!/^[a-f0-9-]{36}$/.test(data.id))throw Error('Could not confirm the private conversation. Contact Midnight Designs before submitting again.');$('feedbackReceiptType').textContent=r.type+' · New';$('feedbackReceiptId').textContent='Request ID: '+data.id;$('feedbackConversation').href=link.href;form.hidden=true;$('feedbackReceipt').hidden=false;$('feedbackStatus').textContent='';try{localStorage.removeItem(key);}catch{}$('feedbackReceipt').scrollIntoView({block:'start'});}catch(error){$('feedbackStatus').textContent=error.message+' '+(storage?'Your draft is saved here.':'Keep this page open.')+' Retry with the same details to avoid a duplicate request, or contact midnightdesign107@gmail.com.';}finally{busy=false;$('submitFeedback').disabled=false;}};
$('anotherFeedback').onclick=()=>{form.reset();form.hidden=false;$('feedbackReceipt').hidden=true;$('feedbackConversation').removeAttribute('href');record=null;signature='';try{localStorage.removeItem(key);}catch{}$('feedbackStatus').textContent='';$('feedbackType').focus();};
fetch('request-service-config.json',{cache:'no-store'}).then(r=>r.json()).then(config=>{if(config.url){const u=new URL(config.url);if(u.protocol==='https:'&&!u.username&&!u.password&&u.pathname==='/'&&!u.search&&!u.hash)service=u.origin;}$('feedbackConnection').textContent=service?'Connected submissions go to Midnight Designs’ Requests dashboard and open a private conversation.':'Shared submission is not connected yet. Save a draft, prepare an email to midnightdesign107@gmail.com, or download a request file for manual intake.';$('submitFeedback').textContent=service?'Submit feedback':'Save feedback';}).catch(()=>{$('feedbackConnection').textContent='Submission connection unavailable. Prepare an email or download a request file instead.';});
})();
