'use strict';
(async()=>{
const $=id=>document.getElementById(id);if(!$('conceptCanvas'))return;
const uid=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const n=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
const message=t=>$('studioStatus').textContent=t;
let items,designs;try{const rs=await Promise.all([fetch('clothing.json'),fetch('designs.json')]);if(rs.some(r=>!r.ok))throw Error();[items,designs]=await Promise.all(rs.map(r=>r.json()));}catch{message('The design catalog could not load. Refresh to try again.');return;}
const shapes={tee:'M180 160 L275 120 Q360 170 445 120 L540 160 L640 320 L530 370 L475 280 L475 690 L245 690 L245 280 L190 370 L80 320 Z',long:'M180 160 L275 120 Q360 165 445 120 L540 160 L680 590 L565 620 L475 300 L475 690 L245 690 L245 300 L155 620 L40 590 Z',pants:'M225 120 L495 120 L520 700 L385 700 L360 345 L335 700 L200 700 Z',shorts:'M225 190 L495 190 L530 600 L390 600 L360 390 L330 600 L190 600 Z',dress:'M280 100 L310 100 Q360 145 410 100 L440 100 L435 295 L555 700 L165 700 L285 295 Z',skirt:'M270 160 L450 160 L575 680 L145 680 Z',bra:'M230 180 L275 180 L285 280 Q360 320 435 280 L445 180 L490 180 L525 450 L195 450 Z',swimsuit:'M245 110 L290 110 Q360 190 430 110 L475 110 L460 300 L495 475 L410 500 L380 665 L340 665 L310 500 L225 475 L260 300 Z',bag:'M250 210 Q250 115 360 115 Q470 115 470 210 L500 270 L500 670 L220 670 L220 270 Z',bandana:'M120 160 L600 160 L360 690 Z'};
const sleeve='M260 160 L455 160 L500 650 L220 650 Z',hood='M185 660 Q150 360 270 170 Q390 60 515 240 L505 670 Z',pocket='M220 280 L500 280 L540 520 L180 520 Z',leg='M245 140 L465 140 L490 700 L220 700 Z',waist='M160 300 L560 300 L560 430 L160 430 Z';
let assets=new Map(),layers=[],activeId=null,view='front',guides=true,db=null,loadSerial=0;
const query=new URLSearchParams(location.search);
for(const item of items){const o=n('option','',item.name);o.value=item.id;$('itemSelect').append(o);}if(items.some(i=>i.id===query.get('item')))$('itemSelect').value=query.get('item');
for(const d of designs.filter(d=>d.kind!=='reference')){const o=n('option','',d.name);o.value=d.id;$('galleryArtwork').append(o);}
const item=()=>items.find(i=>i.id===$('itemSelect').value),selected=()=>layers.find(l=>l.id===activeId);
function rect(x,y,w,h){return {box:[x,y,w,h],path:`M${x} ${y}h${w}v${h}h-${w}Z`};}
function zones(){const i=item(),top=['tee','long'].includes(i.shape),body=shapes[i.shape]||shapes.tee;const base={front:{label:'Front',view:'front',box:top?[245,130,230,560]:[160,110,400,590],path:body,main:true},back:{label:'Back',view:'back',box:top?[245,130,230,560]:[160,110,400,590],path:body,main:true}};
if(top){const torso='M180 160 L275 120 Q360 170 445 120 L540 160 L475 280 L475 690 L245 690 L245 280 Z';base.front.box=base.back.box=[180,120,360,570];base.front.path=torso;base.back.path=torso.replace('Q360 170','Q360 135');base['left-chest']={label:'Left chest',view:'front',...rect(370,235,90,110),main:false};base['right-chest']={label:'Right chest',view:'front',...rect(260,235,90,110),main:false};for(const side of ['left','right'])base[side+'-sleeve']={label:side==='left'?'Left sleeve':'Right sleeve',view:side+'-sleeve',box:[220,160,280,490],path:sleeve,main:true};}
if(/hoodie/i.test(i.name)){for(const side of ['left','right'])base[side+'-hood']={label:side==='left'?'Left hood':'Right hood',view:side+'-hood',box:[175,130,340,540],path:hood,main:true};base.pocket={label:'Front pocket',view:'pocket',box:[180,280,360,240],path:pocket,main:true};}
if(['pants','shorts'].includes(i.shape)){for(const side of ['left','right'])base[side+'-leg']={label:side==='left'?'Left leg':'Right leg',view:side+'-leg',box:[220,140,270,560],path:leg,main:true};base.waistband={label:'Waistband',view:'waistband',box:[160,300,400,130],path:waist,main:true};}
if(i.shape==='skirt')base.waistband={label:'Waistband',view:'waistband',box:[160,300,400,130],path:waist,main:true};
if(i.shape==='bag'){for(const side of ['left','right'])base[side+'-side']={label:side==='left'?'Left side':'Right side',view:side+'-side',...rect(260,170,200,500),main:true};}
return base;}
function silhouette(v){if(v==='front'||v==='back'){let path=shapes[item().shape]||shapes.tee;if(v==='back')path=path.replace(/Q360 1(?:70|65) 445 120/,'Q360 135 445 120');return path;}return Object.values(zones()).find(z=>z.view===v)?.path||shapes.tee;}
function paintLayer(ctx,l,z){const art=assets.get(l.assetId)?.img;if(!art)return;const [x,y,w,h]=z.box,ratio=art.width/art.height;let aw=l.mode==='graphic'?w*.8:w,ah=aw/ratio;if(l.mode!=='graphic'&&ah<h){ah=h;aw=h*ratio;}const factor=l.scale/100;aw*=factor;ah*=factor;
ctx.save();ctx.clip(new Path2D(z.path));ctx.globalAlpha=l.opacity/100;ctx.translate(x+w/2+l.x*w/100,y+h/2+l.y*h/100);ctx.rotate(l.rotation*Math.PI/180);ctx.scale(l.flip?-1:1,1);
if(l.mode==='repeat'){const tw=Math.max(20,w*.5*factor),th=tw/ratio,patternCanvas=document.createElement('canvas');patternCanvas.width=Math.ceil(tw);patternCanvas.height=Math.max(1,Math.ceil(th));patternCanvas.getContext('2d').drawImage(art,0,0,patternCanvas.width,patternCanvas.height);const pattern=ctx.createPattern(patternCanvas,'repeat');ctx.fillStyle=pattern;ctx.fillRect(-1500,-1500,3000,3000);}else ctx.drawImage(art,-aw/2,-ah/2,aw,ah);ctx.restore();}
function draw(canvas,v,showGuides=false){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.scale(canvas.width/720,canvas.height/820);ctx.fillStyle='#20211c';ctx.fillRect(0,0,720,820);const shape=new Path2D(silhouette(v));ctx.fillStyle=$('baseColor').value;ctx.fill(shape);ctx.save();ctx.clip(shape);const zs=zones();
for(const l of layers){const z=zs[l.zone];if(z?.view===v)paintLayer(ctx,l,z);}
// Sleeve and pocket assignments also appear on the front/back overview.
if(['front','back'].includes(v)&&['tee','long'].includes(item().shape)){for(const side of ['left','right']){const targetX=(side==='left')===(v==='front')?500:85;ctx.save();ctx.translate(targetX,200);ctx.scale(.29,item().shape==='long'?.75:.28);ctx.translate(-220,-160);for(const l of layers.filter(l=>l.zone===side+'-sleeve'))paintLayer(ctx,l,zs[l.zone]);ctx.restore();}if(v==='front'&&zs.pocket){ctx.save();ctx.translate(270,480);ctx.scale(.5,.55);ctx.translate(-180,-280);for(const l of layers.filter(l=>l.zone==='pocket'))paintLayer(ctx,l,zs.pocket);ctx.restore();}}
ctx.restore();ctx.strokeStyle='#b4a180';ctx.lineWidth=2;ctx.stroke(shape);
if(showGuides){const z=zs[$('placement').value];if(z&&z.view===v){ctx.save();ctx.strokeStyle='#e9e3d6';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.stroke(new Path2D(z.path));const [x,y,w,h]=z.box;ctx.fillStyle='#e9e3d6';ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillText(z.label.toUpperCase(),x+w/2,y-12);ctx.restore();}const l=selected();if(l&&zs[l.zone]?.view===v){const [x,y,w,h]=zs[l.zone].box,cx=x+w/2+l.x*w/100,cy=y+h/2+l.y*h/100;ctx.strokeStyle='#e9e3d6';ctx.beginPath();ctx.moveTo(cx-10,cy);ctx.lineTo(cx+10,cy);ctx.moveTo(cx,cy-10);ctx.lineTo(cx,cy+10);ctx.stroke();}}
ctx.textAlign='center';ctx.fillStyle='#b4a180';ctx.font='16px sans-serif';ctx.fillText('MIDNIGHT / '+v.replaceAll('-',' ').toUpperCase()+' MAP',360,770);ctx.restore();}
function views(){return [...new Set(Object.values(zones()).map(z=>z.view))];}
function panelUI(){const zs=zones(),previous=$('placement').value;$('placement').replaceChildren();for(const [id,z] of Object.entries(zs)){const o=n('option','',z.label);o.value=id;$('placement').append(o);}if(zs[previous])$('placement').value=previous;view=zs[$('placement').value].view;$('viewTabs').replaceChildren();$('mapOverview').replaceChildren();for(const v of views()){const z=Object.values(zs).find(z=>z.view===v),b=n('button','btn outline',z.label);b.type='button';b.dataset.view=v;b.onclick=()=>{view=v;$('placement').value=Object.entries(zs).find(([id,z])=>z.view===v)[0];activeId=layers.filter(l=>l.zone===$('placement').value).at(-1)?.id||null;controls();render();};$('viewTabs').append(b);const card=n('button','map-tile');card.type='button';card.setAttribute('aria-label','Edit '+z.label);const c=n('canvas');c.width=216;c.height=246;c.dataset.view=v;card.append(c,n('span','',z.label));card.onclick=()=>b.click();$('mapOverview').append(card);}}
function controls(){const l=selected();$('layerControls').querySelectorAll('input,select,button').forEach(e=>e.disabled=!l);for(const [id,key] of [['artScale','scale'],['artX','x'],['artY','y'],['artRotation','rotation'],['artOpacity','opacity'],['coverageMode','mode']])if(l)$(id).value=l[key];$('flipArt').setAttribute('aria-pressed',String(!!l?.flip));$('selectedArtwork').replaceChildren();if(l){const a=assets.get(l.assetId),img=n('img');img.src=a.url;img.alt=a.name;$('selectedArtwork').append(img,n('p','notice',a.name+' · '+a.img.width+' × '+a.img.height+' px'));}else $('selectedArtwork').append(n('p','notice','Add artwork to '+zones()[$('placement').value].label.toLowerCase()+', or select an existing layer.'));outputs();}
function outputs(){for(const [id,value] of [['scaleValue',$('artScale').value+'%'],['xValue',$('artX').value],['yValue',$('artY').value],['rotationValue',$('artRotation').value+'°'],['opacityValue',$('artOpacity').value+'%']])$(id).textContent=value;}
function render(){draw($('conceptCanvas'),view,guides);for(const c of $('mapOverview').querySelectorAll('canvas'))draw(c,c.dataset.view);$('viewTitle').textContent=Object.values(zones()).find(z=>z.view===view)?.label||view;$('previewName').textContent=item().name;$('printfulLink').href='https://www.printful.com/custom/collections/all-over-print?search='+encodeURIComponent(item().name);$('placementHelp').textContent=$('placement').value.includes('chest')?'Chest placement is shown from the wearer’s perspective. Each chest area can use different artwork.':'Artwork stays assigned to this panel while you edit other parts.';for(const b of $('viewTabs').children)b.setAttribute('aria-pressed',String(b.dataset.view===view));$('panelSummary').replaceChildren();for(const [id,z] of Object.entries(zones())){const count=layers.filter(l=>l.zone===id).length;$('panelSummary').append(n('span',count?'panel-done':'panel-empty',z.label+' · '+(count?count+' layer'+(count>1?'s':''):'empty')));}
$('layerList').replaceChildren();for(const l of layers){const z=zones()[l.zone];if(!z)continue;const b=n('button','layer-button',z.label+' / '+assets.get(l.assetId).name);b.setAttribute('aria-pressed',String(l.id===activeId));b.onclick=()=>{activeId=l.id;$('placement').value=l.zone;view=z.view;controls();render();};$('layerList').append(b);}if(!layers.length)$('layerList').append(n('p','notice','Your garment map is empty. Add a design to start.'));}
function defaults(zone,assetId,mode='graphic'){return {id:uid(),zone,assetId,mode,scale:mode==='graphic'?65:100,x:0,y:0,rotation:0,opacity:100,flip:false};}
async function asset(blob,name,source='upload'){const url=URL.createObjectURL(blob),img=new Image();img.src=url;try{await img.decode();const id=uid();assets.set(id,{id,blob,name,source,url,img});return id;}catch{URL.revokeObjectURL(url);throw Error('This image could not be opened. Try a PNG, JPG or WebP.');}}
async function addBlob(blob,name,source,zone=$('placement').value,serial=loadSerial){try{const id=await asset(blob,name,source);if(serial!==loadSerial){URL.revokeObjectURL(assets.get(id).url);assets.delete(id);return;}const l=defaults(zone,id);layers.push(l);activeId=l.id;$('placement').value=zone;view=zones()[zone].view;controls();render();message(name+' added to '+zones()[zone].label+'.');}catch(e){message(e.message);}}
$('addGalleryArt').onclick=async()=>{const d=designs.find(d=>d.id===$('galleryArtwork').value&&d.kind!=='reference');if(!d){message('Choose a design picture first.');return;}const zone=$('placement').value,serial=loadSerial;const existing=layers.find(l=>l.zone===zone&&assets.get(l.assetId)?.source===d.id);if(existing){activeId=existing.id;view=zones()[zone].view;controls();render();return;}if($('addGalleryArt').disabled)return;$('addGalleryArt').disabled=true;message('Loading '+d.name+' onto '+zones()[zone].label+'…');try{const r=await fetch(d.image);if(!r.ok)throw Error();await addBlob(await r.blob(),d.name,d.id,zone,serial);}catch{message('This artwork could not load. Try again.');}finally{$('addGalleryArt').disabled=false;}};
$('galleryArtwork').onchange=()=>{if($('galleryArtwork').value)$('addGalleryArt').onclick();};
async function upload(files){const zone=$('placement').value,serial=loadSerial;for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>20*1024*1024){message('Choose PNG, JPG or WebP files smaller than 20 MB each.');continue;}await addBlob(f,f.name,'upload',zone,serial);}}
$('artUpload').onchange=e=>upload([...e.target.files]);for(const ev of ['dragover','dragenter'])$('dropZone').addEventListener(ev,e=>{e.preventDefault();$('dropZone').classList.add('dragging');});$('dropZone').ondragleave=()=>$('dropZone').classList.remove('dragging');$('dropZone').ondrop=e=>{e.preventDefault();$('dropZone').classList.remove('dragging');upload([...e.dataTransfer.files]);};
$('placement').onchange=()=>{view=zones()[$('placement').value].view;activeId=layers.filter(l=>l.zone===$('placement').value).at(-1)?.id||null;controls();render();};
$('itemSelect').onchange=()=>{loadSerial++;const zs=zones(),before=layers.length;layers=layers.filter(l=>zs[l.zone]);activeId=null;panelUI();controls();render();message(before!==layers.length?'Artwork on panels this item does not have was removed. Your other placements were kept.':'Clothing changed. Check the map and adjust artwork to the new shape.');};$('colorChoice').onchange=()=>{if($('colorChoice').value!=='custom')$('baseColor').value=$('colorChoice').value;render();};$('baseColor').oninput=()=>{$('colorChoice').value='custom';render();};
for(const [id,key] of [['artScale','scale'],['artX','x'],['artY','y'],['artRotation','rotation'],['artOpacity','opacity']])$(id).oninput=()=>{if(!selected())return;selected()[key]=Number($(id).value);outputs();render();};
$('coverageMode').onchange=()=>{const l=selected();if(!l)return;l.mode=$('coverageMode').value;l.scale=l.mode==='graphic'?65:100;l.x=l.y=0;controls();render();};$('flipArt').onclick=()=>{if(!selected())return;selected().flip=!selected().flip;controls();render();};$('resetArt').onclick=()=>{const l=selected();if(!l)return;Object.assign(l,{scale:l.mode==='graphic'?65:100,x:0,y:0,rotation:0,opacity:100,flip:false});controls();render();};$('copyArt').onclick=()=>{const l=selected();if(!l)return;const copy={...l,id:uid(),x:Math.min(100,l.x+10)};layers.push(copy);activeId=copy.id;controls();render();};$('removeArt').onclick=()=>{layers=layers.filter(l=>l.id!==activeId);activeId=layers.filter(l=>l.zone===$('placement').value).at(-1)?.id||null;controls();render();};
$('fullCoverage').onclick=()=>{const l=selected();if(!l)return;const zs=zones();for(const [zone,z] of Object.entries(zs)){if(!z.main)continue;layers=layers.filter(other=>!(other.zone===zone&&other.mode==='cover'&&other.assetId===l.assetId));const copy=defaults(zone,l.assetId,'cover');layers.unshift(copy);if(zone===$('placement').value)activeId=copy.id;}controls();render();message('Coverage added to every main panel. Front, back and each extra panel can be adjusted separately.');};
for(const [id,dir] of [['bringForward',1],['sendBackward',-1]])$(id).onclick=()=>{const l=selected();if(!l)return;const index=layers.indexOf(l);let target=index+dir;while(target>=0&&target<layers.length&&layers[target].zone!==l.zone)target+=dir;if(target>=0&&target<layers.length){[layers[index],layers[target]]=[layers[target],layers[index]];render();}};
$('toggleGuides').onclick=()=>{guides=!guides;$('toggleGuides').setAttribute('aria-pressed',String(guides));render();};
let drag=null;const canvas=$('conceptCanvas');function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*820/r.height};}canvas.onpointerdown=e=>{const l=selected(),z=l&&zones()[l.zone];if(!z||z.view!==view)return;const p=point(e);if(!canvas.getContext('2d').isPointInPath(new Path2D(z.path),p.x,p.y))return;drag={id:l.id,p,x:l.x,y:l.y,box:z.box};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const l=layers.find(l=>l.id===drag.id);if(!l)return;const p=point(e);l.x=Math.round(Math.max(-100,Math.min(100,drag.x+(p.x-drag.p.x)*100/drag.box[2])));l.y=Math.round(Math.max(-100,Math.min(100,drag.y+(p.y-drag.p.y)*100/drag.box[3])));$('artX').value=l.x;$('artY').value=l.y;outputs();render();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('midnightCustomStudio',1);r.onupgradeneeded=()=>r.result.createObjectStore('builds',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}try{db=await openDB();}catch{message('Browser storage is unavailable. Download a brief to keep your design.');}
function database(mode,op){return new Promise((resolve,reject)=>{if(!db)return reject(Error('Could not save in this browser. Download your brief instead.'));const t=db.transaction('builds',mode),r=op(t.objectStore('builds'));let value;r.onsuccess=()=>value=r.result;t.oncomplete=()=>resolve(value);t.onerror=()=>reject(Error('Browser storage could not be updated. Download a brief instead.'));t.onabort=t.onerror;});}
function snapshot(){const qty=Number($('customQty').value);if(!layers.length)throw Error('Add artwork to at least one panel first.');if(!Number.isInteger(qty)||qty<1||qty>99)throw Error('Choose a quantity between 1 and 99.');return {version:3,id:uid(),createdAt:new Date().toISOString(),status:'draft — not submitted or paid',item:item(),layers:layers.map(l=>({...l})),activeId,activeView:view,baseColor:$('baseColor').value,colorChoice:$('colorChoice').value,requestedMaterial:$('materialChoice').value,optionStatus:'Color and material requests — availability to be confirmed',requestedSize:$('requestedSize').value.trim(),sizeGuideCatalogProductId:item().catalogProductId,measurementSource:'Printful product-specific size guide; exact variant to be confirmed',quantity:qty,notes:$('customNotes').value.trim(),orientation:'Left and right refer to the wearer. Artwork coordinates are relative to each illustrated panel.',productionNote:'Visual planning map only. Exact Printful variant, panel templates, seams, bleed, print dimensions and price must be confirmed before production.'};}
const readData=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Artwork could not be exported.'));r.readAsDataURL(blob);});
function exportFile(name,blob){const url=URL.createObjectURL(blob),a=n('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function mapSheet(){const vs=views(),columns=2,rows=Math.ceil(vs.length/columns),sheet=document.createElement('canvas');sheet.width=1000;sheet.height=rows*610+100;const ctx=sheet.getContext('2d');ctx.fillStyle='#141413';ctx.fillRect(0,0,sheet.width,sheet.height);ctx.fillStyle='#e9e3d6';ctx.font='24px sans-serif';ctx.fillText('MIDNIGHT / '+item().name,25,42);ctx.font='14px sans-serif';ctx.fillText('Visual garment map — production templates must be confirmed',25,70);for(let i=0;i<vs.length;i++){const c=document.createElement('canvas');c.width=480;c.height=547;draw(c,vs[i]);ctx.drawImage(c,10+(i%columns)*500,95+Math.floor(i/columns)*610);}return sheet;}
$('downloadMap').onclick=()=>{try{snapshot();mapSheet().toBlob(blob=>{if(blob)exportFile('midnight-garment-map.png',blob);},'image/png');message('Garment map downloaded. This is a design concept, not production print files.');}catch(e){message(e.message);}};
$('downloadBuild').onclick=async()=>{try{const b=snapshot();const used=[...new Set(b.layers.map(l=>l.assetId))];b.artworks=await Promise.all(used.map(async id=>{const a=assets.get(id);return {id,name:a.name,source:a.source,width:a.img.width,height:a.img.height,dataURL:await readData(a.blob)};}));b.panels=Object.entries(zones()).map(([id,z])=>({id,label:z.label,view:z.view,illustratedBounds:z.box,layers:b.layers.filter(l=>l.zone===id).map(l=>l.id)}));b.panelPreviews=views().map(v=>{const c=document.createElement('canvas');c.width=720;c.height=820;draw(c,v);return {view:v,image:c.toDataURL('image/png')};});exportFile('midnight-full-design-'+b.id+'.json',new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));message('Full design brief downloaded with every artwork, layer, placement and panel preview. No order has been submitted.');}catch(e){message(e.message);}};
$('saveBuild').onclick=async()=>{try{const b=snapshot();b.artworks=[...new Set(b.layers.map(l=>l.assetId))].map(id=>{const a=assets.get(id);return {id,name:a.name,source:a.source,blob:a.blob};});b.preview=mapSheet().toDataURL('image/png');await database('readwrite',s=>s.put(b));await saved();message('Your entire garment map was saved on this device. No order or payment was submitted.');}catch(e){message(e.message);}};
async function restore(b){loadSerial++;const serial=loadSerial;try{const incoming=b.version===3?b.artworks:[{id:'legacy',blob:b.artBlob,name:b.artName,source:b.artSource}],loaded=new Map();for(const a of incoming){const id=await asset(a.blob,a.name,a.source);loaded.set(a.id,id);}if(serial!==loadSerial)return;$('itemSelect').value=b.item.id;$('baseColor').value=b.baseColor;$('colorChoice').value=b.colorChoice||([...$('colorChoice').options].some(o=>o.value===b.baseColor)?b.baseColor:'custom');$('materialChoice').value=b.requestedMaterial||'';$('requestedSize').value=b.requestedSize||'';$('customQty').value=b.quantity;$('customNotes').value=b.notes||'';const zs=zones();layers=b.version===3?b.layers.filter(l=>zs[l.zone]).map(l=>({...l,assetId:loaded.get(l.assetId)})):[{...defaults(zs[b.placement]?b.placement:'front',loaded.get('legacy'),b.placement==='all-over'?'cover':'graphic'),scale:b.scale||65}];activeId=b.version===3&&layers.some(l=>l.id===b.activeId)?b.activeId:layers[0]?.id||null;panelUI();if(selected()){$('placement').value=selected().zone;view=zs[selected().zone].view;}controls();render();document.dispatchEvent(new Event('garment-restored'));message('Saved garment map opened.');canvas.scrollIntoView({behavior:'smooth'});}catch{message('This saved build could not be opened.');}}
async function saved(){$('savedBuilds').replaceChildren();if(!db){$('savedBuilds').append(n('p','notice','Browser storage unavailable.'));return;}let builds;try{builds=await database('readonly',s=>s.getAll());}catch(e){message(e.message);return;}if(!builds.length)$('savedBuilds').append(n('p','notice','Your first garment map starts above.'));for(const b of builds.reverse()){const card=n('article','product-card'),img=n('img');img.src=b.preview;img.alt=b.item.name+' saved map';const title=n('h3','',b.item.name),copy=n('p','notice',(b.version===3?b.layers.length+' artwork layers':b.artName)+' / Qty '+b.quantity),open=n('button','btn outline','Open build'),remove=n('button','btn outline','Delete');open.onclick=()=>restore(b);remove.onclick=async()=>{try{await database('readwrite',s=>s.delete(b.id));await saved();}catch(e){message(e.message);}};card.append(img,title,copy,open,remove);$('savedBuilds').append(card);}}
panelUI();controls();render();await saved();const chosen=designs.find(d=>d.id===query.get('design')&&d.kind!=='reference');if(chosen){$('galleryArtwork').value=chosen.id;await $('addGalleryArt').onclick();}if(query.has('upload'))$('dropZone').scrollIntoView();
})();
