import {calculatePrice} from './pricing-math.mjs';
const $=id=>document.getElementById(id), all=[];let draft={};
try{draft=JSON.parse(localStorage.getItem('midnight-pricing-draft')||'{}')}catch{}
const save=()=>{try{localStorage.setItem('midnight-pricing-draft',JSON.stringify(draft))}catch{} $('changes').value='';$('copy').disabled=true;};
const money=(n,c)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n);
function estimate(row){const d=draft[row.v.id]||{},price=Number(d.price??row.v.price),cost=d.cost===''||d.cost==null?NaN:Number(d.cost),other=Number(d.other||0),fee=Number($('fee').value),fixed=Number($('fixedFee').value),profit=price*(1-fee/100)-cost-other-fixed;return {price,profit,margin:profit/price*100};}
function render(){const q=$('search').value.toLowerCase(),cat=$('category').value;const shown=all.filter(r=>(!cat||r.p.category===cat)&&(r.p.name+' '+r.v.name+' '+r.p.id).toLowerCase().includes(q));$('rows').replaceChildren();$('count').textContent=shown.length+' variants';for(const r of shown){const tr=document.createElement('tr'),d=draft[r.v.id]||{},e=estimate(r);const title=document.createElement('td'),img=document.createElement('img');img.src=r.p.image;img.alt='';title.append(img,document.createTextNode(r.v.name));tr.append(title);const current=document.createElement('td');current.textContent=money(r.v.price,r.v.currency);tr.append(current);for(const key of ['cost','other','price']){const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.min=key==='price'?'0.01':'0';input.step='0.01';input.value=d[key]??(key==='price'?r.v.price:key==='other'?0:'');input.setAttribute('aria-label',key+' for '+r.v.name+' '+r.v.id);input.onchange=()=>{draft[r.v.id]={...(draft[r.v.id]||{}),[key]:input.value};save();render()};td.append(input);tr.append(td);}for(const val of [Number.isFinite(e.profit)?money(e.profit,r.v.currency):'Enter cost',Number.isFinite(e.margin)?e.margin.toFixed(1)+'%':'—']){const td=document.createElement('td');td.textContent=val;tr.append(td)}$('rows').append(tr)}}
$('calculate').onclick=()=>{try{const target=Number($('target').value),fee=Number($('fee').value),fixed=Number($('fixedFee').value),cat=$('category').value,updates=[];for(const r of all.filter(x=>!cat||x.p.category===cat)){const d=draft[r.v.id]||{};if(d.cost==null||d.cost==='')continue;const price=calculatePrice(Number(d.cost),Number(d.other||0),fee,fixed,target,$('method').value);if(price<=0)throw Error('Calculated selling prices must be greater than zero.');updates.push([r.v.id,price]);}for(const [id,price]of updates)draft[id]={...draft[id],price};save();render();$('status').textContent=updates.length+' draft prices calculated. Variants without costs were skipped.';}catch(e){$('status').textContent=e.message}};
for(const id of ['search','category','fee','fixedFee'])$(id).oninput=render;
$('prepare').onclick=()=>{try{const prices={};for(const r of all){const raw=draft[r.v.id]?.price;if(raw==null)continue;const n=Number(raw);if(!Number.isFinite(n)||n<=0||n>10000||Math.abs(n*100-Math.round(n*100))>1e-6)throw Error('Selling prices must be positive amounts with at most two decimal places.');if(n!==r.v.price)prices[r.v.id]=n;}if(!Object.keys(prices).length)throw Error('No selling price changes to publish.');$('changes').value=JSON.stringify({version:1,prices});$('copy').disabled=false;$('publishStatus').textContent=Object.keys(prices).length+' variant price changes ready. Not published yet.';}catch(e){$('publishStatus').textContent=e.message}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('changes').value);$('publishStatus').textContent='Copied. Paste into the protected pricing workflow to publish.'}catch{$('changes').select();$('publishStatus').textContent='Select and copy the price changes below.'}};
try{const response=await fetch('products.json',{cache:'no-cache'});if(!response.ok)throw Error('Catalog unavailable');const data=await response.json();for(const p of data.products)for(const v of p.variants)all.push({p,v});for(const c of [...new Set(data.products.map(p=>p.category))]){const option=document.createElement('option');option.value=c;option.textContent=c;$('category').append(option)}render()}catch(e){$('status').textContent='Could not load product prices. Reload to try again.'}
