'use strict';
(async()=>{
const $=id=>document.getElementById(id),form=$('productReviewForm');if(!form)return;const productId=document.body.dataset.productId||new URLSearchParams(location.search).get('id');
let catalog;try{catalog=await fetch('products.json').then(r=>r.json());}catch{return;}if(!catalog.products.some(p=>p.id===productId))return;$('productReviews').hidden=false;
const scores={quality:'Product quality',print:'Print quality',fit:'Fit',comfort:'Comfort',value:'Value',shipping:'Shipping experience',overall:'Overall rating'};
const newId=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map((n,i)=>([4,6,8,10].includes(i)?'-':'')+n.toString(16).padStart(2,'0')).join('');
let voter,db=null,draft=null,photos=[],busy=false,version=0,durable=false;let queue=Promise.resolve();try{voter=localStorage.getItem('midnightProductReviewerId');if(!/^[a-f0-9-]{36}$/.test(voter||'')){voter=newId();localStorage.setItem('midnightProductReviewerId',voter);}}catch{voter=newId();}
try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('midnight-product-reviews',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});draft=await new Promise((resolve,reject)=>{const req=db.transaction('drafts').objectStore('drafts').get(productId);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}catch{db=null;}
durable=!!draft;
async function persist(){if(!db){durable=false;return false;}durable=await new Promise(resolve=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(draft,productId);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false);});return durable;}
if(draft?.voterId&&/^[a-f0-9-]{36}$/.test(draft.voterId))voter=draft.voterId;
const service=fetch('request-service-config.json',{cache:'no-store'}).then(r=>r.json()).then(c=>{if(!c.url)return null;const u=new URL(c.url);return u.protocol==='https:'&&!u.username&&!u.password&&u.pathname==='/'&&!u.search&&!u.hash?u.origin:null;}).catch(()=>null);
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};function notice(text,retry=false){$('productReviewStatus').textContent=text;$('retryProductReview').hidden=!retry;}
function preview(){const box=$('productReviewPhotoPreview');box.replaceChildren();photos.forEach((p,i)=>{const wrap=document.createElement('div'),img=document.createElement('img');img.src='data:image/jpeg;base64,'+p.data;img.alt='Your review photo '+(i+1);const remove=node('button','Remove photo '+(i+1));remove.type='button';remove.className='btn outline';remove.onclick=()=>{photos.splice(i,1);preview();};wrap.append(img,remove);box.append(wrap);});}
async function loadPublished(){const url=await service;if(!url){$('productReviewSummary').textContent='Shared product reviews are not connected yet. You can save a review on this device.';return;}try{const r=await fetch(url+'/api/product-reviews?productId='+encodeURIComponent(productId),{credentials:'omit'});if(!r.ok)throw Error();const data=await r.json();$('productReviewSummary').replaceChildren(node('p',data.count+' published reviews'));if(data.count)for(const [key,label]of Object.entries(scores))$('productReviewSummary').append(node('p',label+': '+data.averages[key].toFixed(2)+' / 5'));$('publishedProductReviews').replaceChildren();for(const review of data.reviews){const article=document.createElement('article');article.className='review-entry';article.append(node('h3',review.displayName),node('p',new Date(review.created).toLocaleDateString()+' · '+[review.size,review.color].filter(Boolean).join(' · ')),node('p',Object.entries(scores).map(([k,l])=>l+': '+review[k]+'/5').join(' · ')),node('p',review.text));const images=document.createElement('div');images.className='review-photos';for(const p of review.photos){const img=document.createElement('img');img.src=new URL(p.url,url).href;img.alt='Customer photo of this product shared by '+review.displayName;img.loading='lazy';images.append(img);}article.append(images);$('publishedProductReviews').append(article);}}catch{$('productReviewSummary').textContent='Product reviews could not load. Refresh to try again.';}}
function send(review,generation=version){queue=queue.catch(()=>{}).then(async()=>{const url=await service;if(!url){notice(durable?(review?'Saved on this device only. Review submission is not connected yet.':'Review removed from this device. Shared reviews are not connected yet.'):'Storage is unavailable. Keep this page open; this review has not been submitted.');return;}try{const r=await fetch(url+'/api/product-reviews',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId,voterId:voter,review})});if(!r.ok)throw Error();if(generation!==version)return;draft.pending=false;await persist();notice(review?'Review submitted for publication review. It is not published yet.':'Your review was removed.');await loadPublished();}catch{if(generation===version)notice('Could not submit. '+(durable?'Your review is saved on this device.':'Keep this page open.'),true);}});}
if(draft?.review){for(const [key,value]of Object.entries(draft.review))if(form.elements.namedItem(key)&&key!=='consent')form.elements.namedItem(key).value=value;photos=draft.review.photos||[];preview();$('removeProductReview').hidden=false;notice('Your saved review. Editing a published review sends it for publication review again.',!!draft.pending);}
$('productReviewPhotos').onchange=async e=>{const files=[...e.target.files];if(files.length+photos.length>3){notice('Choose no more than three photos.');e.target.value='';return;}busy=true;form.querySelector('[type=submit]').disabled=true;try{const next=[];for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('Use PNG, JPG or WebP photos up to 8 MB each.');const img=await createImageBitmap(file);try{const scale=Math.min(1,900/img.width,900/img.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',0.75).split(',')[1];if(data.length>450000)throw Error('Photo is too complex. Please use a smaller image.');next.push({data});}finally{img.close();}}photos.push(...next);preview();notice('Photos added. Save your review to keep them.');}catch(e){notice(e.message);}finally{busy=false;form.querySelector('[type=submit]').disabled=false;e.target.value='';}};
form.onsubmit=async e=>{e.preventDefault();if(busy||!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));for(const key of Object.keys(scores))data[key]=Number(data[key]);data.consent=true;data.photos=structuredClone(photos);delete data.undefined;draft={review:data,pending:true,voterId:voter};const generation=++version;const saved=await persist();$('removeProductReview').hidden=false;notice(saved?'Saved. Checking submission connection…':'Could not save on this device. Checking submission connection…');send(data,generation);};
$('removeProductReview').onclick=async()=>{if(busy)return;const generation=++version;draft={review:null,pending:true,voterId:voter};await persist();photos=[];preview();form.reset();$('removeProductReview').hidden=true;send(null,generation);};$('retryProductReview').onclick=()=>{if(draft)send(draft.review);};await loadPublished();
})();
