'use strict';
(async()=>{
 const $=id=>document.getElementById(id);if(!$('visual')||!$('variant'))return;
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
 const productId=new URLSearchParams(location.search).get('id');let p,entry;try{const values=await Promise.all(['products.json','product-photos.json'].map(async path=>{const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw Error();return r.json()}));p=values[0].products.find(p=>p.id===productId);entry=values[1].products[productId];if(!p||!entry?.photos?.length||(entry.originalImage&&entry.originalImage!==p.image))return}catch{return}
 entry.photos.sort((a,b)=>(a.category==='product'&&a.style==='Flat'&&/^front$/i.test(a.view)?0:1)-(b.category==='product'&&b.style==='Flat'&&/^front$/i.test(b.view)?0:1));
 for(let i=0;i<200&&$('variant').disabled;i++)await new Promise(r=>setTimeout(r,25));if($('variant').disabled)return;
 const filters=node('div',undefined,'photo-filters');filters.setAttribute('role','group');filters.setAttribute('aria-label','Product photo views');const caption=node('p',undefined,'photo-caption');caption.id='photoCaption';caption.setAttribute('aria-live','polite');const zoom=node('button','Enlarge photo ↗','photo-enlarge');zoom.type='button';$('gallery').before(filters);$('gallery').after(caption,zoom);$('gallery').setAttribute('aria-label','Choose a product photo');let active=null,currentFilter='all',color=null;
 const dialog=node('dialog',undefined,'photo-dialog');dialog.id='productPhotoDialog';const close=node('button','Close photo','btn outline');close.type='button';close.onclick=()=>dialog.close();const image=node('img');const heading=node('p');dialog.append(close,heading,image);document.body.append(dialog);zoom.onclick=()=>{if(!active)return;image.src=active.image;image.alt=active.alt;heading.textContent=active.label;dialog.showModal()};
 for(const photo of entry.photos){photo.view=photo.view.replace(/_(dtfabric|dtg|embroidery)$/i,'').replace(/_/g,' ').replace(/\b[a-z]/g,c=>c.toUpperCase());photo.label=photo.category==='fit'?'On-person · '+photo.view:photo.view;photo.alt=p.name+' · '+photo.label;}
 const type=photo=>photo.category==='fit'?'fit':/back/i.test(photo.view)?'back':/front/i.test(photo.view)?'front':'other';
 function show(photo){active=photo;const image=node('img');image.src=photo.image;image.alt=photo.alt;image.loading='eager';$('visual').replaceChildren(image);$('visual').classList.toggle('is-artwork-detail',Boolean(photo.detail));caption.textContent=photo.detail?'Artwork detail — enlarged view of the actual product mockup.':photo.category==='fit'?photo.label+' — production mockup showing how the item is worn. See the size chart for your measurements.':photo.label+' — product mockup.';for(const b of $('gallery').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.photo===photo.key))}
 function render(){const v=p.variants.find(v=>String(v.id)===$('variant').value);const eligible=entry.photos.filter(photo=>!photo.storeVariantIds?.length||photo.storeVariantIds.includes(v?.id));if(!eligible.length){filters.replaceChildren();zoom.disabled=true;$('gallery').dataset.ready='true';$('visual').replaceChildren(node('p','Photos for this color are not available yet.'));$('gallery').replaceChildren();caption.textContent='Choose another color to see its product photos.';active=null;color=v?.color;return;}zoom.disabled=false;const base=eligible.find(photo=>type(photo)==='front')||eligible[0];const all=eligible.map((photo,i)=>({...photo,key:String(i)}));all.push({...base,key:'detail',label:'Artwork detail',alt:p.name+' artwork detail from the product mockup',detail:true});filters.replaceChildren();for(const [id,label] of [['all','All views'],['front','Front'],['back','Back'],['fit','On-person']]){if(id!=='all'&&!eligible.some(photo=>type(photo)===id))continue;const button=node('button',label);button.type='button';button.setAttribute('aria-pressed',String(currentFilter===id));button.onclick=()=>{currentFilter=id;render()};filters.append(button)}const visible=all.filter(photo=>currentFilter==='all'||(!photo.detail&&type(photo)===currentFilter));$('gallery').replaceChildren();for(const photo of visible){const button=node('button',undefined,'photo-thumbnail');button.type='button';button.dataset.photo=photo.key;button.setAttribute('aria-label','View '+photo.label);const image=node('img');image.src=photo.image;image.alt='';image.loading='lazy';button.append(image,node('span',photo.label));button.onclick=()=>show(photo);$('gallery').append(button)}show(visible.find(photo=>photo.key===active?.key)||visible[0]);$('gallery').dataset.ready='true';color=v?.color;}
 $('variant').addEventListener('change',()=>{const v=p.variants.find(v=>String(v.id)===$('variant').value);if(v?.color!==color){currentFilter='all';active=null;render()}});render();
})();
