'use strict';
(()=>{
const $=id=>document.getElementById(id),types=["Custom design request","Customer-uploaded design","Create Your Own submission","Custom clothing request","Question / comment","Revision request","Design idea","Product request","Clothing request","Site problem","Feature suggestion","Complaint","General comment"],statuses=["New","Reviewing","Designing","Customer Review","Revision Requested","Approved","Ready for Production","Completed"],key='midnight-owner-requests-v1';let records=[],editing=null,page=0,storageAvailable=true;
const text=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;},stamp=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
function normalize(r){if(!r||typeof r!=='object'||!types.includes(r.type)||!statuses.includes(r.status))throw Error('Invalid request type or status.');const out={};for(const k of ['id','title','name','email','product','budget','deadline','related','details','files','notes','createdAt','updatedAt']){if(r[k]!=null&&typeof r[k]!=='string')throw Error('Invalid request field.');out[k]=r[k]||'';if(out[k].length>12000)throw Error('Request field too long.');}if(!out.id||out.id.length>100||!out.title.trim()||!out.details.trim())throw Error('Request needs an ID, title and brief.');if(r.priority!=null&&!['Normal','High'].includes(r.priority))throw Error("Invalid priority.");out.priority=r.priority||"Normal";out.type=r.type;out.status=r.status;out.history=Array.isArray(r.history)?r.history.slice(-100).map(h=>{if(!statuses.includes(h.status)||typeof h.at!=='string')throw Error('Invalid history.');return {status:h.status,at:h.at};}):[{status:r.status,at:out.createdAt||stamp()}];return out;}
try{const data=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(data)||data.length>500)throw Error();records=data.map(normalize);}catch{storageAvailable=false;$('queueStatus').textContent='Saved records could not be read. Your saved data has not been overwritten. Export or repair your browser storage before saving.';}
function persist(next){if(!storageAvailable)throw Error('Browser storage is unavailable. Existing data has not been overwritten.');if(next.length>500)throw Error('This local queue supports up to 500 records. Export and archive completed work first.');localStorage.setItem(key,JSON.stringify(next));records=next;render();}
function render(){const q=$('queueSearch').value.toLowerCase(),type=$('typeFilter').value,status=$('statusFilter').value;const list=records.filter(r=>MidnightRequestFilters.matches(r,{q,type,status,bucket:$('queueView').value,customer:$('queueCustomer').value,product:$('queueProduct').value,from:$('queueFrom').value,to:$('queueTo').value})).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));page=Math.min(page,Math.max(0,Math.ceil(list.length/15)-1));$('queueCount').textContent=list.length+' requests · showing '+(list.length?page*15+1:0)+'–'+Math.min(list.length,(page+1)*15);$('requestRows').replaceChildren();for(const r of list.slice(page*15,page*15+15)){const row=text('article','');row.className='request-record';const body=text('div','');body.append(text('h2',r.title),text('p',r.type+' · '+r.status+' · '+r.priority+' priority'),text('p',(r.name||'Name not provided')+' · '+(r.email||'Email not provided')),text('p',r.product||'Product not specified'),text('small','ID: '+r.id+' · Updated: '+new Date(r.updatedAt).toLocaleString()));const b=text('button','Open request');b.className='btn outline';b.onclick=()=>open(r);row.append(body,b);$('requestRows').append(row);}if(!list.length)$('requestRows').append(text('p',records.length?'No matching requests.':'No requests yet. Import a customer file or add an emailed request.'));$('queuePrevious').disabled=page===0;$('queueNext').disabled=(page+1)*15>=list.length;$('queueStats').replaceChildren();for(const [label,count] of [['Total',records.length],['New',records.filter(r=>r.status==='New').length],['In progress',records.filter(r=>!['New','Completed'].includes(r.status)).length],['Completed',records.filter(r=>r.status==='Completed').length]]){const a=text('article',label);a.append(text('strong',count));$('queueStats').append(a);}}
const fields={requestTitle:'title',customerName:'name',customerEmail:'email',requestProduct:'product',requestBudget:'budget',requestDeadline:'deadline',relatedRequest:'related',requestDetails:'details',requestFiles:'files',ownerNotes:'notes'};
function open(r){editing=r||null;$('requestForm').reset();for(const [id,k] of Object.entries(fields))$(id).value=r?.[k]||'';$('requestType').value=r?.type||types[0];$('requestPriority').value=r?.priority||'Normal';$('requestState').value=r?.status||'New';$('removeRequest').hidden=!r;$('editorStatus').textContent='';$('statusHistory').replaceChildren();for(const h of r?.history||[])$('statusHistory').append(text('li',h.status+' — '+new Date(h.at).toLocaleString()));$('requestEditor').showModal();}
$('newRequest').onclick=()=>open();$('closeRequest').onclick=()=>$('requestEditor').close();
$('requestForm').onsubmit=e=>{e.preventDefault();try{const now=stamp(),r={...(editing||{}),id:editing?.id||uid(),createdAt:editing?.createdAt||now,updatedAt:now,priority:$('requestPriority').value,type:$('requestType').value,status:$('requestState').value,history:[...(editing?.history||[])]};for(const [id,k]of Object.entries(fields))r[k]=$(id).value.trim();if(!r.history.length||r.status!==editing?.status)r.history.push({status:r.status,at:now});const valid=normalize(r);persist([...records.filter(x=>x.id!==valid.id),valid]);$('requestEditor').close();$('queueStatus').textContent='Request saved on this device. No customer notification or production action was sent.';}catch(e){$('editorStatus').textContent=e.message;}};
$('removeRequest').onclick=()=>$('deleteConfirm').showModal();$('cancelDelete').onclick=()=>$('deleteConfirm').close();$('confirmDelete').onclick=()=>{try{persist(records.filter(r=>r.id!==editing.id));$('deleteConfirm').close();$('requestEditor').close();$('queueStatus').textContent='Local record deleted.';}catch(e){$('deleteConfirm').close();$('editorStatus').textContent=e.message;}};
for(const id of ['queueSearch','typeFilter','statusFilter','queueView','queueCustomer','queueProduct','queueFrom','queueTo'])$(id).oninput=()=>{page=0;render();};$('queueReset').onclick=()=>{for(const id of ['queueSearch','typeFilter','statusFilter','queueView','queueCustomer','queueProduct','queueFrom','queueTo'])$(id).value='';page=0;render();};$('queuePrevious').onclick=()=>{page--;render();};$('queueNext').onclick=()=>{page++;render();};
$('exportQueue').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,kind:'midnight-request-backup',requests:records},null,2)],{type:'application/json'}));const a=text('a','');a.href=url;a.download='midnight-owner-requests-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('queueStatus').textContent='Backup downloaded. It contains customer details; keep it private.';};
$('importQueue').onchange=async()=>{try{const file=$('importQueue').files[0];if(!file)return;if(file.size>40*1024*1024)throw Error('File exceeds 40 MB. Keep original artwork separately.');const data=JSON.parse(await file.text());let incoming;
 if(data.kind==='midnight-request-backup'&&data.version===1&&Array.isArray(data.requests))incoming=data.requests.map(normalize);
 else if(data.kind==='midnight-design-request'&&data.version===1)incoming=[normalize({...data.request,status:'New',history:[{status:'New',at:stamp()}]})];
 else if(data.version===3&&data.item&&Array.isArray(data.layers)){const now=stamp();incoming=[normalize({id:'studio-'+String(data.id),type:'Create Your Own submission',status:'New',title:String(data.item.name||'Custom garment'),name:'',email:'',product:String(data.item.name||''),budget:'',deadline:'',related:'',notes:'Imported garment map summary (up to 12,000 characters). Keep the original full design file for all artwork and production details. Confirm customer contact, quote and final production files.',files:(data.artworks||[]).map(a=>String(a.name||a.id)).join('\n'),details:JSON.stringify({requestedSize:data.requestedSize,quantity:data.quantity,baseColor:data.baseColor,material:data.requestedMaterial,notes:data.notes,layers:data.layers,panels:data.panels},null,2).slice(0,12000),createdAt:now,updatedAt:now})];}
 else throw Error('Choose a Midnight Designs request file, full Create yours design file or queue backup.');
 if(incoming.length>500)throw Error('Too many records in import.');const ids=new Set(records.map(r=>r.id)),unique=incoming.filter(r=>{if(ids.has(r.id))return false;ids.add(r.id);return true;});persist([...records,...unique]);$('queueStatus').textContent=unique.length+' requests imported; '+(incoming.length-unique.length)+' existing IDs skipped. Customer files remain separate. Confirm contact information before working.';}catch(e){$('queueStatus').textContent='Import failed: '+e.message;}finally{$('importQueue').value='';}};
render();
})();
