'use strict';
(async()=>{
 const $=id=>document.getElementById(id),node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 if(!$('itemSelect')&&!$('variant'))return;
 let guides,items,products;try{[guides,items,products]=await Promise.all(['size-guides.json','clothing.json','products.json'].map(async p=>{const r=await fetch(p,{cache:'no-cache'});if(!r.ok)throw Error();return r.json();}));}catch{return;}
 const box=node('section');box.className='panel size-guide';box.id='sizeGuide';const title=node('h2','Sizes & measurements'),intro=node('p');intro.className='notice';const units=node('select');units.id='measurementUnits';units.setAttribute('aria-label','Measurement units');for(const [v,t]of [['inches','Inches'],['cm','Centimeters']]){const o=node('option',t);o.value=v;units.append(o);}const content=node('div');box.append(title,intro,units,content);const anchor=$('requestedSize')?.closest('.panel')||$('description')?.parentElement;if($('requestedSize'))anchor?.before(box);else ($('productDetails')||$('description'))?.after(box);
 const plain=html=>{const d=new DOMParser().parseFromString(html||'','text/html');return d.body.textContent||'';};
 const value=v=>{const raw=v.value??(v.min_value!==undefined&&v.max_value!==undefined?v.min_value+'–'+v.max_value:'—');if(units.value==='inches')return raw;return String(raw).replace(/\d+(?:\.\d+)?/g,n=>String(Math.round(Number(n)*2.54*10)/10));};
 function render(){content.replaceChildren();const i=$('itemSelect')?items.find(x=>x.id===$('itemSelect').value):products.products.find(x=>x.id===new URLSearchParams(location.search).get('id'));const guide=guides.guides[String(i?.catalogProductId)];intro.textContent=i?.catalogTitle||i?.name||'Choose your garment';if(!guide){content.append(node('p','Measurements are not available for this exact product yet. Confirm sizing before ordering.'));return;}const sizes=$('itemSelect')?(guide.available_sizes||[]):[...new Set((i?.variants||[]).map(v=>v.size).filter(Boolean))];const p=node('p',($('itemSelect')?'Catalog sizes: ':'Available store sizes: ')+(sizes.join(', ')||'Not provided'));p.className='notice';content.append(p);if($('requestedSize')){let dl=$('garmentSizes');if(!dl){dl=node('datalist');dl.id='garmentSizes';$('requestedSize').after(dl);$('requestedSize').setAttribute('list',dl.id);}dl.replaceChildren(...sizes.map(s=>{const o=node('option');o.value=s;return o;}));$('requestedSize').placeholder='Choose a catalog size above';}
 if(!guide.size_tables?.length){content.append(node('p','A measurement chart is not available for this item yet.'));return;}
 for(const chart of guide.size_tables){const section=node('details');const summary=node('summary',({measure_yourself:'Body measurements',product_measure:'Garment dimensions',international:'International size equivalents'})[chart.type]||chart.type);section.append(summary);section.open=chart.type==='product_measure'||guide.size_tables.length===1;const note=node('p',plain(chart.description));note.className='notice';section.append(note);const wrap=node('div');wrap.style.overflowX='auto';const table=node('table');table.style.cssText='width:100%;border-collapse:collapse;font-size:12px';const tr=node('tr');for(const t of ['Size',...chart.measurements.map(m=>m.type_label+(chart.unit==='inches'?' ('+units.value+')':''))]){const th=node('th',t);th.style.cssText='padding:10px;text-align:left;border-bottom:1px solid #555';tr.append(th);}const thead=node('thead');thead.append(tr);table.append(thead);const body=node('tbody');for(const size of sizes){const row=node('tr');const vals=[size,...chart.measurements.map(m=>{const v=m.values.find(v=>v.size===size);return v?(chart.unit==='inches'?value(v):v.value||'—'):'—';})];for(const t of vals){const td=node('td',t);td.style.cssText='padding:10px;border-bottom:1px solid #383831;white-space:nowrap';row.append(td);}body.append(row);}table.append(body);wrap.append(table);section.append(wrap);if(chart.image_url){const img=node('img');img.src=chart.image_url;img.alt='How to measure this garment';img.loading='lazy';img.style.cssText='max-width:100%;max-height:240px;object-fit:contain';section.append(img);}section.append(node('p',plain(chart.image_description)));content.append(section);}
 const note=node('p','Body measurements and flat garment dimensions are different. These charts are not artwork print-area dimensions. Catalog sizes may include options not offered in this store; select an available store variant when purchasing.');note.className='notice';content.append(note);
 }
 document.addEventListener('garment-restored',render);units.onchange=render;$('itemSelect')?.addEventListener('change',render);render();if($('itemSelect')&&!$('itemSelect').value){const observer=new MutationObserver(()=>{if($('itemSelect').value){render();observer.disconnect();}});observer.observe($('itemSelect'),{childList:true});}
})();

