'use strict';
(async()=>{
if(!document.querySelector('.studio'))return;
const el=id=>document.getElementById(id), node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
const shapes={tee:'M180 160 L275 120 Q360 170 445 120 L540 160 L640 320 L530 370 L475 280 L475 690 L245 690 L245 280 L190 370 L80 320 Z',long:'M180 160 L275 120 Q360 165 445 120 L540 160 L680 590 L565 620 L475 300 L475 690 L245 690 L245 300 L155 620 L40 590 Z',pants:'M225 120 L495 120 L520 700 L385 700 L360 345 L335 700 L200 700 Z',shorts:'M225 190 L495 190 L530 600 L390 600 L360 390 L330 600 L190 600 Z',dress:'M280 100 L310 100 Q360 145 410 100 L440 100 L435 295 L555 700 L165 700 L285 295 Z',skirt:'M270 160 L450 160 L575 680 L145 680 Z',bra:'M230 180 L275 180 L285 280 Q360 320 435 280 L445 180 L490 180 L525 450 L195 450 Z',swimsuit:'M245 110 L290 110 Q360 190 430 110 L475 110 L460 300 L495 475 L410 500 L380 665 L340 665 L310 500 L225 475 L260 300 Z',bag:'M250 210 Q250 115 360 115 Q470 115 470 210 L500 270 L500 670 L220 670 L220 270 Z',bandana:'M120 160 L600 160 L360 690 Z'};
function draw(c,item,art,color='#24241f',scale=65,placement='front'){
const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.scale(c.width/720,c.height/820);ctx.fillStyle='#20211c';ctx.fillRect(0,0,720,820);const path=new Path2D(shapes[item.shape]||shapes.tee);ctx.fillStyle=color;ctx.fill(path);if(art){ctx.save();ctx.clip(path);if(placement==='all-over')ctx.drawImage(art,120,100,480,600);else{let w=320*scale/65,h=w*art.height/art.width,x=360-w/2,y=260;if(placement.includes('sleeve')){w=90;h=w*art.height/art.width;x=placement==='left-sleeve'?120:510;y=240;}ctx.drawImage(art,x,y,w,h);}ctx.restore();}ctx.strokeStyle='#b4a180';ctx.lineWidth=2;ctx.stroke(path);ctx.fillStyle='#b4a180';ctx.textAlign='center';ctx.font='16px sans-serif';ctx.fillText('MIDNIGHT / '+placement.toUpperCase()+' CONCEPT',360,770);ctx.restore();}
function picture(src,alt){const img=node('img');img.src=src;img.alt=alt;img.loading='lazy';return img;}
function link(label,href,cls='btn outline'){const a=node('a',cls,label);a.href=href;return a;}
function say(t){if(el('studioStatus'))el('studioStatus').textContent=t;}
let items,designs;try{const responses=await Promise.all([fetch('clothing.json'),fetch('designs.json')]);if(responses.some(r=>!r.ok))throw Error();[items,designs]=await Promise.all(responses.map(r=>r.json()));}catch{document.querySelector('.studio').append(node('p','error','The custom catalog could not load. Please refresh.'));return;}
if(el('clothingGrid')){
for(const category of new Set(items.map(i=>i.category))){const o=node('option','',category);o.value=category;el('clothingCategory').append(o);}
function render(){const query=el('clothingSearch').value.trim().toLowerCase(),category=el('clothingCategory').value,list=items.filter(i=>(!category||i.category===category)&&i.name.toLowerCase().includes(query));el('clothingGrid').replaceChildren();el('clothingStatus').textContent=list.length+' clothing / item options';for(const item of list){const card=node('article','product-card'),a=link('','custom.html?item='+item.id,'product-image');const c=node('canvas');c.width=360;c.height=410;c.setAttribute('aria-label',item.name+' illustration');draw(c,item);a.append(c);card.append(a,node('div','eyebrow',item.category),node('h3','',item.name),node('p','notice','All-over print · availability to be confirmed'),link('Choose this piece ↗',a.href));el('clothingGrid').append(card);}if(!list.length)el('clothingGrid').append(node('p','notice','No matching pieces. Try another search.'));}el('clothingSearch').oninput=render;el('clothingCategory').onchange=render;render();}
if(el('designGrid')){
let active=null,preferences={};try{preferences=JSON.parse(localStorage.getItem('midnightDesignVotes')||'{}')||{};}catch{}
function buttons(){el('likeDesign').setAttribute('aria-pressed',String(preferences[active.id]==='like'));el('dislikeDesign').setAttribute('aria-pressed',String(preferences[active.id]==='dislike'));}
for(const category of new Set(designs.map(d=>d.category))){const o=node('option','',category);o.value=category;el('designCategory').append(o);}
function gallery(){const q=el('designSearch').value.toLowerCase().trim(),cat=el('designCategory').value,list=designs.filter(d=>(!cat||d.category===cat)&&d.name.toLowerCase().includes(q));el('designGrid').replaceChildren();el('designCount').textContent=list.length+' of '+designs.length+' design pictures';for(const d of list){const card=node('article','product-card'),b=node('button','art-card');b.append(picture(d.thumbnail||d.image,d.name));b.setAttribute('aria-label','Open '+d.name);b.onclick=()=>{active=d;el('designLarge').src=d.image;el('designLarge').alt=d.name;el('designTitle').textContent=d.name;el('chooseDesign').href='custom.html?design='+d.id;el('chooseDesign').hidden=d.kind==='reference';el('designKind').textContent=d.kind==='reference'?'Finished mockup / inspiration reference. Choose a standalone artwork picture to create your piece.':d.category+' · Choose this artwork for your custom piece.';buttons();el('designDialog').showModal();};card.append(b,node('div','eyebrow',d.category),node('h3','',d.name));el('designGrid').append(card);}if(!list.length)el('designGrid').append(node('p','notice','No matching design pictures.'));}el('designSearch').oninput=gallery;el('designCategory').onchange=gallery;gallery();el('closeDesign').onclick=()=>el('designDialog').close();for(const vote of ['like','dislike'])el(vote+'Design').onclick=()=>{preferences[active.id]=preferences[active.id]===vote?null:vote;try{localStorage.setItem('midnightDesignVotes',JSON.stringify(preferences));}catch{}buttons();};}
if(!el('conceptCanvas'))return;
let artwork=null,artBlob=null,artName='',artSource='',objectURL=null,db=null;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('midnightCustomStudio',1);r.onupgradeneeded=()=>r.result.createObjectStore('builds',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
try{db=await openDB();}catch{say('Browser storage is unavailable. You can still download your brief.');}
function database(mode,operation){return new Promise((resolve,reject)=>{if(!db)return reject(Error('storage'));const t=db.transaction('builds',mode),r=operation(t.objectStore('builds'));let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
for(const item of items){const o=node('option','',item.name);o.value=item.id;el('itemSelect').append(o);}
const query=new URLSearchParams(location.search);if(items.some(i=>i.id===query.get('item')))el('itemSelect').value=query.get('item');
function current(){return items.find(i=>i.id===el('itemSelect').value);}
function render(){const item=current();draw(el('conceptCanvas'),item,artwork,el('baseColor').value,Number(el('artScale').value),el('placement').value);el('previewName').textContent=item.name;el('printfulLink').href='https://www.printful.com/custom/collections/all-over-print?search='+encodeURIComponent(item.name);}
for(const id of ['itemSelect','placement','artScale','baseColor'])el(id).addEventListener('input',render);
let artVersion=0;
async function setArt(blob,name,source='upload'){const version=++artVersion,url=URL.createObjectURL(blob),img=new Image();img.src=url;try{await img.decode();if(version!==artVersion){URL.revokeObjectURL(url);return;}if(objectURL)URL.revokeObjectURL(objectURL);objectURL=url;artwork=img;artBlob=blob;artName=name;artSource=source;el('selectedArtwork').replaceChildren(picture(url,name),node('p','notice',name+' · '+img.width+' × '+img.height+' pixels'));render();say('Artwork ready. Choose your clothing and placement.');}catch{URL.revokeObjectURL(url);say('This image could not be opened. Try a PNG, JPG or WebP.');}}
async function upload(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){say('Choose a PNG, JPG or WebP image smaller than 20 MB.');return;}await setArt(file,file.name);}
el('artUpload').onchange=e=>upload(e.target.files[0]);const zone=el('dropZone');for(const ev of ['dragover','dragenter'])zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('dragging');});zone.ondragleave=()=>zone.classList.remove('dragging');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragging');upload(e.dataTransfer.files[0]);};
const chosen=designs.find(d=>d.id===query.get('design')&&d.kind!=='reference');if(chosen){try{const r=await fetch(chosen.image);if(!r.ok)throw Error();await setArt(await r.blob(),chosen.name,chosen.id);}catch{say('The artwork could not load. Choose another design or upload your own.');}}else el('selectedArtwork').append(node('p','notice','Choose a gallery design or upload your own image.'));
function brief(){const qty=Number(el('customQty').value);if(!artBlob)throw Error('Choose or upload artwork first.');if(!Number.isInteger(qty)||qty<1||qty>99)throw Error('Choose a quantity between 1 and 99.');return {id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:'draft — not submitted or paid',item:current(),artName,artSource,placement:el('placement').value,scale:Number(el('artScale').value),baseColor:el('baseColor').value,requestedSize:el('requestedSize').value.trim(),quantity:qty,notes:el('customNotes').value.trim(),productionNote:'Illustrated concept only. Confirm availability, size, price and garment panel print files before production.'};}
function readData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});}
function download(name,data){const url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=link('',url);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
el('downloadBuild').onclick=async()=>{try{const b=brief();b.artworkDataURL=await readData(artBlob);b.conceptPreview=el('conceptCanvas').toDataURL('image/png');download('midnight-custom-order-'+b.id+'.json',JSON.stringify(b,null,2));say('Order brief downloaded with artwork and preview. It has not been submitted.');}catch(e){say(e.message);}};
el('saveBuild').onclick=async()=>{try{const b=brief();b.artBlob=artBlob;b.preview=el('conceptCanvas').toDataURL('image/png');await database('readwrite',s=>s.put(b));await saved();say('Custom build saved on this device. No order or payment has been submitted.');}catch(e){say(e.message==='storage'?'Could not save in this browser. Download your brief instead.':e.message);}};
async function saved(){el('savedBuilds').replaceChildren();if(!db){el('savedBuilds').append(node('p','notice','Browser storage is unavailable.'));return;}let builds;try{builds=await database('readonly',s=>s.getAll());}catch{el('savedBuilds').append(node('p','notice','Saved builds could not load.'));return;}if(!builds.length)el('savedBuilds').append(node('p','notice','Your first custom piece starts above.'));for(const b of builds.reverse()){const card=node('article','product-card');card.append(picture(b.preview,b.item.name+' concept'),node('h3','',b.item.name),node('p','notice',b.artName+' / '+b.placement+' / Qty '+b.quantity));const edit=node('button','btn outline','Open build');edit.onclick=async()=>{el('itemSelect').value=b.item.id;el('placement').value=b.placement;el('artScale').value=b.scale;el('baseColor').value=b.baseColor;el('requestedSize').value=b.requestedSize;el('customQty').value=b.quantity;el('customNotes').value=b.notes;await setArt(b.artBlob,b.artName,b.artSource);el('conceptCanvas').scrollIntoView({behavior:'smooth'});};const remove=node('button','btn outline','Delete');remove.onclick=async()=>{try{await database('readwrite',s=>s.delete(b.id));await saved();}catch{say('Could not delete this build.');}};card.append(edit,remove);el('savedBuilds').append(card);}}
render();await saved();if(query.has('upload'))el('dropZone').scrollIntoView();
})();
