import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createService} from './server.mjs';
import {scryptSync} from 'node:crypto';
const origin='http://127.0.0.1:3033',password='browser-test-owner-only',salt='cd'.repeat(16),passwordHash=salt+':'+scryptSync(password,salt,64).toString('hex');
const {server}=createService({origin,passwordHash,dbPath:':memory:',secure:false});await new Promise(r=>server.listen(3033,'127.0.0.1',r));
const browser=await chromium.launch(),ownerContext=await browser.newContext(),customerContext=await browser.newContext(),owner=await ownerContext.newPage(),customer=await customerContext.newPage(),errors=[];
for(const p of [owner,customer])p.on('pageerror',e=>errors.push(e.message));
try{
 await customer.goto(origin);await customer.locator('#name').fill('Test customer');await customer.locator('#email').fill('customer@example.test');await customer.locator('#title').fill('Raven hoodie');await customer.locator('#brief').fill('Bone white raven on the back, small red moon on left sleeve. XL. Budget USD 150.');await customer.locator('#newForm button').click();await customer.locator('#reply').waitFor({state:'visible'});
 await owner.goto(origin);await owner.getByText('Owner sign-in',{exact:true}).click();await owner.locator('#password').fill(password);await owner.locator('#loginForm button').click();await owner.locator('#queue button').first().click();await owner.locator('#ownerControls').waitFor({state:'visible'});
 await customer.locator('#reply').fill('Can the moon be bigger?');await customer.locator('#replyForm button').first().click();await customer.waitForFunction(()=>document.querySelector('#reply').value==='');await owner.locator('#refreshThread').click();await owner.getByText('Can the moon be bigger?',{exact:true}).waitFor();
 await owner.locator('#reply').fill('Yes, here is version one.');await owner.locator('#replyForm button').first().click();await owner.waitForFunction(()=>document.querySelector('#reply').value==='');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jK1sAAAAASUVORK5CYII=','base64');await owner.locator('#imageFile').setInputFiles({name:'raven.png',mimeType:'image/png',buffer:png});await owner.locator('#uploadForm button').click();await owner.locator('#designAttachment option').waitFor({state:'attached'});await owner.locator('#designForm button').click();await owner.waitForFunction(()=>document.querySelector('#threadMeta').textContent.includes('Customer Review'));
 await customer.locator('#refreshThread').click();await customer.locator('#approvalForm').waitFor({state:'visible'});await customer.locator('#approveCheck').check();await customer.locator('#approvalForm button').click();await customer.waitForFunction(()=>document.querySelector('#threadMeta').textContent.includes('Approved'));
 await owner.locator('#refreshThread').click();await owner.locator('#designNote').fill('More texture');await owner.locator('#designForm button').click();await owner.waitForFunction(()=>document.querySelector('#threadMeta').textContent.includes('Customer Review'));await customer.locator('#refreshThread').click();await customer.locator('#approvalForm').waitFor({state:'visible'});assert.equal(await customer.locator('#approveCheck').isChecked(),false);
 await customer.locator('#reply').fill('Please fade the edges.');await customer.locator('#revision').click();await customer.waitForFunction(()=>document.querySelector('#threadMeta').textContent.includes('Revision Requested'));await owner.locator('#refreshThread').click();await owner.getByText('Please fade the edges.',{exact:true}).waitFor();
 for(const [width,height]of [[320,568],[390,844],[844,390],[768,1024],[1024,768],[1440,900]]){for(const [p,label]of [[customer,'customer'],[owner,'owner']]){await p.setViewportSize({width,height});const title=await p.locator('#threadTitle').innerText();await p.locator('#threadTitle').evaluate(el=>el.textContent='X'.repeat(200));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#threadTitle').evaluate((el,text)=>el.textContent=text,title);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'qa-conversation-'+label+'-'+width+'.png',fullPage:true});}}
 assert.equal(await customer.locator('#ownerControls').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS: separate owner/customer sessions, direct intake, two-way replies, private artwork, exact-version approval, revision requests and six responsive sizes.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
