import {AUDIENCES,productAudience,productFit,audienceMatches} from './factory-audiences.mjs';
import {randomUUID} from 'node:crypto';
export const FACTORY_ROLES=[['headwear','Headwear'],['facewear','Face coverings'],['shirts','Shirts'],['hoodies','Sweatshirts and hoodies'],['jackets','Jackets'],['pants','Pants'],['shorts','Shorts'],['underwear','Underwear'],['socks','Socks'],['footwear','Footwear'],['accessories','Accessories']];
export function factoryManager({db,auth,body,send,fail,limit,origin,fetchImpl=fetch,token=process.env.PRINTFUL_TOKEN}){
 db.exec(`CREATE TABLE IF NOT EXISTS factory_settings(id INTEGER PRIMARY KEY CHECK(id=1),state TEXT NOT NULL,daily_budget INTEGER NOT NULL,total_budget INTEGER NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_employees(id TEXT PRIMARY KEY,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS factory_jobs(id TEXT PRIMARY KEY,title TEXT NOT NULL,kind TEXT NOT NULL,employee TEXT NOT NULL,gender TEXT NOT NULL,brief TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_usage(id TEXT PRIMARY KEY,job TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>=0),created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_creator_profiles(id TEXT PRIMARY KEY,instructions TEXT NOT NULL DEFAULT '',templates TEXT NOT NULL DEFAULT '[]');
 CREATE TABLE IF NOT EXISTS factory_job_profiles(job TEXT PRIMARY KEY,instructions TEXT NOT NULL,templates TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_audience_profiles(id TEXT PRIMARY KEY,instructions TEXT NOT NULL,enabled INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_collection_styles(collection TEXT PRIMARY KEY,palette TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_job_audiences(job TEXT PRIMARY KEY,selection TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_events(id TEXT PRIMARY KEY,action TEXT NOT NULL,created TEXT NOT NULL);`);
 const now=()=>new Date().toISOString(),run=(sql,...a)=>db.prepare(sql).run(...a),get=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a);
 run('INSERT OR IGNORE INTO factory_settings VALUES(1,?,?,?,?)','stopped',0,0,now());
 // Retire the old separate Bags role without dropping its history; bags now belong to Accessories.
 if(get("SELECT id FROM factory_employees WHERE id='bags'")){run("UPDATE factory_jobs SET employee='accessories' WHERE employee='bags'");if(get("SELECT enabled FROM factory_employees WHERE id='bags'")?.enabled)run("UPDATE factory_employees SET enabled=1 WHERE id='accessories'");run("DELETE FROM factory_employees WHERE id='bags'");}
 for(const [id,name]of FACTORY_ROLES){run('INSERT OR IGNORE INTO factory_employees VALUES(?,?,0)',id,name);run('UPDATE factory_employees SET name=? WHERE id=?',name,id);run('INSERT OR IGNORE INTO factory_creator_profiles(id) VALUES(?)',id);}
 for(const id of AUDIENCES)run('INSERT OR IGNORE INTO factory_audience_profiles VALUES(?,?,?)',id,'',id==='children'?0:1);
 const rolePatterns={headwear:/\b(hats?|beanies?|caps?|visors?)\b/i,facewear:/\b(masks?|face cover\w*|gaiters?)\b/i,shirts:/\b(t[- ]?shirts?|shirts?|tank tops?|crop tops?|polos?)\b/i,hoodies:/\b(hoodies?|sweatshirts?|pullovers?)\b/i,jackets:/\b(jackets?|windbreakers?|coats?|outerwear)\b/i,pants:/\b(pants|joggers?|leggings?)\b/i,shorts:/\bshorts\b/i,underwear:/\b(underwear|briefs?|boxers?|bras?)\b/i,socks:/\bsocks?\b/i,footwear:/\b(shoes?|sneakers?|slides?|slippers?|flip.flops?)\b/i,accessories:/\b(bags?|backpacks?|bandanas?|bandannas?|scarves|scarf|belts?|aprons?|towels?|phone cases?|jewelry|pins?|patches|patch)\b/i};
 let catalogCache=null;
 async function catalog(){if(catalogCache&&Date.now()-catalogCache.time<300000)return catalogCache.data;if(!token)fail(503,'Connect Printful to verify creator product availability.');let r;try{r=await fetchImpl('https://api.printful.com/products',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});}catch{fail(502,'Printful catalog is unavailable. Assignments were not changed.');}if([401,403].includes(r.status))fail(503,'Supplier access needs reconnection.');if(!r.ok)fail(502,'Printful catalog lookup failed.');const data=await r.json();if(!Array.isArray(data.result))fail(502,'Printful returned an invalid catalog.');const products=data.result.filter(p=>Number.isSafeInteger(p.id)&&!p.is_discontinued).map(p=>({id:p.id,name:p.title||p.type_name||String(p.id),audiences:productAudience(p.title||''),fit:productFit(p.title||''),roles:FACTORY_ROLES.filter(([id])=>rolePatterns[id].test((p.type_name||p.type||'')+' '+(p.title||''))).map(([id])=>id)}));catalogCache={time:Date.now(),data:products};return products;}
 const variantCache=new Map();
 async function productDetails(id){const products=await catalog(),p=products.find(p=>p.id===id);if(!p)fail(400,'Product is not in the connected supplier catalog.');const cached=variantCache.get(id);if(cached&&Date.now()-cached.time<300000)return cached.data;let r;try{r=await fetchImpl('https://api.printful.com/products/'+id,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});}catch{fail(502,'Supplier variant lookup failed.');}if([401,403].includes(r.status))fail(503,'Supplier access needs reconnection.');if(!r.ok)fail(502,'Supplier variant lookup failed.');const result=(await r.json()).result;if(!Array.isArray(result?.variants))fail(502,'Supplier variant data is unavailable.');const variants=result.variants.filter(v=>Number.isSafeInteger(v.id)&&!v.is_discontinued&&!['discontinued','out_of_stock','temporary_out_of_stock'].includes(v.availability_status)).map(v=>({id:v.id,size:v.size||'',color:v.color||'',name:v.name||'',availability:v.availability_status||'not reported'}));const data={...p,variants,sizes:[...new Set(variants.map(v=>v.size).filter(Boolean))],source:'live Printful variants',stockNote:'Sizes come from supplier variants. Destination-specific stock and shipping are not verified here.'};variantCache.set(id,{time:Date.now(),data});return data;}
 function sharedArtwork(){return all('SELECT id,name,collection,kind,permissions FROM factory_artwork').map(a=>({...a,reusable:JSON.parse(a.permissions).reuse})).map(({permissions,...a})=>a);}
 async function selectionFor(b){const policy=get('SELECT * FROM factory_audience_profiles WHERE id=?',b.gender);if(!policy?.enabled)fail(409,'Enable this audience first.');if(b.selection===undefined)return {audience:b.gender,audienceInstructions:policy.instructions,product:null,fit:'',sizes:[],collection:'',artworkIds:[],palette:[]};const s=b.selection;if(!s||typeof s!=='object'||!['', 'oversized','relaxed','slim','regular','classic','fitted'].includes(s.fit)||!Array.isArray(s.sizes)||s.sizes.length>100||s.sizes.some(x=>typeof x!=='string'||x.length>40)||typeof s.collection!=='string'||s.collection.length>100||!Array.isArray(s.artworkIds)||s.artworkIds.length>100||s.artworkIds.some(x=>typeof x!=='string')||new Set(s.artworkIds).size!==s.artworkIds.length||new Set(s.sizes).size!==s.sizes.length)fail(400,'Invalid audience, fit, sizes or collection artwork.');let variants=[];if(s.product!==null){if(!Number.isSafeInteger(s.product))fail(400,'Choose a supplier product.');const p=await productDetails(s.product);if(!audienceMatches(p,b.gender)||!p.roles.includes(b.employee)||s.fit&&p.fit!==s.fit)fail(400,'Product does not match this audience, creator or fit.');if(s.sizes.some(size=>!p.sizes.includes(size)))fail(400,'Selected sizes are not supplied for this product.');variants=p.variants.filter(v=>!s.sizes.length||s.sizes.includes(v.size)).map(v=>v.id);if(!variants.length)fail(409,'No supplier variants match this selection.');}else if(s.fit||s.sizes.length)fail(400,'Choose a supplier product before setting fit or sizes.');const artwork=sharedArtwork();if(s.artworkIds.some(id=>!artwork.some(a=>a.id===id&&a.collection===s.collection&&a.reusable)))fail(400,'Shared artwork must belong to this collection and have Reuse permission.');return {...s,audience:b.gender,audienceInstructions:policy.instructions,variantIds:variants,palette:JSON.parse(get('SELECT palette FROM factory_collection_styles WHERE collection=?',s.collection)?.palette||'[]'),coordination:'Share artwork and palette; each cut still requires its own native-area blueprint and placement review.'};}
 function templates(){return all('SELECT id,title,product,variant,technique,areas FROM factory_print_drafts').map(d=>({...d,areas:JSON.parse(d.areas)}));}

 // No production worker is registered yet. Credentials alone must never imply running jobs.
 let production=null;const readiness=()=>production?.readiness()||{workerConnected:false,storageDurable:false};
 const event=action=>run('INSERT INTO factory_events VALUES(?,?,?)',randomUUID(),action,now());
 function snapshot(){const settings=get('SELECT * FROM factory_settings WHERE id=1'),usage=get('SELECT COALESCE(sum(amount),0) AS total,COALESCE(sum(CASE WHEN substr(created,1,10)=? THEN amount ELSE 0 END),0) AS daily FROM factory_usage',now().slice(0,10)),jobs=all('SELECT * FROM factory_jobs ORDER BY created DESC LIMIT 300').map(j=>{const p=get('SELECT * FROM factory_job_profiles WHERE job=?',j.id);return {...j,creatorInstructions:p?.instructions||'',assignedTemplates:JSON.parse(p?.templates||'[]'),audienceSelection:JSON.parse(get('SELECT selection FROM factory_job_audiences WHERE job=?',j.id)?.selection||'null')};});return {audiences:all('SELECT * FROM factory_audience_profiles').map(p=>({...p,enabled:!!p.enabled})),sharedArtwork:sharedArtwork(),collectionStyles:all('SELECT * FROM factory_collection_styles').map(c=>({...c,palette:JSON.parse(c.palette)})),settings,...readiness(),budget:{currency:'USD',timezone:'UTC',dailySpent:usage.daily,totalSpent:usage.total,dailyRemaining:Math.max(0,settings.daily_budget-usage.daily),totalRemaining:Math.max(0,settings.total_budget-usage.total),source:'Recorded factory usage only; no provider billing reconciliation is connected.'},employees:FACTORY_ROLES.map(([id])=>{const e=get('SELECT * FROM factory_employees WHERE id=?',id),p=get('SELECT * FROM factory_creator_profiles WHERE id=?',id),q=all('SELECT status,count(*) n FROM factory_jobs WHERE employee=? GROUP BY status',id);return {...e,enabled:!!e.enabled,instructions:p.instructions,templates:JSON.parse(p.templates),queue:q,currentTask:jobs.find(j=>j.employee===id&&j.status==='running')?.title||null,progress:{running:q.find(x=>x.status==='running')?.n||0,completed:q.filter(x=>x.status==='completed').reduce((n,x)=>n+x.n,0),total:q.reduce((n,x)=>n+x.n,0)}};}),jobs,events:all('SELECT action,created FROM factory_events ORDER BY created DESC,rowid DESC LIMIT 15')};}

 async function prepareJob(b,{replacementJobId=null}={}){if(typeof b.title!=='string'||!b.title.trim()||b.title.length>100||typeof b.brief!=='string'||!b.brief.trim()||b.brief.length>6000||!['outfit','product'].includes(b.kind)||!AUDIENCES.includes(b.gender)||!FACTORY_ROLES.some(([id])=>id===b.employee))fail(400,'Complete the design brief and select a creator.');if(!get('SELECT enabled FROM factory_employees WHERE id=?',b.employee)?.enabled)fail(409,'Enable this creator first.');if(get("SELECT count(*) n FROM factory_jobs WHERE status='queued'").n-(replacementJobId&&get('SELECT status FROM factory_jobs WHERE id=?',replacementJobId)?.status==='queued'?1:0)>=100)fail(409,'The queue is full (100 tasks).');const selection=await selectionFor(b),profile=get('SELECT * FROM factory_creator_profiles WHERE id=?',b.employee),id=randomUUID();let assigned=JSON.parse(profile.templates);if(assigned.length){const products=await catalog();assigned=assigned.filter(id=>{const t=get('SELECT product,variant FROM factory_print_drafts WHERE id=?',id),p=products.find(p=>p.id===t?.product);return p&&p.roles.includes(b.employee)&&audienceMatches(p,b.gender)&&(!selection.fit||p.fit===selection.fit)&&(selection.product===null||t.product===selection.product&&selection.variantIds.includes(t.variant));});}return {id,b,profile,selection,assigned};}
 function insertJob({id,b,profile,selection,assigned}){run('INSERT INTO factory_jobs(id,title,kind,employee,gender,brief,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?)',id,b.title.trim(),b.kind,b.employee,b.gender,b.brief.trim(),'queued',now(),now());run('INSERT INTO factory_job_profiles VALUES(?,?,?)',id,profile.instructions,JSON.stringify(assigned));run('INSERT INTO factory_job_audiences VALUES(?,?)',id,JSON.stringify(selection));event('Queued '+b.title.trim());return id;}
 return {setProduction(p){production=p;},prepareJob,insertJob,productDetails,async handle(req,res,path,method){if(!path.startsWith('/api/owner/ai-factory/'))return false;auth(req,null,true);
 if(method==='GET'&&path==='/api/owner/ai-factory/creator-catalog'){send(res,200,{products:await catalog(),templates:templates(),source:'live Printful catalog',fetchedAt:new Date(catalogCache.time).toISOString()});return true;}
 const variantRoute=path.match(/^\/api\/owner\/ai-factory\/audience-product\/(\d{1,7})$/);if(method==='GET'&&variantRoute){limit(req,'audience-variants',30);send(res,200,await productDetails(Number(variantRoute[1])));return true;}
 if(method==='GET'&&path==='/api/owner/ai-factory/jobs'){send(res,200,snapshot());return true;}
 if(method!=='POST')fail(405,'Use POST for factory changes.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'factory-manager',60);const b=await body(req);
 if(path.endsWith('/audience-profile')){if(!AUDIENCES.includes(b.id)||typeof b.instructions!=='string'||b.instructions.length>6000||typeof b.enabled!=='boolean'||b.id!=='children'&&!b.enabled)fail(400,'Invalid audience profile.');run('UPDATE factory_audience_profiles SET instructions=?,enabled=? WHERE id=?',b.instructions.trim(),Number(b.enabled),b.id);event('Updated audience '+b.id);
 }else if(path.endsWith('/collection-style')){if(typeof b.collection!=='string'||!b.collection.trim()||b.collection.length>100||!Array.isArray(b.palette)||b.palette.length>12||b.palette.some(c=>typeof c!=='string'||!/^#[a-f0-9]{6}$/i.test(c)))fail(400,'Choose a collection and up to 12 hex colors.');if(!sharedArtwork().some(a=>a.collection===b.collection))fail(400,'Choose an existing artwork collection.');run('INSERT INTO factory_collection_styles VALUES(?,?) ON CONFLICT(collection) DO UPDATE SET palette=excluded.palette',b.collection,JSON.stringify(b.palette));event('Updated collection palette');
 }else if(path.endsWith('/control')){if(!['start','pause','resume','stop','emergency-stop'].includes(b.action))fail(400,'Unknown factory action.');const s=get('SELECT * FROM factory_settings WHERE id=1');if(['start','resume'].includes(b.action)){if(!readiness().workerConnected)fail(409,'The background production worker is not connected. Jobs remain queued; no AI charges or publication were started.');if(!readiness().storageDurable)fail(409,'Persistent queue storage is required before starting unattended production.');if(!s.daily_budget||!s.total_budget)fail(409,'Set spending limits before starting.');}
 const state=b.action==='pause'?'paused':['start','resume'].includes(b.action)?'running':'stopped';db.exec('BEGIN IMMEDIATE');try{run('UPDATE factory_settings SET state=?,updated=? WHERE id=1',state,now());if(b.action==='emergency-stop')run("UPDATE factory_jobs SET status='cancelled',error='Cancelled by emergency stop',updated=? WHERE status IN ('queued','running','retry_wait','waiting_input')",now());event(b.action);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }else if(path.endsWith('/budget')){for(const k of ['dailyBudget','totalBudget'])if(!Number.isSafeInteger(b[k])||b[k]<0||b[k]>1000000)fail(400,'Use a budget between $0 and $10,000.');if(b.dailyBudget>b.totalBudget)fail(400,'Daily budget cannot exceed the total budget.');run('UPDATE factory_settings SET daily_budget=?,total_budget=?,updated=? WHERE id=1',b.dailyBudget,b.totalBudget,now());event('Budget updated');
 }else if(path.endsWith('/creator-profile')){if(!FACTORY_ROLES.some(([id])=>id===b.id)||typeof b.instructions!=='string'||b.instructions.length>6000||!Array.isArray(b.templates)||b.templates.length>50||b.templates.some(id=>typeof id!=='string')||new Set(b.templates).size!==b.templates.length)fail(400,'Invalid creator instructions or template assignments.');if(b.templates.length){const products=await catalog(),saved=templates();for(const id of b.templates){const d=saved.find(d=>d.id===id);if(!d||!products.some(p=>p.id===d.product&&p.roles.includes(b.id)))fail(400,'Choose saved blueprints for products currently listed in this creator’s supplier catalog.');}}run('UPDATE factory_creator_profiles SET instructions=?,templates=? WHERE id=?',b.instructions.trim(),JSON.stringify(b.templates),b.id);event('Updated creator profile '+b.id);
 }else if(path.endsWith('/employee')){if(!FACTORY_ROLES.some(([id])=>id===b.id)||typeof b.enabled!=='boolean')fail(400,'Invalid creator.');run('UPDATE factory_employees SET enabled=? WHERE id=?',Number(b.enabled),b.id);event((b.enabled?'Enabled ':'Disabled ')+b.id);
 }else if(path.endsWith('/enqueue')){const prepared=await prepareJob(b);db.exec('BEGIN IMMEDIATE');try{insertJob(prepared);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }else if(path.endsWith('/retry')){const job=get('SELECT * FROM factory_jobs WHERE id=?',typeof b.id==='string'?b.id:'');if(!job||job.status!=='failed')fail(409,'Only failed tasks can be retried.');if(job.attempts>=3)fail(409,'Retry limit reached. Review the brief before creating another task.');run("UPDATE factory_jobs SET status='queued',attempts=attempts+1,error='',updated=? WHERE id=? AND status='failed'",now(),job.id);event('Retry '+job.title);
 }else fail(404,'Factory action not found.');send(res,200,snapshot());return true;
 }};
}
