import {randomUUID,createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
const basePlacements=['front','back','left-sleeve','right-sleeve','hood'];
export function factoryArtwork({db,auth,body,send,fail,limit,origin,plans=JSON.parse(readFileSync(new URL('../printful-plans.json',import.meta.url),'utf8'))}){
 db.exec(`CREATE TABLE IF NOT EXISTS factory_artwork(id TEXT PRIMARY KEY,original TEXT NOT NULL,kind TEXT NOT NULL,name TEXT NOT NULL,collection TEXT NOT NULL,scope TEXT NOT NULL,target TEXT NOT NULL,product INTEGER,placements TEXT NOT NULL,instructions TEXT NOT NULL,permissions TEXT NOT NULL,mime TEXT NOT NULL,filename TEXT NOT NULL,data BLOB NOT NULL,bytes INTEGER NOT NULL,sha256 TEXT NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL);`);
 const get=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a),now=()=>new Date().toISOString();
 const products=Object.values(plans.products||{}).filter(p=>p.printfiles?.available_placements).map(p=>({id:p.catalogProductId,name:p.name,placements:p.printfiles.available_placements}));
 const clean=row=>{const {data,...rest}=row;return {...rest,placements:JSON.parse(row.placements),permissions:JSON.parse(row.permissions),url:'/api/owner/ai-factory/artwork/'+row.id+'/file'};};
 function metadata(b){for(const [key,max]of [['name',100],['collection',100],['target',120],['instructions',6000]])if(typeof b[key]!=='string'||b[key].length>max)fail(400,'Invalid '+key+'.');if(!b.name.trim()||!b.collection.trim()||!['product','outfit','collection'].includes(b.scope))fail(400,'Name, collection and usage scope are required.');const p=b.product===null?null:products.find(p=>p.id===b.product);if(b.product!==null&&!p)fail(400,'Select a supported product blueprint.');if(b.scope==='product'&&!p)fail(400,'Select a product for product-specific artwork.');if(b.scope==='outfit'&&!b.target.trim())fail(400,'Name the outfit this artwork belongs to.');const allowed=new Set([...basePlacements,...Object.keys(p?.placements||{})]);if(!Array.isArray(b.placements)||!b.placements.length||b.placements.length>30||b.placements.some(v=>!allowed.has(v)))fail(400,'Choose valid garment placements.');const keys=['reuse','recolor','crop','modify'];if(!b.permissions||keys.some(k=>typeof b.permissions[k]!=='boolean')||Object.keys(b.permissions).some(k=>!keys.includes(k)))fail(400,'Choose the artwork permissions.');return {...b,name:b.name.trim(),collection:b.collection.trim(),target:b.target.trim(),placements:[...new Set(b.placements)]};}
 function image(f){if(!f||typeof f.filename!=='string'||!f.filename.length||f.filename.length>180||/[\x00-\x1f\x7f]/.test(f.filename)||typeof f.base64!=='string'||f.base64.length>7000000||(f.base64.length%4!==0||!/^[A-Za-z0-9+/]*={0,2}$/.test(f.base64)))fail(400,'Invalid image upload.');const data=Buffer.from(f.base64,'base64');if(data.toString('base64')!==f.base64)fail(400,'Invalid image encoding.');if(data.length<12||data.length>5*1024*1024)fail(413,'Each image must be under 5 MB.');let mime;if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&data.length>=33&&data.toString('ascii',12,16)==='IHDR')mime='image/png';else if(data[0]===255&&data[1]===216&&data[2]===255&&data.at(-2)===255&&data.at(-1)===217)mime='image/jpeg';else if(data.toString('ascii',0,4)==='RIFF'&&data.toString('ascii',8,12)==='WEBP'&&['VP8 ','VP8L','VP8X'].includes(data.toString('ascii',12,16)))mime='image/webp';else fail(400,'Use PNG, JPEG or WebP images.');return {data,mime,filename:f.filename};}
 function insert(file,m,original,kind){const id=randomUUID(),date=now();db.prepare('INSERT INTO factory_artwork VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,original||id,kind,m.name,m.collection,m.scope,m.target,m.product,JSON.stringify(m.placements),m.instructions,JSON.stringify(m.permissions),file.mime,file.filename,file.data,file.data.length,createHash('sha256').update(file.data).digest('hex'),date,date);return id;}
 // Adds one original artwork from trusted backend code (the design-library import); same checks and limits as an owner upload.
 function importFile({data,filename},m){const file=image({filename,base64:data.toString('base64')}),meta=metadata(m);if(get('SELECT COALESCE(sum(bytes),0) bytes FROM factory_artwork').bytes+file.data.length>200*1024*1024||get('SELECT count(*) n FROM factory_artwork').n>=256)fail(413,'Artwork storage limit reached. Download your files before adding more.');return insert(file,meta,null,'original');}
 return {importFile,async handle(req,res,path,method){if(!path.startsWith('/api/owner/ai-factory/artwork'))return false;auth(req,null,true);
 if(method==='GET'&&path==='/api/owner/ai-factory/artwork'){send(res,200,{artworks:all('SELECT id,original,kind,name,collection,scope,target,product,placements,instructions,permissions,mime,filename,bytes,sha256,created,updated FROM factory_artwork ORDER BY created DESC').map(clean),products,blueprintUpdatedAt:plans.updatedAt,storageDurable:false});return true;}
 const download=path.match(/^\/api\/owner\/ai-factory\/artwork\/([a-f0-9-]{36})\/file$/);if(method==='GET'&&download){const row=get('SELECT * FROM factory_artwork WHERE id=?',download[1]);if(!row)fail(404,'Artwork not found.');res.writeHead(200,{'Content-Type':row.mime,'Content-Length':row.bytes,'Content-Disposition':"inline; filename*=UTF-8''"+encodeURIComponent(row.filename),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(row.data);return true;}
 if(method!=='POST')fail(405,'Use POST.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'factory-artwork',30);const b=await body(req);
 if(path.endsWith('/upload')){const m=metadata(b);if(!Array.isArray(b.files)||!b.files.length||b.files.length>10)fail(400,'Choose 1–10 images.');const files=b.files.map(image),bytes=files.reduce((n,f)=>n+f.data.length,0);if(bytes>8*1024*1024)fail(413,'Keep each batch under 8 MB.');if(get('SELECT count(*) n,COALESCE(sum(bytes),0) bytes FROM factory_artwork').bytes+bytes>200*1024*1024||get('SELECT count(*) n FROM factory_artwork').n+files.length>256)fail(413,'Artwork storage limit reached. Download your files before adding more.');db.exec('BEGIN IMMEDIATE');try{for(let i=0;i<files.length;i++)insert(files[i],{...m,name:files.length===1?m.name:(m.name+' / '+files[i].filename).slice(0,100)},null,'original');db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }else if(path.endsWith('/version')){const row=get('SELECT * FROM factory_artwork WHERE id=?',typeof b.id==='string'?b.id:'');if(!row)fail(404,'Original artwork not found.');const file=image(b.file),m=metadata(b);if(get('SELECT count(*) n,COALESCE(sum(bytes),0) bytes FROM factory_artwork').bytes+file.data.length>200*1024*1024||get('SELECT count(*) n FROM factory_artwork').n>=256)fail(413,'Artwork storage limit reached.');insert(file,m,row.original,'edited');
 }else if(path.endsWith('/update')){const m=metadata(b);if(!get('SELECT id FROM factory_artwork WHERE id=?',typeof b.id==='string'?b.id:''))fail(404,'Artwork not found.');db.prepare('UPDATE factory_artwork SET name=?,collection=?,scope=?,target=?,product=?,placements=?,instructions=?,permissions=?,updated=? WHERE id=?').run(m.name,m.collection,m.scope,m.target,m.product,JSON.stringify(m.placements),m.instructions,JSON.stringify(m.permissions),now(),b.id);
 }else fail(404,'Artwork action not found.');send(res,200,{artworks:all('SELECT id,original,kind,name,collection,scope,target,product,placements,instructions,permissions,mime,filename,bytes,sha256,created,updated FROM factory_artwork ORDER BY created DESC').map(clean),products,blueprintUpdatedAt:plans.updatedAt,storageDurable:false});return true;
 }};
}
