import {randomUUID} from 'node:crypto';
export const FACTORY_ROLES=[['headwear','Headwear'],['facewear','Face coverings'],['shirts','Shirts'],['hoodies','Sweatshirts and hoodies'],['jackets','Jackets'],['pants','Pants'],['shorts','Shorts'],['underwear','Underwear'],['socks','Socks'],['footwear','Footwear'],['accessories','Accessories']];
export function factoryManager({db,auth,body,send,fail,limit,origin,fetchImpl=fetch,token=process.env.PRINTFUL_TOKEN}){
 db.exec(`CREATE TABLE IF NOT EXISTS factory_settings(id INTEGER PRIMARY KEY CHECK(id=1),state TEXT NOT NULL,daily_budget INTEGER NOT NULL,total_budget INTEGER NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_employees(id TEXT PRIMARY KEY,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS factory_jobs(id TEXT PRIMARY KEY,title TEXT NOT NULL,kind TEXT NOT NULL,employee TEXT NOT NULL,gender TEXT NOT NULL,brief TEXT NOT NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_usage(id TEXT PRIMARY KEY,job TEXT NOT NULL,amount INTEGER NOT NULL CHECK(amount>=0),created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_creator_profiles(id TEXT PRIMARY KEY,instructions TEXT NOT NULL DEFAULT '',templates TEXT NOT NULL DEFAULT '[]');
 CREATE TABLE IF NOT EXISTS factory_job_profiles(job TEXT PRIMARY KEY,instructions TEXT NOT NULL,templates TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_events(id TEXT PRIMARY KEY,action TEXT NOT NULL,created TEXT NOT NULL);`);
 const now=()=>new Date().toISOString(),run=(sql,...a)=>db.prepare(sql).run(...a),get=(sql,...a)=>db.prepare(sql).get(...a),all=(sql,...a)=>db.prepare(sql).all(...a);
 run('INSERT OR IGNORE INTO factory_settings VALUES(1,?,?,?,?)','stopped',0,0,now());
 // Retire the old separate Bags role without dropping its history; bags now belong to Accessories.
 if(get("SELECT id FROM factory_employees WHERE id='bags'")){run("UPDATE factory_jobs SET employee='accessories' WHERE employee='bags'");if(get("SELECT enabled FROM factory_employees WHERE id='bags'")?.enabled)run("UPDATE factory_employees SET enabled=1 WHERE id='accessories'");run("DELETE FROM factory_employees WHERE id='bags'");}
 for(const [id,name]of FACTORY_ROLES){run('INSERT OR IGNORE INTO factory_employees VALUES(?,?,0)',id,name);run('UPDATE factory_employees SET name=? WHERE id=?',name,id);run('INSERT OR IGNORE INTO factory_creator_profiles(id) VALUES(?)',id);}
 const rolePatterns={headwear:/\b(hats?|beanies?|caps?|visors?)\b/i,facewear:/\b(masks?|face cover\w*|gaiters?)\b/i,shirts:/\b(t[- ]?shirts?|shirts?|tank tops?|crop tops?|polos?)\b/i,hoodies:/\b(hoodies?|sweatshirts?|pullovers?)\b/i,jackets:/\b(jackets?|windbreakers?|coats?|outerwear)\b/i,pants:/\b(pants|joggers?|leggings?)\b/i,shorts:/\bshorts\b/i,underwear:/\b(underwear|briefs?|boxers?|bras?)\b/i,socks:/\bsocks?\b/i,footwear:/\b(shoes?|sneakers?|slides?|slippers?|flip.flops?)\b/i,accessories:/\b(bags?|backpacks?|bandanas?|bandannas?|scarves|scarf|belts?|aprons?|towels?|phone cases?|jewelry|pins?|patches|patch)\b/i};
 let catalogCache=null;
 async function catalog(){if(catalogCache&&Date.now()-catalogCache.time<300000)return catalogCache.data;if(!token)fail(503,'Connect Printful to verify creator product availability.');let r;try{r=await fetchImpl('https://api.printful.com/products',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});}catch{fail(502,'Printful catalog is unavailable. Assignments were not changed.');}if(!r.ok)fail(502,'Printful catalog lookup failed.');const data=await r.json();if(!Array.isArray(data.result))fail(502,'Printful returned an invalid catalog.');const products=data.result.filter(p=>Number.isSafeInteger(p.id)).map(p=>({id:p.id,name:p.title||p.type_name||String(p.id),roles:FACTORY_ROLES.filter(([id])=>rolePatterns[id].test((p.type_name||p.type||'')+' '+(p.title||''))).map(([id])=>id)}));catalogCache={time:Date.now(),data:products};return products;}
 function templates(){return all('SELECT id,title,product,variant,technique,areas FROM factory_print_drafts').map(d=>({...d,areas:JSON.parse(d.areas)}));}

 // No production worker is registered yet. Credentials alone must never imply running jobs.
 const workerConnected=false;
 const event=action=>run('INSERT INTO factory_events VALUES(?,?,?)',randomUUID(),action,now());
 function snapshot(){const settings=get('SELECT * FROM factory_settings WHERE id=1'),usage=get('SELECT COALESCE(sum(amount),0) AS total,COALESCE(sum(CASE WHEN substr(created,1,10)=? THEN amount ELSE 0 END),0) AS daily FROM factory_usage',now().slice(0,10)),jobs=all('SELECT * FROM factory_jobs ORDER BY created DESC LIMIT 300').map(j=>{const p=get('SELECT * FROM factory_job_profiles WHERE job=?',j.id);return {...j,creatorInstructions:p?.instructions||'',assignedTemplates:JSON.parse(p?.templates||'[]')};});return {settings,workerConnected,storageDurable:false,budget:{currency:'USD',timezone:'UTC',dailySpent:usage.daily,totalSpent:usage.total,dailyRemaining:Math.max(0,settings.daily_budget-usage.daily),totalRemaining:Math.max(0,settings.total_budget-usage.total),source:'Recorded factory usage only; no provider billing reconciliation is connected.'},employees:FACTORY_ROLES.map(([id])=>{const e=get('SELECT * FROM factory_employees WHERE id=?',id),p=get('SELECT * FROM factory_creator_profiles WHERE id=?',id),q=all('SELECT status,count(*) n FROM factory_jobs WHERE employee=? GROUP BY status',id);return {...e,enabled:!!e.enabled,instructions:p.instructions,templates:JSON.parse(p.templates),queue:q,currentTask:jobs.find(j=>j.employee===id&&j.status==='running')?.title||null,progress:{running:q.find(x=>x.status==='running')?.n||0,completed:q.filter(x=>x.status==='completed').reduce((n,x)=>n+x.n,0),total:q.reduce((n,x)=>n+x.n,0)}};}),jobs,events:all('SELECT action,created FROM factory_events ORDER BY created DESC,rowid DESC LIMIT 15')};}
 return {async handle(req,res,path,method){if(!path.startsWith('/api/owner/ai-factory/'))return false;auth(req,null,true);
 if(method==='GET'&&path==='/api/owner/ai-factory/creator-catalog'){send(res,200,{products:await catalog(),templates:templates(),source:'live Printful catalog',fetchedAt:new Date(catalogCache.time).toISOString()});return true;}
 if(method==='GET'&&path==='/api/owner/ai-factory/jobs'){send(res,200,snapshot());return true;}
 if(method!=='POST')fail(405,'Use POST for factory changes.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'factory-manager',60);const b=await body(req);
 if(path.endsWith('/control')){if(!['start','pause','resume','stop','emergency-stop'].includes(b.action))fail(400,'Unknown factory action.');const s=get('SELECT * FROM factory_settings WHERE id=1');if(['start','resume'].includes(b.action)){if(!workerConnected)fail(409,'The background production worker is not connected. Jobs remain queued; no AI charges or publication were started.');if(!s.daily_budget||!s.total_budget)fail(409,'Set spending limits before starting.');}
 const state=b.action==='pause'?'paused':['start','resume'].includes(b.action)?'running':'stopped';db.exec('BEGIN IMMEDIATE');try{run('UPDATE factory_settings SET state=?,updated=? WHERE id=1',state,now());if(b.action==='emergency-stop')run("UPDATE factory_jobs SET status='cancelled',error='Cancelled by emergency stop',updated=? WHERE status IN ('queued','running')",now());event(b.action);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }else if(path.endsWith('/budget')){for(const k of ['dailyBudget','totalBudget'])if(!Number.isSafeInteger(b[k])||b[k]<0||b[k]>1000000)fail(400,'Use a budget between $0 and $10,000.');if(b.dailyBudget>b.totalBudget)fail(400,'Daily budget cannot exceed the total budget.');run('UPDATE factory_settings SET daily_budget=?,total_budget=?,updated=? WHERE id=1',b.dailyBudget,b.totalBudget,now());event('Budget updated');
 }else if(path.endsWith('/creator-profile')){if(!FACTORY_ROLES.some(([id])=>id===b.id)||typeof b.instructions!=='string'||b.instructions.length>6000||!Array.isArray(b.templates)||b.templates.length>50||b.templates.some(id=>typeof id!=='string')||new Set(b.templates).size!==b.templates.length)fail(400,'Invalid creator instructions or template assignments.');if(b.templates.length){const products=await catalog(),saved=templates();for(const id of b.templates){const d=saved.find(d=>d.id===id);if(!d||!products.some(p=>p.id===d.product&&p.roles.includes(b.id)))fail(400,'Choose saved blueprints for products currently listed in this creator’s supplier catalog.');}}run('UPDATE factory_creator_profiles SET instructions=?,templates=? WHERE id=?',b.instructions.trim(),JSON.stringify(b.templates),b.id);event('Updated creator profile '+b.id);
 }else if(path.endsWith('/employee')){if(!FACTORY_ROLES.some(([id])=>id===b.id)||typeof b.enabled!=='boolean')fail(400,'Invalid creator.');run('UPDATE factory_employees SET enabled=? WHERE id=?',Number(b.enabled),b.id);event((b.enabled?'Enabled ':'Disabled ')+b.id);
 }else if(path.endsWith('/enqueue')){if(typeof b.title!=='string'||!b.title.trim()||b.title.length>100||typeof b.brief!=='string'||!b.brief.trim()||b.brief.length>6000||!['outfit','product'].includes(b.kind)||!['women','men','unisex'].includes(b.gender)||!FACTORY_ROLES.some(([id])=>id===b.employee))fail(400,'Complete the design brief and select a creator.');if(!get('SELECT enabled FROM factory_employees WHERE id=?',b.employee)?.enabled)fail(409,'Enable this creator first.');if(get("SELECT count(*) n FROM factory_jobs WHERE status='queued'").n>=100)fail(409,'The queue is full (100 tasks).');const profile=get('SELECT * FROM factory_creator_profiles WHERE id=?',b.employee),id=randomUUID();db.exec('BEGIN IMMEDIATE');try{run('INSERT INTO factory_jobs(id,title,kind,employee,gender,brief,status,created,updated) VALUES(?,?,?,?,?,?,?,?,?)',id,b.title.trim(),b.kind,b.employee,b.gender,b.brief.trim(),'queued',now(),now());run('INSERT INTO factory_job_profiles VALUES(?,?,?)',id,profile.instructions,profile.templates);event('Queued '+b.title.trim());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }else if(path.endsWith('/retry')){const job=get('SELECT * FROM factory_jobs WHERE id=?',typeof b.id==='string'?b.id:'');if(!job||job.status!=='failed')fail(409,'Only failed tasks can be retried.');if(job.attempts>=3)fail(409,'Retry limit reached. Review the brief before creating another task.');run("UPDATE factory_jobs SET status='queued',attempts=attempts+1,error='',updated=? WHERE id=? AND status='failed'",now(),job.id);event('Retry '+job.title);
 }else fail(404,'Factory action not found.');send(res,200,snapshot());return true;
 }};
}
