import {FACTORY_ROLES} from './factory-manager.mjs';
const cents=v=>Number.isSafeInteger(v)&&v>=0&&v<=10000000;
export function validatePricingRule(r){if(!r||!['none','dollar','99'].includes(r.rounding)||typeof r.absorbShipping!=='boolean'||!['paymentFeeBps','platformFeeBps','marginBps','discountBps'].every(k=>Number.isInteger(r[k])&&r[k]>=0&&r[k]<=9500)||r.paymentFeeBps+r.platformFeeBps+r.marginBps>=10000||r.discountBps>=10000||!['paymentFixedCents','platformFixedCents','minimumProfitCents','minimumPriceCents','maximumPriceCents'].every(k=>cents(r[k]))||!r.maximumPriceCents||r.minimumPriceCents>r.maximumPriceCents)throw Error('Invalid fees, margin, discount, rounding or category price limits.');return r;}
export function assessPrice(rule,cost,actualPriceCents){if(!rule)return {status:'held',reason:'Save pricing rules for this category.'};validatePricingRule(rule);if(!cost||cost.verified!==true||cost.currency!=='USD'||!['supplierCents','extraCents'].every(k=>cents(cost[k]))||rule.absorbShipping&&!cents(cost.shippingCents))return {status:'held',reason:'Verified USD supplier, extra print/embroidery and absorbed shipping costs are required. Zero extra charges must be confirmed explicitly.'};const costCents=cost.supplierCents+cost.extraCents+(rule.absorbShipping?cost.shippingCents:0)+rule.paymentFixedCents+rule.platformFixedCents;
 const calc=price=>{const revenueCents=Math.floor(price*(10000-rule.discountBps)/10000),percentageFeesCents=Math.ceil(revenueCents*(rule.paymentFeeBps+rule.platformFeeBps)/10000),profitCents=revenueCents-percentageFeesCents-costCents;return {revenueCents,percentageFeesCents,profitCents};},meets=price=>{const c=calc(price);return c.revenueCents>0&&c.profitCents>=rule.minimumProfitCents&&c.profitCents*10000>=c.revenueCents*rule.marginBps;};
 const feeBps=rule.paymentFeeBps+rule.platformFeeBps;
 // Necessary lower bounds before integer-cent discount and fee rounding.
 const revenueNeeded=Math.max(1,Math.ceil((costCents+rule.minimumProfitCents)*10000/(10000-feeBps)),Math.ceil(costCents*10000/(10000-feeBps-rule.marginBps)));
 const low=Math.max(rule.minimumPriceCents,Math.ceil(revenueNeeded*10000/(10000-rule.discountBps)));
 let priceCents=rule.rounding==='99'?Math.ceil((low+1)/100)*100-1:rule.rounding==='dollar'?Math.ceil(low/100)*100:low;
 // Recheck after rounding: discounted integer-cent fee rounding can change profitability.
 const increment=rule.rounding==='none'?1:100;while(priceCents<=rule.maximumPriceCents&&!meets(priceCents))priceCents+=increment;
 if(priceCents>rule.maximumPriceCents)return {status:'held',reason:'No allowed price within the category maximum meets margin and minimum profit after fees, discounts and rounding.'};
 if(actualPriceCents!==undefined){if(!cents(actualPriceCents)||actualPriceCents<rule.minimumPriceCents||actualPriceCents>rule.maximumPriceCents||!meets(actualPriceCents)||rule.rounding==='99'&&actualPriceCents%100!==99||rule.rounding==='dollar'&&actualPriceCents%100!==0)return {status:'held',reason:'Publication price does not meet the current pricing rules.'};priceCents=actualPriceCents;}
 return {status:'ready',currency:'USD',priceCents,costCents,...calc(priceCents),discountBps:rule.discountBps,marginBps:rule.marginBps,reason:'All confirmed variant costs meet current rules at the maximum allowed discount.'};
}
export function factoryPricing({db,auth,body,send,fail,limit,origin}){
 db.exec(`CREATE TABLE IF NOT EXISTS factory_pricing_rules(category TEXT PRIMARY KEY,rule TEXT NOT NULL,updated TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS factory_pricing_costs(job TEXT NOT NULL REFERENCES factory_jobs(id),variant INTEGER NOT NULL,cost TEXT NOT NULL,updated TEXT NOT NULL,PRIMARY KEY(job,variant));`);
 const get=(s,...a)=>db.prepare(s).get(...a),all=(s,...a)=>db.prepare(s).all(...a),run=(s,...a)=>db.prepare(s).run(...a),now=()=>new Date().toISOString();
 function variants(job){const p=get('SELECT templates FROM factory_job_profiles WHERE job=?',job),ids=JSON.parse(p?.templates||'[]').map(id=>get('SELECT variant FROM factory_print_drafts WHERE id=?',id)?.variant);return ids.some(id=>!Number.isSafeInteger(id))?[]:[...new Set(ids)];}
 function assessJob(job,publicationPrices){const j=get('SELECT id,employee,title,status AS jobStatus FROM factory_jobs WHERE id=?',job);if(!j)fail(404,'Design job not found.');const row=get('SELECT rule,updated FROM factory_pricing_rules WHERE category=?',j.employee),rule=row?JSON.parse(row.rule):null,ids=variants(job);if(!ids.length)return {...j,status:'held',reason:'Assign exact supplier variant blueprints before pricing.',variants:[]};const results=ids.map(variant=>{const saved=get('SELECT cost,updated FROM factory_pricing_costs WHERE job=? AND variant=?',job,variant),cost=saved?JSON.parse(saved.cost):null;return {variant,cost,costUpdated:saved?.updated||null,...assessPrice(rule,cost,publicationPrices?.[variant])};});const held=results.find(r=>r.status==='held');return {...j,status:held?'held':'ready',reason:held?.reason||'Every assigned variant passes pricing.',ruleUpdated:row?.updated||null,variants:results};}
 function assertPublish(job,prices){if(typeof job!=='string'||!get('SELECT id FROM factory_jobs WHERE id=?',job))fail(404,'Design job not found.');const ids=variants(job);if(!prices||ids.some(id=>!Object.hasOwn(prices,id)))fail(409,'Supply the actual publication price for every supplier variant.');const result=assessJob(job,prices);if(result.status!=='ready')fail(409,'Pricing hold: '+result.reason);return result;}
 function snapshot(){return {currency:'USD',categories:FACTORY_ROLES.map(([id,name])=>({id,name})),rules:all('SELECT * FROM factory_pricing_rules').map(r=>({...r,rule:JSON.parse(r.rule)})),jobs:all('SELECT id FROM factory_jobs ORDER BY created DESC LIMIT 100').map(j=>assessJob(j.id)),note:'Rules apply to every assigned supplier variant and maximum discount. Costs are explicitly verified by the master account; supplier cost synchronization and automatic publishing are not connected.'};}
 return {assessJob,assertPublish,snapshot,async handle(req,res,path,method){if(!path.startsWith('/api/owner/ai-factory/pricing'))return false;auth(req,null,true);if(method==='GET'&&path==='/api/owner/ai-factory/pricing'){send(res,200,snapshot());return true;}if(method!=='POST')fail(405,'Use POST.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'factory-pricing',60);const b=await body(req);if(path.endsWith('/rule')){if(!FACTORY_ROLES.some(([id])=>id===b.category))fail(400,'Choose a clothing category.');try{validatePricingRule(b.rule);}catch(e){fail(400,e.message);}run('INSERT INTO factory_pricing_rules VALUES(?,?,?) ON CONFLICT(category) DO UPDATE SET rule=excluded.rule,updated=excluded.updated',b.category,JSON.stringify(b.rule),now());
 }else if(path.endsWith('/cost')){if(typeof b.job!=='string'||!get('SELECT id FROM factory_jobs WHERE id=?',b.job))fail(404,'Design job not found.');if(!Number.isSafeInteger(b.variant)||!variants(b.job).includes(b.variant))fail(400,'Choose an exact variant assigned to this design.');const c=b.cost;if(!c||c.verified!==true||c.currency!=='USD'||!cents(c.supplierCents)||!cents(c.extraCents)||(c.shippingCents!==null&&!cents(c.shippingCents))||typeof c.source!=='string'||!c.source.trim()||c.source.length>500)fail(400,'Verify supplier and extra charges in USD; supply a cost source and either a verified shipping cost or null.');run('INSERT INTO factory_pricing_costs VALUES(?,?,?,?) ON CONFLICT(job,variant) DO UPDATE SET cost=excluded.cost,updated=excluded.updated',b.job,b.variant,JSON.stringify(c),now());
 }else if(path.endsWith('/check-publication')){send(res,200,assertPublish(b.job,b.prices));return true;}else fail(404,'Unknown pricing action.');send(res,200,snapshot());return true;}};
}
