import {randomUUID} from 'node:crypto';
export const SUPPORT_ROLES=[
 ['art-director','Art director','Keep artwork, palette and collection consistent with Midnight Designs.'],
 ['template-technician','Template technician','Prepare separate files for the exact supplier variant and supported print areas.'],
 ['quality-reviewer','Quality reviewer','Check native placement dimensions, missing files and resolution; request visual review.'],
 ['merchandiser','Merchandiser','Write accurate titles, descriptions, tags and collection information.'],
 ['pricing','Pricing employee','Calculate prices from verified supplier costs, shipping, fees and margin.'],
 ['publishing','Publishing employee','Publish only approved products through connected supplier and store integrations.'],
 ['operations','Operations employee','Monitor failures, spending and unfinished jobs.']
];
export function calculatePrice({supplierCents,shippingCents,otherCents,feePercent,fixedFeeCents,marginPercent}){
 for(const value of [supplierCents,shippingCents,otherCents,fixedFeeCents])if(!Number.isSafeInteger(value)||value<0||value>1000000)throw Error('Use verified nonnegative costs in cents.');
 if(!Number.isFinite(feePercent)||feePercent<0||feePercent>30||!Number.isFinite(marginPercent)||marginPercent<0||marginPercent>=95||feePercent+marginPercent>=100)throw Error('Fees and target margin must leave a positive cost allowance.');
 const costCents=supplierCents+shippingCents+otherCents+fixedFeeCents,priceCents=Math.ceil(costCents/(1-(feePercent+marginPercent)/100));
 return {currency:'USD',priceCents,costCents,feePercent,marginPercent,note:'Estimate using owner-verified inputs. Destination taxes, currency conversion and any excluded costs must be handled separately. No store prices were changed.'};
}
export function factorySupport({db,auth,body,send,fail,limit,origin}){
 db.exec(`CREATE TABLE IF NOT EXISTS factory_support_profiles(id TEXT PRIMARY KEY,role TEXT NOT NULL,name TEXT NOT NULL,instructions TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS factory_support_tasks(job TEXT NOT NULL REFERENCES factory_jobs(id),profile TEXT NOT NULL,role TEXT NOT NULL,name TEXT NOT NULL,instructions TEXT NOT NULL,status TEXT NOT NULL,result TEXT NOT NULL DEFAULT '{}',PRIMARY KEY(job,profile));`);
 const run=(s,...a)=>db.prepare(s).run(...a),get=(s,...a)=>db.prepare(s).get(...a),all=(s,...a)=>db.prepare(s).all(...a);
 for(const [role,name,instructions]of SUPPORT_ROLES)run('INSERT OR IGNORE INTO factory_support_profiles VALUES(?,?,?,?,0)',role,role,name,instructions);
 function assign(job){for(const p of all('SELECT * FROM factory_support_profiles WHERE enabled=1'))run('INSERT OR IGNORE INTO factory_support_tasks(job,profile,role,name,instructions,status) VALUES(?,?,?,?,?,?)',job,p.id,p.role,p.name,p.instructions,'queued');}
 function checkpoint(job,step,result){const roles={validate:['art-director'],supplier:['template-technician'],files:['quality-reviewer'],review:['merchandiser','pricing','publishing','operations']}[step]||[];for(const role of roles){let report=result,status='checked';if(role==='art-director'){status='awaiting_integration';report={note:'Brand and palette guidance saved. An art-direction AI adapter and owner visual review are required.'};}if(role==='template-technician')report={...result,note:'Supplier variant verified. Artwork preparation and visual placement review remain required.'};if(role==='quality-reviewer')report={...result,note:'Required files match saved blueprint pixel dimensions. Visual composition, seams and source artwork quality require review.'};if(['merchandiser','pricing','publishing'].includes(role)){status='awaiting_integration';report={note:role==='pricing'?'Verified costs and a pricing policy are required before calculating selling prices.':role==='publishing'?'No automatic publishing adapter is connected. Owner approval is required.':'No merchandising AI adapter is connected. Listing copy remains to be prepared.'};}if(role==='operations')report={note:'Preparation checkpoint reached owner review. Generation and publication are still pending.'};run('UPDATE factory_support_tasks SET status=?,result=? WHERE job=? AND role=?',status,JSON.stringify(report),job,role);}}
 function snapshot(){const profiles=all('SELECT * FROM factory_support_profiles').map(p=>({...p,enabled:!!p.enabled})),tasks=all('SELECT t.*,j.title,j.status jobStatus,j.error FROM factory_support_tasks t JOIN factory_jobs j ON j.id=t.job ORDER BY j.created DESC LIMIT 500').map(t=>({...t,status:t.jobStatus==='cancelled'?'cancelled':t.status,result:JSON.parse(t.result)}));return {roles:SUPPORT_ROLES.map(([id,name])=>({id,name})),profiles,tasks,maxProfiles:50,concurrency:JSON.parse(get('SELECT policy FROM factory_production_policy WHERE id=1').policy).maxConcurrent,operations:{failed:get("SELECT count(*) n FROM factory_jobs WHERE status='failed'").n,unfinished:get("SELECT count(*) n FROM factory_jobs WHERE status IN ('queued','running','retry_wait','waiting_input','awaiting_review')").n,spentCents:get('SELECT COALESCE(sum(amount),0) n FROM factory_usage').n,reservedCents:get("SELECT COALESCE(sum(max_cost),0) n FROM factory_production_effects WHERE status='pending_confirmation'").n},note:'Supporting checks run within the parent job’s authenticated worker lease and shared concurrency/budget limits. No separate AI calls or automatic publication are connected.'};}
 return {assign,checkpoint,snapshot,async handle(req,res,path,method){if(!path.startsWith('/api/owner/ai-factory/support'))return false;auth(req,null,true);if(method==='GET'&&path==='/api/owner/ai-factory/support'){send(res,200,snapshot());return true;}if(method!=='POST')fail(405,'Use POST.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'factory-support',60);const b=await body(req);if(path==='/api/owner/ai-factory/support/price'){if(b.verified!==true)fail(400,'Confirm these costs were verified before calculating.');let result;try{result=calculatePrice(b);}catch(e){fail(400,e.message);}send(res,200,result);return true;}if(!['/api/owner/ai-factory/support/profile','/api/owner/ai-factory/support/create'].includes(path))fail(404,'Unknown support action.');if(!SUPPORT_ROLES.some(([id])=>id===b.role)||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.instructions!=='string'||b.instructions.length>6000||typeof b.enabled!=='boolean')fail(400,'Choose a role, name, instructions and enabled setting.');if(path.endsWith('/create')){if(get('SELECT count(*) n FROM factory_support_profiles').n>=50)fail(409,'Maximum 50 supporting employee profiles.');run('INSERT INTO factory_support_profiles VALUES(?,?,?,?,?)',randomUUID(),b.role,b.name.trim(),b.instructions.trim(),Number(b.enabled));}else{const p=get('SELECT * FROM factory_support_profiles WHERE id=?',typeof b.id==='string'?b.id:'');if(!p)fail(404,'Employee profile not found.');if(p.role!==b.role)fail(400,'An existing employee’s role cannot change. Create another profile.');run('UPDATE factory_support_profiles SET name=?,instructions=?,enabled=? WHERE id=?',b.name.trim(),b.instructions.trim(),Number(b.enabled),b.id);}send(res,200,snapshot());return true;}};
}
