import {randomBytes,createHash,createHmac,timingSafeEqual,createCipheriv,createDecipheriv} from 'node:crypto';
const hash=s=>createHash('sha256').update(s).digest('hex'),random=()=>randomBytes(24).toString('hex');
export function verifySignature(raw,header,secret,clock=Date.now()){
 if(!secret||typeof header!=='string')return false;
 const fields=header.split(',').map(p=>p.split('='));const timestamps=fields.filter(([k])=>k==='t');
 if(timestamps.length!==1||!/^\d+$/.test(timestamps[0][1]))return false;const timestamp=timestamps[0][1];
 if(Math.abs(clock/1000-Number(timestamp))>300)return false;
 const expected=createHmac('sha256',secret).update(timestamp+'.').update(raw).digest();
 return fields.some(([k,v])=>k==='v1'&&/^[a-f0-9]{64}$/.test(v||'')&&timingSafeEqual(expected,Buffer.from(v,'hex')));
}
export function paymentSystem({db,origin,storefrontOrigin,body,send,fail,limit,auth,settings={},fetchImpl=fetch,catalogLoader}){
 const config={enabled:process.env.PAYMENTS_ENABLED==='true',key:process.env.STRIPE_SECRET_KEY,webhook:process.env.STRIPE_WEBHOOK_SECRET,printful:process.env.PRINTFUL_TOKEN,storeId:process.env.PRINTFUL_STORE_ID,quoteSecret:process.env.CHECKOUT_SIGNING_SECRET,countries:(process.env.CHECKOUT_COUNTRIES||'US').split(','),live:process.env.PAYMENTS_LIVE==='true',...settings};
 const ready=()=>config.enabled&&!!config.key&&!!config.webhook&&!!config.printful&&typeof config.quoteSecret==='string'&&config.quoteSecret.length>=32&&config.countries.length>0&&(config.live?config.key.startsWith('sk_live_'):config.key.startsWith('sk_test_'));
 const get=(sql,...a)=>db.prepare(sql).get(...a);
 const secretKey=()=>createHash('sha256').update(config.quoteSecret||'').digest();
 const seal=payload=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',secretKey(),iv),data=Buffer.concat([cipher.update(JSON.stringify(payload)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64url');};
 function unseal(value){try{if(typeof value!=='string'||value.length>60000)throw Error();const raw=Buffer.from(value,'base64url'),decipher=createDecipheriv('aes-256-gcm',secretKey(),raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]));}catch{fail(404,'Checkout not found.');}}
 const proof=m=>createHmac('sha256',secretKey()).update([m.midnight_order,m.midnight_subtotal,m.midnight_shipping,m.midnight_receipt].join(':')).digest('hex');
 function trusted(session){const m=session.metadata||{};if(session.livemode!==config.live||!m.midnight_order||m.midnight_proof!==proof(m))fail(400,'Session does not match this store.');const subtotal=Number(m.midnight_subtotal),shipping=Number(m.midnight_shipping),tax=session.total_details?.amount_tax||0;if(!Number.isSafeInteger(subtotal)||subtotal<=0||!Number.isSafeInteger(shipping)||shipping<0)fail(400,'Order amounts are invalid.');if(session.payment_status==='paid'&&(session.currency!=='usd'||session.amount_subtotal!==subtotal||session.total_details?.amount_shipping!==shipping||session.total_details?.amount_discount!==0||!Number.isSafeInteger(tax)||tax<0||session.amount_total!==subtotal+shipping+tax))fail(400,'Paid amounts do not match the order.');return {subtotal,shipping,tax};}
 async function publicOrder(session){const amounts=trusted(session),items=await stripe('/checkout/sessions/'+encodeURIComponent(session.id)+'/line_items?limit=100');if(!Array.isArray(items.data)||items.has_more)fail(502,'Order items could not be loaded.');const charge=session.payment_intent?.latest_charge;let status=session.payment_status==='paid'?'paid':session.status==='expired'?'expired':'pending';if(charge?.amount_refunded>0)status=charge.refunded?'refunded':'partially_refunded';return {id:session.id,status,testMode:!session.livemode,currency:'USD',...amounts,total:session.amount_total,items:items.data.map(i=>({name:i.description,size:'',color:'',qty:i.quantity,unitAmount:i.price?.unit_amount}))};}
 const retrieve=id=>stripe('/checkout/sessions/'+encodeURIComponent(id)+'?expand[]=customer&expand[]=payment_intent.latest_charge');
 async function stripe(path,parameters,idempotency){const options={headers:{Authorization:'Bearer '+config.key,'Stripe-Version':'2025-02-24.acacia'},signal:AbortSignal.timeout(20000)};if(parameters){options.method='POST';options.headers['Content-Type']='application/x-www-form-urlencoded';options.headers['Idempotency-Key']=idempotency;options.body=new URLSearchParams(parameters);}const r=await fetchImpl('https://api.stripe.com/v1'+path,options);const value=await r.json();if(!r.ok){const e=value.error||{};const code=typeof e.code==='string'&&/^[a-z_]+$/.test(e.code)?e.code:'unknown';const param=typeof e.param==='string'&&/^[a-z_\[\]0-9]+$/.test(e.param)?e.param:'unknown';console.error('Stripe request rejected',JSON.stringify({status:r.status,code,param}));if(/tax/i.test(e.message||''))fail(502,'Stripe tax setup needs attention. The store owner must complete Stripe Tax settings before checkout can open.');if(r.status===401)fail(502,'Stripe could not authenticate the store. The store owner must check the payment key.');fail(502,'The payment provider could not complete checkout. Please try again.');}return value;}
 async function catalog(){if(catalogLoader)return catalogLoader();const r=await fetchImpl(storefrontOrigin+'/products.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)fail(503,'The catalog could not be verified.');return r.json();}
 function address(input){const a={};if(!input||typeof input!=='object')fail(400,'Enter your delivery address.');for(const field of ['name','email','address1','address2','city','state_code','country_code','zip']){const value=input[field]||'';if(typeof value!=='string'||value.length>200)fail(400,'Invalid delivery address.');a[field]=value.trim();}a.country_code=a.country_code.toUpperCase();a.state_code=a.state_code.toUpperCase();if(!config.countries.includes(a.country_code)||['name','address1','city','zip'].some(f=>!a[f])||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(a.email)||(['US','CA','AU'].includes(a.country_code)&&!a.state_code))fail(400,'Complete your delivery address and email.');return a;}
 async function lines(input){if(!Array.isArray(input)||!input.length||input.length>30)fail(400,'Your bag must contain 1–30 different items.');const data=await catalog();if(!Array.isArray(data.products))fail(503,'The catalog is unavailable.');const seen=new Set(),out=[];let count=0;for(const x of input){if(!x||typeof x.productId!=='string'||typeof x.variantId!=='string'||!Number.isInteger(x.qty)||x.qty<1||x.qty>20)fail(400,'Invalid bag item or quantity.');const key=x.productId+':'+x.variantId;if(seen.has(key))fail(400,'Duplicate bag item.');seen.add(key);count+=x.qty;if(count>50)fail(400,'Your bag is limited to 50 pieces.');const p=data.products.find(p=>p.id===x.productId),v=p?.variants.find(v=>String(v.id)===x.variantId);if(!v||v.availability!=='active'||!v.size||v.currency!=='USD'||!Number.isFinite(v.price)||v.price<=0||!Number.isInteger(v.catalogVariantId))fail(409,'A bag option is unavailable. Return to your bag and review it.');const amount=Math.round(v.price*100);if(!Number.isSafeInteger(amount)||amount>100000)fail(409,'A product price could not be verified.');out.push({productId:p.id,variantId:String(v.id),catalogVariantId:v.catalogVariantId,name:p.name,size:v.size,color:v.color||'Printed design',unitAmount:amount,qty:x.qty});}return out;}
 async function rates(items,recipient){const r=await fetchImpl('https://api.printful.com/shipping/rates',{method:'POST',headers:{Authorization:'Bearer '+config.printful,'Content-Type':'application/json',...(config.storeId?{'X-PF-Store-Id':config.storeId}:{})},body:JSON.stringify({recipient,items:items.map(x=>({variant_id:x.catalogVariantId,quantity:x.qty})),currency:'USD'}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok||!Array.isArray(data.result))fail(502,'Shipping could not be calculated for this address.');const options=data.result.filter(x=>x.currency==='USD'&&/^\d+(\.\d{1,2})?$/.test(String(x.rate))&&typeof x.id==='string').map(x=>({id:x.id,name:x.name||'Shipping',amount:Math.round(Number(x.rate)*100)})).filter(x=>Number.isSafeInteger(x.amount)&&x.amount>=0&&x.amount<=100000);if(!options.length)fail(422,'Shipping is unavailable for this address and bag.');return options;}
 return {async handle(req,res,path,method){
  if(!path.startsWith('/api/checkout/')&&path!=='/api/payments/webhook'&&path!=='/api/owner/payment-orders')return false;
  if(path==='/api/payments/webhook'){
   if(method!=='POST')fail(405,'Use POST.');if(!config.webhook)fail(503,'Payments are not connected.');let length=0,chunks=[];for await(const chunk of req){length+=chunk.length;if(length>1024*1024)fail(413,'Webhook too large.');chunks.push(chunk);}const raw=Buffer.concat(chunks);if(!verifySignature(raw,req.headers['stripe-signature'],config.webhook))fail(400,'Invalid webhook signature.');let event;try{event=JSON.parse(raw);}catch{fail(400,'Invalid webhook.');}if(typeof event.id!=='string')fail(400,'Invalid event.');
   if(['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'].includes(event.type)&&event.data?.object?.metadata?.midnight_order)trusted(await retrieve(event.data.object.id));
   // Stripe is the durable record. Webhooks have no local side effects to duplicate.
   send(res,200,{received:true});return true;
  }
  if(![origin,storefrontOrigin].includes(req.headers.origin))fail(403,'Origin rejected.');res.setHeader('Access-Control-Allow-Origin',req.headers.origin);res.setHeader('Vary','Origin');
  if(method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET, POST');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.writeHead(204);res.end();return true;}
  if(path==='/api/checkout/config'&&method==='GET'){send(res,200,{enabled:ready(),testMode:!config.live,countries:config.countries,provider:'stripe',storage:'stripe'});return true;}
  if(path==='/api/owner/payment-orders'&&method==='GET'){
   const bearer=req.headers.authorization?.match(/^Bearer ([a-f0-9]{64})$/)?.[1],owner=bearer&&get('SELECT role FROM sessions WHERE hash=? AND expires>?',hash(bearer),Date.now());if(owner?.role!=='owner')auth(req,null,true);
   if(!config.key)fail(503,'Stripe is not connected yet.');const result=await stripe('/checkout/sessions?limit=100');if(!Array.isArray(result.data))fail(502,'Orders could not be loaded.');const orders=[];for(const session of result.data.filter(s=>s.metadata?.midnight_order)){const full=await retrieve(session.id),order=await publicOrder(full),c=full.customer||{},a=c.shipping?.address||{};orders.push({...order,created:new Date(full.created*1000).toISOString(),delivery:{name:c.shipping?.name||c.name||'',email:c.email||'',address1:a.line1||'',address2:a.line2||'',city:a.city||'',state_code:a.state||'',zip:a.postal_code||'',country_code:a.country||''}});}send(res,200,orders);return true;
  }
  if(method!=='POST')fail(405,'Use POST.');limit(req,'checkout',20);const b=await body(req);
  if(path==='/api/checkout/status'){if(typeof b?.orderId!=='string'||!/^cs_(test_)?[A-Za-z0-9_]+$/.test(b.orderId)||typeof b?.receiptToken!=='string'||! /^[a-f0-9]{48}$/.test(b.receiptToken))fail(404,'Order not found.');if(!config.key)fail(503,'Stripe is not connected.');const session=await retrieve(b.orderId);if(session.metadata?.midnight_receipt!==hash(b.receiptToken))fail(404,'Order not found.');send(res,200,await publicOrder(session));return true;}
  if(!ready())fail(503,'Payments are not connected yet.');
  if(path==='/api/checkout/quote'){
   const recipient=address(b?.recipient),items=await lines(b?.items),shipping=await rates(items,recipient),receiptToken=random(),expires=Date.now()+10*60*1000,subtotal=items.reduce((n,x)=>n+x.unitAmount*x.qty,0),payload={id:random(),expires,receipt_hash:hash(receiptToken),items,recipient,shipping,subtotal};send(res,200,{quoteId:seal(payload),receiptToken,subtotal,shipping,currency:'USD',expiresAt:expires,testMode:!config.live});return true;
  }
  if(path==='/api/checkout/session'){
   const quote=unseal(b?.quoteId);if(quote.expires<Date.now())fail(409,'Your shipping quote expired. Calculate shipping again.');if(typeof b?.receiptToken!=='string'||hash(b.receiptToken)!==quote.receipt_hash)fail(404,'Checkout not found.');const p=quote,shipping=p.shipping.find(x=>x.id===b.shippingId);if(!shipping)fail(400,'Invalid shipping option.');const fresh=await lines(p.items);if(JSON.stringify(fresh)!==JSON.stringify(p.items))fail(409,'Your bag price or availability changed. Calculate shipping again.');
   const a=p.recipient;const customer=await stripe('/customers',{email:a.email,name:a.name,'shipping[name]':a.name,'shipping[address][line1]':a.address1,'shipping[address][line2]':a.address2,'shipping[address][city]':a.city,'shipping[address][state]':a.state_code,'shipping[address][postal_code]':a.zip,'shipping[address][country]':a.country_code},'midnight-customer-'+quote.id);
   // The receipt capability is supplied by the browser and checked against the quote.
   const params={mode:'payment',customer:customer.id,'billing_address_collection':'required','customer_update[address]':'auto','payment_method_types[0]':'card','automatic_tax[enabled]':'true','metadata[midnight_order]':quote.id,client_reference_id:quote.id,success_url:storefrontOrigin+'/checkout-result.html#order={CHECKOUT_SESSION_ID}&access='+b.receiptToken,cancel_url:storefrontOrigin+'/cart.html?checkout=cancelled','shipping_options[0][shipping_rate_data][type]':'fixed_amount','shipping_options[0][shipping_rate_data][display_name]':shipping.name,'shipping_options[0][shipping_rate_data][fixed_amount][amount]':String(shipping.amount),'shipping_options[0][shipping_rate_data][fixed_amount][currency]':'usd','shipping_options[0][shipping_rate_data][tax_behavior]':'exclusive',expires_at:String(Math.floor(quote.expires/1000)+1800)};
   const metadata={midnight_order:quote.id,midnight_subtotal:String(p.subtotal),midnight_shipping:String(shipping.amount),midnight_receipt:quote.receipt_hash};metadata.midnight_proof=proof(metadata);for(const [key,value]of Object.entries(metadata))params[`metadata[${key}]`]=value;
   p.items.forEach((x,i)=>{params[`line_items[${i}][price_data][currency]`]='usd';params[`line_items[${i}][price_data][unit_amount]`]=String(x.unitAmount);params[`line_items[${i}][price_data][tax_behavior]`]='exclusive';params[`line_items[${i}][price_data][product_data][name]`]=x.name+' / '+x.size+' / '+x.color;params[`line_items[${i}][quantity]`]=String(x.qty);});
   const session=await stripe('/checkout/sessions',params,'midnight-session-'+quote.id);if(session.payment_status==='paid')fail(409,'This order is already paid.');if(typeof session.id!=='string'||!session.url?.startsWith('https://checkout.stripe.com/'))fail(502,'The payment page could not be opened.');send(res,200,{url:session.url,orderId:session.id,testMode:!config.live});return true;
  }
  fail(404,'Not found.');
 }};
}
