import {randomUUID,createHash} from 'node:crypto';
export const REVIEW_SCORES=['quality','print','fit','comfort','value','shipping','overall'];
export function productReviews({db,products,auth,body,send,fail,limit,origin,storefrontOrigin}){
 const catalog=new Map(products.map(p=>[p.id,p]));db.exec(`CREATE TABLE IF NOT EXISTS product_reviews(id TEXT PRIMARY KEY,product TEXT NOT NULL,voter TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected')),content TEXT NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL,revision TEXT NOT NULL,UNIQUE(product,voter));`);
 const all=(sql,...args)=>db.prepare(sql).all(...args),run=(sql,...args)=>db.prepare(sql).run(...args);
 const view=row=>{const content=JSON.parse(row.content);return {id:row.id,productId:row.product,productName:catalog.get(row.product)?.name||'Archived product',status:row.status,created:row.created,updated:row.updated,revision:row.revision,...content,photos:content.photos.map((p,i)=>({url:'/api/product-review-photos/'+row.id+'/'+i}))};};
 const text=(s,max,required=false)=>{if(typeof s!=='string'||s.length>max||(required&&!s.trim()))fail(400,'Invalid review field.');return s.trim();};
 function validate(r){if(!r||REVIEW_SCORES.some(k=>!Number.isInteger(r[k])||r[k]<1||r[k]>5)||r.consent!==true)fail(400,'Complete all seven scores and confirm photo and review consent.');const clean=Object.fromEntries(REVIEW_SCORES.map(k=>[k,r[k]]));Object.assign(clean,{displayName:text(r.displayName,60,true),text:text(r.text,4000,true),size:text(r.size||'',40),color:text(r.color||'',60)});if(!Array.isArray(r.photos)||r.photos.length>3)fail(400,'Use up to three customer photos.');clean.photos=r.photos.map(p=>{if(!p||typeof p.data!=='string'||p.data.length>450000||! /^[A-Za-z0-9+/]+={0,2}$/.test(p.data))fail(400,'Invalid review photo.');const bytes=Buffer.from(p.data,'base64');if(bytes.length<12||bytes[0]!==255||bytes[1]!==216||bytes[2]!==255||bytes[bytes.length-2]!==255||bytes[bytes.length-1]!==217)fail(400,'Use JPEG review photos.');return {data:bytes.toString('base64')};});return clean;}
 return async(req,res,path,method,url)=>{
  const photo=path.match(/^\/api\/product-review-photos\/([a-f0-9-]{36})\/([0-2])$/);if(photo&&method==='GET'){const row=all('SELECT * FROM product_reviews WHERE id=?',photo[1])[0];if(!row)fail(404,'Photo not found.');if(row.status!=='approved')auth(req,null,true);const p=JSON.parse(row.content).photos[Number(photo[2])];if(!p)fail(404,'Photo not found.');res.setHeader('Content-Type','image/jpeg');res.end(Buffer.from(p.data,'base64'));return true;}
  if(path==='/api/product-reviews'){
   const allowed=req.headers.origin===origin||req.headers.origin===storefrontOrigin;
   if(method==='OPTIONS'){if(!allowed)fail(403,'Origin rejected.');res.setHeader('Access-Control-Allow-Origin',req.headers.origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET, POST');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.writeHead(204);res.end();return true;}
   if(allowed){res.setHeader('Access-Control-Allow-Origin',req.headers.origin);res.setHeader('Vary','Origin');}
   if(method==='GET'){const productId=url.searchParams.get('productId');if(!catalog.has(productId))fail(404,'Product not found.');const rows=all("SELECT * FROM product_reviews WHERE product=? AND status='approved' ORDER BY created DESC,id LIMIT 50",productId),summary=all("SELECT count(*) AS count,"+REVIEW_SCORES.map(k=>`avg(json_extract(content,'$.${k}')) AS ${k}`).join(',')+" FROM product_reviews WHERE product=? AND status='approved'",productId)[0],averages=Object.fromEntries(REVIEW_SCORES.map(k=>[k,summary[k]]));send(res,200,{count:summary.count,averages,reviews:rows.map(view)});return true;}
   if(method!=='POST'||!allowed)fail(403,'Origin rejected.');limit(req,'product-review',15);const b=await body(req);if(!b||!catalog.has(b.productId)||typeof b.voterId!=='string'||! /^[a-f0-9-]{36}$/.test(b.voterId))fail(400,'Invalid product review.');const voter=createHash('sha256').update(b.voterId).digest('hex');if(b.review===null){run('DELETE FROM product_reviews WHERE product=? AND voter=?',b.productId,voter);send(res,200,{ok:true});return true;}
   const review=validate(b.review),now=new Date().toISOString();run("INSERT INTO product_reviews VALUES(?,?,?,'pending',?,?,?,?) ON CONFLICT(product,voter) DO UPDATE SET content=excluded.content,status='pending',updated=excluded.updated,revision=excluded.revision",randomUUID(),b.productId,voter,JSON.stringify(review),now,now,randomUUID());send(res,200,{ok:true,status:'pending'});return true;
  }
  if(path==='/api/owner/product-reviews'){
   auth(req,null,true);if(method==='GET'){send(res,200,all('SELECT * FROM product_reviews ORDER BY updated DESC LIMIT 100').map(view));return true;}
   if(method!=='POST')fail(405,'Method not allowed.');if(req.headers.origin!==origin)fail(403,'Origin rejected.');limit(req,'review-moderation',100);const b=await body(req);if(!b||typeof b.id!=='string'||!['approved','rejected'].includes(b.status))fail(400,'Choose a review status.');if(!all('SELECT id FROM product_reviews WHERE id=?',b.id).length)fail(404,'Review not found.');const result=run('UPDATE product_reviews SET status=?,updated=? WHERE id=? AND revision=?',b.status,new Date().toISOString(),b.id,b.revision||'');if(!result.changes)fail(409,'This review changed. Refresh and check the latest submission.');send(res,200,{ok:true});return true;
  }
  return false;
 };
}
