import {test} from 'node:test';import assert from 'node:assert/strict';import {scryptSync,randomUUID} from 'node:crypto';import {createService} from './server.mjs';
test('Seven rating signals validate, update, aggregate separately and remain owner-only',async()=>{
 const origin='http://localhost:3000',salt='ab'.repeat(16),password='ratings-test-password',passwordHash=salt+':'+scryptSync(password,salt,64).toString('hex');const {server}=createService({dbPath:':memory:',origin,passwordHash,secure:false,designCatalog:[{id:'a',name:'Artwork',kind:'artwork'},{id:'r',name:'Reference',kind:'reference'}]});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const call=async(path,body,cookie,source=origin)=>{const r=await fetch(url+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{Origin:source,...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 try{assert.equal((await call('design-ratings')).status,401);const owner=(await call('owner/login',{password})).cookie,voter=randomUUID(),rating={overall:4,artwork:5,colors:2,style:3,wear:'Yes',buy:'Maybe',complexity:'Too busy'};const post=(r,v=voter,id='a',source=origin)=>call('design-ratings',{designId:id,voterId:v,rating:r},null,source);const totals=async()=> (await call('design-ratings',undefined,owner)).data[0];
 assert.equal((await post(rating)).status,200);await post(rating);assert.equal((await totals()).responses,1);await post({...rating,overall:2,buy:'No'});assert.equal((await totals()).averages.overall,2);const other=randomUUID();await post({...rating,overall:4,wear:'No',complexity:'Just right'},other);let t=await totals();assert.equal(t.responses,2);assert.equal(t.averages.overall,3);assert.equal(t.averages.artwork,5);assert.deepEqual(t.distributions.wear,{Yes:1,No:1});assert.deepEqual(t.distributions.buy,{Yes:0,Maybe:1,No:1});assert.equal(JSON.stringify(t).includes(voter),false);
 for(const bad of [{...rating,overall:6},{...rating,artwork:1.5},{...rating,colors:'5'},{...rating,buy:'Sure'},{...rating,wear:undefined},{...rating,complexity:'Busy'},{}])assert.equal((await post(bad)).status,400);
 assert.equal((await post(rating,voter,'r')).status,400);assert.equal((await post(rating,voter,'unknown')).status,400);assert.equal((await post(rating,voter,'a','https://evil.example')).status,403);const pre=await fetch(url+'/api/design-ratings',{method:'OPTIONS',headers:{Origin:'https://midnight-designs.store'}});assert.equal(pre.status,204);
 await post(null);assert.equal((await totals()).responses,1);await post(null,other);t=await totals();assert.equal(t.responses,0);assert.equal(t.averages.overall,null);
 }finally{await new Promise(r=>server.close(r));}
});
