import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const products=JSON.parse(fs.readFileSync('products.json')).products;const p=products[0],v=p.variants[0],other=p.variants[1],second=products.find(x=>x.id!==p.id&&x.variants.some(v=>v.color!==p.variants[0].color))||products[1],sv=second.variants[0],key='midnightCartV2',base='http://localhost:8000/';
const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const row=(p,v)=>page.locator('.item').filter({has:page.locator('[data-key="'+p.id+':'+v.id+'"]')});const item=(p,v)=>page.locator('[data-key="'+p.id+':'+v.id+'"]');
async function add(product,variant){await page.goto(base+'product.html?id='+product.id);await page.waitForSelector('#add:not([disabled])');await page.locator('#variant').selectOption(String(variant.id));await page.locator('#add').click();}
await add(p,v);await add(p,v);await add(p,other);await add(second,sv);await page.goto(base+'cart.html');await page.waitForSelector('.item');assert.equal(await page.locator('.item').count(),3);assert.equal(await item(p,v).locator('input').inputValue(),'2');assert.ok((await item(p,v).innerText()).includes('Size: '+v.size));assert.ok((await item(second,sv).innerText()).includes('Color / base: '+sv.color));const expected=v.price*2+other.price+sv.price;assert.equal(Number((await page.locator('#total').innerText()).replace(/[^0-9.]/g,'')),expected);
await item(p,v).locator('input').fill('3');await page.reload();await page.waitForSelector('.item');assert.equal(await item(p,v).locator('input').inputValue(),'3');
for(const invalid of ['0','100','1.5']){await item(p,v).locator('input').fill(invalid);await item(p,v).locator('input').dispatchEvent('change');assert.equal(await item(p,v).locator('input').inputValue(),'3');}
const tab=await context.newPage();await tab.goto(base+'cart.html');await tab.waitForSelector('.item');await tab.locator('[data-key="'+p.id+':'+v.id+'"] input').fill('4');await page.waitForFunction(()=>document.querySelector('.item input')?.value==='4');await tab.locator('[data-key="'+p.id+':'+other.id+'"] button').click();await page.waitForFunction(()=>document.querySelectorAll('.item').length===2);await tab.close();
await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw Error('Storage blocked')}});await item(p,v).locator('input').fill('5');assert.equal(await item(p,v).locator('input').inputValue(),'4');assert.ok((await page.locator('#cartStatus').innerText()).includes('could not save'));await page.reload();await page.waitForSelector('.item');assert.equal(await item(p,v).locator('input').inputValue(),'4');
const changed=structuredClone(products);changed[0].variants[0].price=v.price+5;await page.route('**/products.json',r=>r.fulfill({json:{products:changed}}));await page.reload();await page.waitForSelector('.item');assert.equal(Number((await page.locator('#total').innerText()).replace(/[^0-9.]/g,'')),(v.price+5)*4+sv.price);await page.unroute('**/products.json');
const unavailable=structuredClone(products);unavailable[0].variants=unavailable[0].variants.filter(x=>x.id!==v.id);await page.route('**/products.json',r=>r.fulfill({json:{products:unavailable}}));await page.reload();await page.waitForSelector('.item');assert.ok((await item(p,v).innerText()).includes('Unavailable'));assert.equal(await item(p,v).locator('input').count(),0);assert.equal(Number((await page.locator('#total').innerText()).replace(/[^0-9.]/g,'')),sv.price);await page.unroute('**/products.json');
await page.evaluate(({key,p,v})=>localStorage.setItem(key,JSON.stringify([{id:'bad',productId:p.id,variantId:v.id,qty:1},{id:'duplicate',productId:p.id,variantId:v.id,qty:2},{id:'broken',qty:8},{productId:p.id,variantId:v.id,qty:-2} ])),{key,p,v});await page.reload();await page.waitForSelector('.item');assert.equal(await page.locator('.item').count(),1);assert.equal(await page.locator('.item input').inputValue(),'3');
const photos=JSON.parse(fs.readFileSync('product-photos.json')).products;const bagImage=new URL(await page.locator('.item img').getAttribute('src')).pathname.slice(1);assert.ok(photos[p.id].photos.some(photo=>photo.image===bagImage&&photo.storeVariantIds.includes(v.id)));await page.screenshot({path:'qa-cart-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa-cart-mobile.png',fullPage:true});await page.locator('.item button').click();await page.reload();await page.waitForSelector('#items .notice');assert.equal(await page.locator('.item').count(),0);
await page.evaluate(key=>localStorage.setItem(key,'{broken'),key);await page.reload();await page.waitForSelector('#items .notice');assert.equal(await page.locator('.item').count(),0);assert.ok((await page.locator('#cartStatus').innerText()).includes('could not be read'));
assert.deepEqual(errors,[]);await browser.close();console.log('Reliable bag: correct variants, quantities, subtotal, refresh, immediate save, invalid quantities, tab sync, save failure, catalog price refresh, unavailable options, duplicate/corrupt data and mobile layout passed.');
