import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8000/';
await page.goto(base+'designs.html');await page.waitForSelector('.art-card');assert.equal(await page.locator('.art-card').count(),73);await page.locator('#designCategory').selectOption('Mockups & references');await page.locator('.art-card').first().click();assert.equal(await page.locator('#chooseDesign').isVisible(),false);await page.locator('#closeDesign').click();await page.locator('#designSearch').fill('no-such-picture');assert.equal(await page.locator('.art-card').count(),0);await page.locator('#designSearch').fill('');await page.locator('#designCategory').selectOption('');await page.locator('.art-card').first().click();await page.locator('#likeDesign').click();assert.equal(await page.locator('#likeDesign').getAttribute('aria-pressed'),'true');await page.locator('#chooseDesign').click();await page.waitForSelector('#selectedArtwork img');assert.equal(await page.locator('#layerList button').count(),1);
// Independent chest/back placements and direct manipulation.
await page.locator('#placement').selectOption('right-chest');await page.locator('#artUpload').setInputFiles('assets/designs/skull-crown.jpg');await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===2);await page.locator('#artScale').fill('85');await page.locator('#artScale').dispatchEvent('input');await page.locator('.advanced-tools summary').click();await page.locator('#artRotation').fill('30');await page.locator('#artRotation').dispatchEvent('input');await page.locator('#flipArt').click();await page.locator('#placement').selectOption('left-chest');await page.locator('#galleryArtwork').selectOption('blood-moon-reaper');await page.locator('#addGalleryArt').click();await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===3);await page.locator('#placement').selectOption('back');await page.locator('#addGalleryArt').click();await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===4);await page.locator('#coverageMode').selectOption('repeat');await page.locator('#requestedSize').fill('XL');
const box=await page.locator('#conceptCanvas').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.54);await page.mouse.up();assert.notEqual(await page.locator('#artX').inputValue(),'0');
// Hoodie-specific flat panels and all-panel coverage.
const hoodie=await page.locator('#itemSelect option').evaluateAll(os=>os.find(o=>o.textContent==='Unisex cotton hoodie').value);await page.locator('#itemSelect').selectOption(hoodie);await page.locator('#placement').selectOption('front');await page.locator('#fullCoverage').click();await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===11);assert.equal(await page.locator('#mapOverview canvas').count(),7);await page.locator('#placement').selectOption('left-hood');assert.equal(await page.locator('#coverageMode').inputValue(),'cover');await page.locator('#artRotation').fill('-20');await page.locator('#artRotation').dispatchEvent('input');await page.locator('#saveBuild').click();await page.waitForSelector('#savedBuilds article');await page.reload();await page.waitForSelector('#savedBuilds article');await page.locator('#savedBuilds button').first().click();await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===11);assert.equal(await page.locator('#requestedSize').inputValue(),'XL');assert.equal(await page.locator('#placement').inputValue(),'left-hood');assert.equal(await page.locator('#artRotation').inputValue(),'-20');
const downloadEvent=page.waitForEvent('download');await page.locator('#downloadBuild').click();const dl=await downloadEvent;const stream=await dl.createReadStream();let text='';for await(const chunk of stream)text+=chunk;const brief=JSON.parse(text);assert.equal(brief.version,3);assert.equal(brief.layers.length,11);assert.equal(brief.panelPreviews.length,7);assert.equal(brief.panels.length,9);assert(brief.artworks.every(a=>a.dataURL.startsWith('data:image/')));const right=brief.layers.find(l=>l.zone==='right-chest');assert.equal(right.rotation,30);assert.equal(right.flip,true);assert.equal(right.scale,85);assert(brief.layers.find(l=>l.zone==='left-chest'));assert(brief.layers.find(l=>l.zone==='back'&&l.mode==='repeat'));assert.match(brief.status,/not submitted/);
const mapEvent=page.waitForEvent('download');await page.locator('#downloadMap').click();const map=await mapEvent;assert.match(map.suggestedFilename(),/\.png$/);
await page.locator('.advanced-tools summary').click();await page.locator('#copyArt').click();assert.equal(await page.locator('#layerList button').count(),12);await page.locator('#removeArt').click();assert.equal(await page.locator('#layerList button').count(),11);await page.locator('#customQty').fill('0');await page.locator('#saveBuild').click();assert.match(await page.locator('#studioStatus').innerText(),/between 1 and 99/);await page.locator('#customQty').fill('1');
// Drag-drop creates a separate layer.
await page.locator('#dropZone').evaluate(zone=>{const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2l0AAAAASUVORK5CYII='),c=>c.charCodeAt(0));const dt=new DataTransfer();dt.items.add(new File([bytes],'dropped.png',{type:'image/png'}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:dt}));});await page.waitForFunction(()=>document.querySelectorAll('#layerList button').length===12);
// Existing single-artwork drafts remain readable.
await page.evaluate(async()=>{await new Promise((resolve,reject)=>{const r=indexedDB.open('midnightCustomStudio',1);r.onsuccess=async()=>{const db=r.result,artBlob=await fetch('assets/designs/skull-crown.jpg').then(r=>r.blob()),t=db.transaction('builds','readwrite');t.objectStore('builds').put({id:'legacy',createdAt:new Date().toISOString(),item:{id:'option-1',name:'Legacy tee'},artBlob,artName:'Legacy artwork',artSource:'upload',placement:'back',scale:65,baseColor:'#171717',requestedSize:'M',quantity:1,notes:'old draft',preview:''});t.oncomplete=resolve;t.onerror=reject;};r.onerror=reject;});});await page.reload();await page.waitForSelector('#savedBuilds article');await page.locator('#savedBuilds article').filter({hasText:'Legacy tee'}).getByText('Open build').click();await page.waitForFunction(()=>document.getElementById('selectedArtwork').textContent.includes('Legacy artwork'));assert.equal(await page.locator('#layerList button').count(),1);assert.equal(await page.locator('#placement').inputValue(),'back');assert.equal(await page.locator('#requestedSize').inputValue(),'M');
// Non-shirt garments must not offer chest, sleeve, or hood placements.
await page.locator('#itemSelect').selectOption({label:'Yoga leggings'});const options=await page.locator('#placement option').allTextContents();assert(options.includes('Left leg'));assert(!options.includes('Left chest'));assert(!options.includes('Left hood'));
for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.goto(base+'custom.html?design=blood-moon-reaper&item='+hoodie);await page.waitForSelector('#selectedArtwork img');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa-map-'+width+'.png',fullPage:true});}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: design vault, independent chest/front/back layers, drag, resize/rotation/flip, full hoodie panels, save/restore, complete exports, uploads/drop, legacy drafts, garment-specific placements, mobile.');
