import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import {renderOrderMessage} from '../order-messages.mjs';
const templates=JSON.parse(fs.readFileSync('order-email-templates.json')).templates;
for(const t of templates){const keys=[...new Set((t.subject+' '+t.body).match(/\{\{[A-Za-z]+\}\}/g))].map(k=>k.slice(2,-2));const values=Object.fromEntries(keys.map(k=>[k,'Example '+k]));const message=renderOrderMessage(t,values);assert.ok(!message.body.includes('{{'));assert.ok(message.body.includes('order-help.html'));delete values[keys[0]];assert.throws(()=>renderOrderMessage(t,values),/Missing message field/);}
assert.throws(()=>renderOrderMessage(templates[0],{orderNumber:'bad\r\nBcc: other'}),/Missing|Invalid/);
const browser=await chromium.launch(),page=await browser.newPage(),errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')posts.push(r.url())});
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('http://localhost:8000/order-help.html');assert.ok((await page.locator('main').innerText()).includes('cannot accept new orders'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa-order-help-'+width+'.png'});}
await page.getByRole('link',{name:'Help with a confirmation',exact:false}).click();await page.waitForFunction(()=>document.querySelector('#supportTopic').value==='Order confirmation');assert.ok((await page.locator('#topicHelp').innerText()).includes('duplicate order'));await page.locator('#supportEmail').fill('customer@example.test');await page.locator('#supportOrder').fill('MD-SAMPLE');await page.locator('#supportMessage').fill('My confirmation is missing.');await page.locator('#supportForm button').click();assert.ok((await page.locator('#preparedMessage').inputValue()).includes('MD-SAMPLE'));assert.equal(await page.locator('#openEmail').isVisible(),true);assert.ok((await page.locator('#openEmail').getAttribute('href')).startsWith('mailto:'+JSON.parse(fs.readFileSync('support-config.json')).email+'?'));
await page.route('**/support-config.json',r=>r.fulfill({json:{email:'help@example.test'}}));await page.goto('http://localhost:8000/order-help.html');await page.getByRole('link',{name:'Help with tracking',exact:false}).click();await page.waitForFunction(()=>document.querySelector('#supportTopic').value==='Tracking update');await page.waitForSelector('#directEmail:visible');assert.equal(await page.locator('#supportTopic').inputValue(),'Tracking update');await page.locator('#supportEmail').fill('customer@example.test');await page.locator('#supportOrder').fill('MD-123');await page.locator('#supportMessage').fill('Package 2 has no scan.');await page.locator('#supportForm button').click();const mail=await page.locator('#openEmail').getAttribute('href');assert.ok(new URLSearchParams(mail.split('?')[1]).get('body').includes('Package 2 has no scan.'));
await page.unroute('**/support-config.json');await page.goto('http://localhost:8000/master.html#orderCommunication');await page.waitForSelector('#orderTemplate option',{state:'attached'});assert.equal(await page.locator('#orderTemplate option').count(),3);for(const t of templates){await page.locator('#orderTemplate').selectOption(t.id);const text=await page.locator('#orderMessagePreview').inputValue();assert.ok(text.includes('DEMO ONLY'));assert.ok(!text.includes('{{'));assert.ok((await page.locator('#orderTrigger').innerText()).includes(t.trigger));}await page.waitForFunction(()=>document.querySelector('#orderInboxStatus').textContent.includes('published'));await page.screenshot({path:'qa-order-owner.png'});
for(const id of ['index','shop','product','cart','designs','catalog','custom','ai-designer','master','pricing','layout','shipping','returns','contact','order-help'])assert.ok(fs.readFileSync(id+'.html','utf8').includes('href="order-help.html"'),id+' order help link');
assert.equal(posts.length,0,'No sending or customer data submission');assert.deepEqual(errors,[]);await browser.close();console.log('Order help: responsive guide, confirmation/tracking topic handoffs, configured/unconfigured inbox behavior, draft templates, owner preview, missing-field rejection and no customer submission passed.');
