import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];page.on('request',r=>{if(r.method()!=='GET')requests.push(r.url())});
await page.goto('http://localhost:8000/returns.html');assert.ok((await page.locator('#rights').innerText()).includes('14 days'));assert.ok((await page.locator('#sizing').innerText()).includes('different size'));assert.ok((await page.locator('#damage').innerText()).includes('does not shorten your legal rights'));await page.screenshot({path:'qa-returns-desktop.png',fullPage:true});
await page.goto('http://localhost:8000/contact.html?topic=Cancellation%20or%20change');await page.waitForFunction(()=>document.querySelector('#contactStatus').textContent.includes('not available yet'));assert.equal(await page.locator('#supportTopic').inputValue(),'Cancellation or change');assert.equal(await page.locator('#directEmail').isVisible(),false);
await page.locator('#supportEmail').fill('customer@example.test');await page.locator('#supportOrder').fill('MD-123 & ?');await page.locator('#supportMessage').fill('Please cancel my order.');await page.locator('#supportForm button[type="submit"]').click();assert.equal(await page.locator('#messagePreview').isVisible(),true);assert.equal(await page.locator('#openEmail').isVisible(),false);assert.ok((await page.locator('#messageStatus').textContent()).includes('Nothing has been sent'));await page.screenshot({path:'qa-contact-desktop.png',fullPage:true});
await page.route('**/support-config.json',route=>route.fulfill({json:{email:'support@example.test'}}));await page.reload();await page.waitForSelector('#directEmail:visible');assert.equal(await page.locator('#directEmail').getAttribute('href'),'mailto:support@example.test');await page.locator('#supportEmail').fill('customer@example.test');await page.locator('#supportOrder').fill('MD-123 & ?');await page.locator('#supportMessage').fill('Photo problem & details?\nLine two.');await page.locator('#supportForm button[type="submit"]').click();const href=await page.locator('#openEmail').getAttribute('href');const params=new URLSearchParams(href.split('?')[1]);assert.ok(params.get('body').includes('Photo problem & details?\nLine two.'));assert.ok(params.get('subject').includes('MD-123 & ?'));assert.equal(requests.length,0,'Composer must not submit data');
await page.unroute('**/support-config.json');await page.route('**/support-config.json',r=>r.fulfill({json:{email:'bad@example.test\r\nBcc: attacker@example.test'}}));await page.reload();await page.waitForFunction(()=>document.querySelector('#contactStatus').textContent.includes('not available yet'));assert.equal(await page.locator('#directEmail').isVisible(),false);
for(const id of ['returns','contact']){await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:8000/'+id+'.html');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa-'+id+'-mobile.png',fullPage:true});}
for(const id of ['index','shop','product','cart','custom','designs','catalog','ai-designer','master','pricing','layout','shipping','returns','contact']){const html=fs.readFileSync(id+'.html','utf8');assert.ok(html.includes('href="returns.html"'),id);assert.ok(html.includes('href="contact.html"'),id);}
assert.deepEqual(errors,[]);await browser.close();console.log('Returns/support: policy links, legal rights, honest unconfigured state, configured email composer, safe message encoding, no data submission and desktop/mobile layout passed.');
