import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8000');
await page.waitForSelector('.hero-product img');
await page.locator('.hero-product img').evaluate(img=>img.decode());
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'qa-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'qa-mobile.png',fullPage:true});
await page.goto('http://127.0.0.1:8000/shop.html');
await page.waitForSelector('.product-card');
const count=await page.locator('.product-card').count();assert(count>0);
await page.locator('.product-image').first().click();
await page.waitForSelector('#add:not([disabled])');
await page.locator('#add').click();
await page.goto('http://127.0.0.1:8000/cart.html');
await page.waitForSelector('.item');
assert.equal(await page.locator('.item').count(),1);
await page.locator('.item input').fill('2');
await page.locator('.item input').dispatchEvent('change');
assert((await page.locator('#total').innerText()).includes('108'));
await page.locator('.item button').click();
assert.equal(await page.locator('.item').count(),0);
assert.equal(errors.length,0,errors.join('\n'));
await browser.close();console.log('PASS: live product mockup, desktop/mobile layout, product selection, bag add/quantity/remove.');
