import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8000/';
await page.goto(base+'catalog.html');await page.waitForSelector('#clothingGrid article');assert.equal(await page.locator('#clothingGrid article').count(),101);await page.locator('#clothingSearch').fill('bomber');assert.equal(await page.locator('#clothingGrid article').count(),1);await page.locator('#clothingGrid .btn').click();await page.waitForSelector('#itemSelect option',{state:'attached'});assert.match(await page.locator('#itemSelect option:checked').innerText(),/bomber/i);
await page.goto(base+'designs.html');await page.waitForSelector('.art-card');assert.equal(await page.locator('.art-card').count(),73);await page.locator('#designCategory').selectOption('Mockups & references');await page.locator('.art-card').first().click();assert.equal(await page.locator('#chooseDesign').isVisible(),false);await page.locator('#closeDesign').click();await page.locator('#designSearch').fill('no-such-artwork');assert.equal(await page.locator('.art-card').count(),0);await page.locator('#designSearch').fill('');await page.locator('#designCategory').selectOption('');await page.locator('.art-card').first().click();await page.locator('#likeDesign').click();assert.equal(await page.locator('#likeDesign').getAttribute('aria-pressed'),'true');await page.locator('#dislikeDesign').click();assert.equal(await page.locator('#likeDesign').getAttribute('aria-pressed'),'false');await page.locator('#chooseDesign').click();await page.waitForSelector('#selectedArtwork img');await page.locator('#placement').selectOption('back');await page.locator('#requestedSize').fill('XL');await page.locator('#saveBuild').click();await page.waitForSelector('#savedBuilds article');await page.reload();await page.waitForSelector('#savedBuilds article');await page.locator('#savedBuilds button').first().click();await page.waitForSelector('#selectedArtwork img');assert.equal(await page.locator('#requestedSize').inputValue(),'XL');assert.equal(await page.locator('#placement').inputValue(),'back');
await page.locator('#artUpload').setInputFiles('assets/designs/skull-crown.jpg');await page.waitForFunction(()=>document.getElementById('selectedArtwork').textContent.includes('skull-crown.jpg'));const event=page.waitForEvent('download');await page.locator('#downloadBuild').click();const dl=await event;const stream=await dl.createReadStream();let text='';for await(const chunk of stream)text+=chunk;const brief=JSON.parse(text);assert.match(brief.status,/not submitted/);assert.match(brief.artworkDataURL,/^data:image\/jpeg/);assert.equal(brief.artName,'skull-crown.jpg');await page.locator('#customQty').fill('0');await page.locator('#saveBuild').click();assert.match(await page.locator('#studioStatus').innerText(),/between 1 and 99/);await page.locator('#customQty').fill('1');
// Exercise drop handling with the same supported browser File type.
await page.locator('#dropZone').evaluate(zone=>{const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j2l0AAAAASUVORK5CYII='),c=>c.charCodeAt(0));const dt=new DataTransfer();dt.items.add(new File([bytes],'dropped.png',{type:'image/png'}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:dt}));});await page.waitForFunction(()=>document.getElementById('selectedArtwork').textContent.includes('dropped.png'));
await page.locator('#savedBuilds button').last().click();await page.waitForFunction(()=>!document.querySelector('#savedBuilds article'));
for(const width of [1440,390]){await page.setViewportSize({width,height:900});for(const route of ['catalog.html','designs.html','custom.html?design=blood-moon-reaper']){await page.goto(base+route);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow');if(route.startsWith('custom'))await page.waitForSelector('#selectedArtwork img');await page.screenshot({path:'qa-studio-'+width+'-'+route.split('.')[0]+'.png',fullPage:true});}}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 101 options, filters, design votes/selection, uploads/drop, preview, persistence, brief export, validation, delete, desktop/mobile.');
